dev/docker-compose.yaml

- Fix path from astronomer_operators to astronomer_providers in connections

HotFix: Fix path from astronomer_operators to astronomer_providers

---

astronomer/providers/amazon/aws/example_dags/example_redshift_cluster_management.py
astronomer/providers/amazon/aws/example_dags/example_redshift_sql.py
astronomer/providers/amazon/aws/example_dags/example_s3.py
astronomer/providers/amazon/aws/hooks/base_aws_async.py
astronomer/providers/amazon/aws/hooks/redshift_cluster.py
astronomer/providers/amazon/aws/hooks/redshift_data.py
astronomer/providers/amazon/aws/hooks/s3.py
astronomer/providers/amazon/aws/operators/redshift_cluster.py
astronomer/providers/amazon/aws/operators/redshift_sql.py
astronomer/providers/amazon/aws/sensors/redshift_cluster.py
astronomer/providers/amazon/aws/triggers/redshift_cluster.py
astronomer/providers/amazon/aws/triggers/redshift_sql.py
tests/amazon/aws/hooks/test_redshift_sql.py
tests/amazon/aws/operators/test_redshift_sql.py

- Fix mypy errors for amazon hooks, sensors, triggers and example DAG.
- Fix the test as per mypy changes
Part of issue: #65

Fix Amazon Providers mypy errors 

---

astronomer/providers/amazon/aws/triggers/redshift_cluster.py
astronomer/providers/snowflake/triggers/snowflake_trigger.py
tests/amazon/aws/hooks/test_redshift_cluster.py
tests/amazon/aws/hooks/test_redshift_sql.py
tests/amazon/aws/operators/test_redshift_cluster.py
tests/amazon/aws/operators/test_redshift_sql.py
tests/amazon/aws/sensors/test_redshift_sensor.py
tests/amazon/aws/triggers/test_redshift_cluster.py
tests/amazon/aws/triggers/test_redshift_sql.py
tests/snowflake/hooks/test_snowflake_async.py
tests/snowflake/operators/test_snowflake_async.py
tests/snowflake/triggers/test_snowflake.py

Story Id: https://app.zenhub.com/workspaces/airflow-providers-team-61a89ee7fbf048001dc8378d/issues/astronomer/astronomer-providers/87
- Fixed Test case for snowflake and Redshift to improve code coverage points

Fix Code coverage

---

setup.cfg

Based on https://github.com/pypa/trove-classifiers/pull/87

Add Apache Airflow classifiers

---

astronomer/providers/google/cloud/example_dags/example_gcs.py

Add Delay to GCS sensors DAG

---

CONTRIBUTING.rst

- Add Guideline to write an example DAG
- Add a section for considerations while writing Async or Deferrable Operator
- Step by step guide to writing your own Deferrable or Async Operator.
- Add a section for coding style and best practices
- Add a section for static code checks
- Add a section for installing and running Pre-commit hooks.
closes: #76

Update the contributing guide 

---

CONTRIBUTING.rst
Makefile
dev/.dockerignore

This will allow rebuilding the docker-image whenever needed, example after we added new deps

Dev: Add make command to rebuild Docker image

---

astronomer/providers/amazon/aws/example_dags/example_redshift_cluster_management.py
astronomer/providers/amazon/aws/example_dags/example_redshift_sql.py
astronomer/providers/amazon/aws/example_dags/example_s3.py
astronomer/providers/cncf/kubernetes/example_dags/example_kubernetes_pod_operator.py
astronomer/providers/core/example_dags/example_external_task.py
astronomer/providers/core/example_dags/example_external_task_wait_for_me.py
astronomer/providers/core/example_dags/example_file_sensor.py
astronomer/providers/databricks/example_dags/example_databricks.py
astronomer/providers/google/cloud/example_dags/example_bigquery_queries.py
astronomer/providers/google/cloud/example_dags/example_gcs.py
astronomer/providers/http/example_dags/example_http.py
astronomer/providers/snowflake/example_dags/example_snowflake.py

issue: #63 
Parameterize example dags to run automation test

Parameterize example DAGs for integration tests

---

astronomer/providers/amazon/aws/example_dags/example_redshift_sql.py

Fix broken dependency of redshift sql example

---

.pre-commit-config.yaml
README.rst

https://github.com/PyCQA/bandit - Bandit is a tool designed to find common security issues in Python code.

Add `bandit` pre-commit for Security scanning

---

docs/conf.py
setup.cfg

Since 1.1.0 is released, we should bump this version

Bump version to 1.2.0.dev1

---

CONTRIBUTING.rst
Makefile
docs/conf.py

- It will be convenient to build docs using top-level make command by just running `make docs`

Add top-level make command for building docs

---

astronomer/providers/google/cloud/example_dags/example_dataproc.py
astronomer/providers/google/cloud/hooks/dataproc.py
astronomer/providers/google/cloud/operators/dataproc.py
astronomer/providers/google/cloud/triggers/dataproc.py
tests/google/cloud/hooks/test_dataproc.py
tests/google/cloud/operators/test_dataproc.py
tests/google/cloud/triggers/test_dataproc.py

Story id https://github.com/astronomer/astronomer-providers/issues/132
Implement DataprocSubmitJobOperatorAsync and DataprocSubmitTrigger and DataporcHookAsync

Implement  DataprocSubmitJobOperatorAsync

---

astronomer/providers/amazon/aws/operators/redshift_cluster.py

- Added Doc string to capture whatever found while doing integration testing

Update Docstrings for redshift cluster operators

---

astronomer/providers/amazon/aws/hooks/redshift_data.py
astronomer/providers/amazon/aws/hooks/redshift_sql.py
astronomer/providers/amazon/aws/operators/redshift_sql.py
astronomer/providers/amazon/aws/sensors/redshift_cluster.py
astronomer/providers/amazon/aws/sensors/s3.py
astronomer/providers/amazon/aws/triggers/redshift_cluster.py
astronomer/providers/amazon/aws/triggers/redshift_sql.py
astronomer/providers/amazon/aws/triggers/s3.py
astronomer/providers/google/cloud/hooks/bigquery.py
astronomer/providers/google/cloud/hooks/gcs.py
astronomer/providers/google/cloud/operators/bigquery.py
astronomer/providers/google/cloud/triggers/bigquery.py
astronomer/providers/google/common/hooks/base_google.py
astronomer/providers/snowflake/hooks/snowflake.py
astronomer/providers/snowflake/operators/snowflake.py
astronomer/providers/snowflake/triggers/snowflake_trigger.py

- Fixed Doc string for Snowflake, Redshift, BigQuery, S3 operators

Fix Doc string for Operators

---

.circleci/integration-tests/Dockerfile
astronomer/providers/amazon/aws/example_dags/example_redshift_cluster_management.py
astronomer/providers/amazon/aws/example_dags/example_redshift_sql.py
astronomer/providers/amazon/aws/example_dags/example_s3.py

Issue: https://github.com/astronomer/astronomer-providers/issues/165
Add the first task to create a Redshift cluster and the last task to delete the redshift cluster RedshiftPauseClusterOperatorAsync and RedshiftSQLOperatorAsync.

Automate redshift cluster creation

---

.pre-commit-config.yaml

This PR/commits bumps versions for existing pre-commit hooks

Update pre-commits hooks

---

astronomer/providers/amazon/aws/example_dags/example_emr.py
astronomer/providers/amazon/aws/hooks/emr.py
astronomer/providers/amazon/aws/sensors/emr.py
astronomer/providers/amazon/aws/triggers/emr.py
tests/amazon/aws/hooks/test_emr.py
tests/amazon/aws/sensors/test_emr_sensors.py
tests/amazon/aws/triggers/test_emr.py

Story id : https://github.com/astronomer/astronomer-providers/issues/120
- Added Sensor, Hook, Trigger
- Added Test case for Hook, Trigger, sensors
- Added doc string, mypy fix

Implement Async EMR container sensor async

---

CHANGELOG.rst
docs/conf.py
setup.cfg

Update the release version and `CHANGELOG.rst` for release 1.2.0

Releasing 1.2.0

---

docs/conf.py
setup.cfg

Since 1.2.0 is released, we should bump this version

Bump version to 1.3.0.dev1

---

.circleci/integration-tests/master_dag.py
astronomer/providers/apache/livy/example_dags/example_livy.py
setup.cfg

- Add self-sufficient example DAG for LivyOperatorAsync.
- The pem file content has to be added as Variable.
Closes: #231

Livy operator async example dag

---

tests/google/cloud/hooks/test_gcs.py
tests/google/cloud/sensors/test_gcs.py
tests/google/cloud/triggers/test_gcs.py
tests/snowflake/hooks/test_snowflake_async.py
tests/snowflake/operators/test_snowflake_async.py

Remove the Apache license content from the repo

Remove Apache License from repo

---

.circleci/integration-tests/master_dag.py
astronomer/providers/microsoft/azure/example_dags/example_adf_run_pipeline.py
astronomer/providers/microsoft/azure/hooks/data_factory.py
astronomer/providers/microsoft/azure/operators/data_factory.py
astronomer/providers/microsoft/azure/triggers/data_factory.py
tests/microsoft/azure/operators/test_data_factory.py
tests/microsoft/azure/triggers/test_data_factory.py

Implement AzureDataFactoryRunPipelineOperatorAsync
- Add operator/hook/trigger 
- Unit test for operator/trigger
Hook tests & examples depend on: https://github.com/astronomer/astronomer-providers/pull/253
Closes #186

Add AzureDataFactoryRunPipelineOperatorAsync

---

astronomer/providers/apache/hive/example_dags/example_hive.py

- Update the table data location needed to create a hive table.  
- modify the location since the hive feature branch got merged to the main branch.

Update hive table data path in `HivePartitionSensorAsync`

---

astronomer/providers/apache/hive/sensors/hive_partition.py

- update docstring in `HivePartitionSensorAsync` 
- correct typo and add `auth_mechanism='PLAIN'` only

Update docstring in `HivePartitionSensorAsync`

---

astronomer/providers/microsoft/azure/example_dags/example_adf_run_pipeline.py

Closes: #267 
1. Update the task names to be more meaningful (run_pipeline_op -> run_pipeline_no_wait and run_pipeline_op1 -> run_pipeline_wait)
2. Make execution time configurable

Update example DAG for `AzureDataFactoryPipelineRunStatusSensorAsync`

---

.readthedocs.yaml
astronomer/providers/amazon/aws/hooks/redshift_data.py
astronomer/providers/amazon/aws/operators/redshift_sql.py
astronomer/providers/google/cloud/sensors/gcs.py
astronomer/providers/http/triggers/http.py

- There were duplicate params description
- No docstrings for some
- and `.readthedocs.yaml` was missing the "all" extra which is needed to show params from inherited class

Fix some of the docstrings

---

.pre-commit-config.yaml
astronomer/providers/amazon/aws/triggers/emr.py
astronomer/providers/amazon/aws/triggers/redshift_cluster.py
astronomer/providers/amazon/aws/triggers/redshift_sql.py
astronomer/providers/amazon/aws/triggers/s3.py
astronomer/providers/apache/hive/triggers/hive_partition.py
astronomer/providers/apache/livy/triggers/livy.py
astronomer/providers/core/triggers/external_task.py
astronomer/providers/core/triggers/filesystem.py
astronomer/providers/databricks/triggers/databricks.py
astronomer/providers/google/cloud/triggers/bigquery.py
astronomer/providers/google/cloud/triggers/dataproc.py
astronomer/providers/google/cloud/triggers/gcs.py
astronomer/providers/http/triggers/http.py
astronomer/providers/microsoft/azure/triggers/data_factory.py
astronomer/providers/snowflake/triggers/snowflake_trigger.py
tests/amazon/aws/triggers/test_emr.py
tests/amazon/aws/triggers/test_redshift_cluster.py
tests/amazon/aws/triggers/test_redshift_sql.py
tests/amazon/aws/triggers/test_s3_triggers.py
tests/apache/hive/triggers/test_hive_partition.py
tests/apache/livy/triggers/test_livy.py
tests/databricks/triggers/test_databricks.py
tests/google/cloud/triggers/test_bigquery.py
tests/google/cloud/triggers/test_dataproc.py
tests/google/cloud/triggers/test_gcs.py
tests/microsoft/azure/triggers/test_data_factory.py
tests/snowflake/triggers/test_snowflake.py

Closes: #271 
Remove unused return statement from all trigger run methods i.e now trigger run method will only yield

Remove return stmt after yield from trigger

---

astronomer/providers/amazon/aws/triggers/emr.py
tests/amazon/aws/triggers/test_emr.py

EmrContainerSensor currently does not respect max_retries parameter. After this changes, it will timeout after max_retries limit exceed 
closes: #241

Include timeout on EmrContainerSensorTrigger

---

CHANGELOG.rst
docs/conf.py
setup.cfg

This commit publishes 1.3.0beta1 to allow testing with Airflow 2.3 and new version of Providers
Co-Authored-By: Phani Kumar <94376113+phanikumv@users.noreply.github.com>

Publish `1.3.0b1`

---

CONTRIBUTING.rst

This PR will update the contribution guide with more information about writing good integration tests. Since we are running example DAG as integration tests so the guide is in the example DAG section. 
Please let me know if you want to create a new section for integration tests guideline
Closes: #183

Update `CONTRIBUTING.rst` for integration test

---

astronomer/providers/amazon/aws/example_dags/example_redshift_cluster_management.py

CI pipelines have failed on main branch here: https://github.com/astronomer/astronomer-providers/commit/274ba19e07345512bb3f08abb1ff615b85cf7b16
We're pushing a dummy commit to ensure that main is stable.

Push dummy commit to test CI

---

astronomer/providers/amazon/aws/sensors/s3.py

closes https://github.com/astronomer/astronomer-providers/issues/362

Add `template_fields` to `S3KeySensorAsync`

---

astronomer/providers/google/cloud/hooks/bigquery.py
astronomer/providers/google/cloud/triggers/bigquery.py
tests/google/cloud/triggers/test_bigquery.py

Remove serialize vs non serialize branching logic in BigQueryGetOperatorAsync
Closes: #270

Remove nocast branching from bigquery hook get_records method

---

CHANGELOG.rst
docs/conf.py
setup.cfg

Update setup.cfg, docs/conf.py and CHANGELOG.rst with the changes pertaining to release 1.4.0

Release 1.4.0

---

.circleci/integration-tests/Dockerfile
dev/Dockerfile
dev/Dockerfile.emr_eks_container

non-base image require requirements.txt, packages.txt

Fix base image

---

.circleci/integration-tests/master_dag.py
astronomer/providers/amazon/aws/example_dags/example_batch.py
astronomer/providers/amazon/aws/hooks/batch_client.py
astronomer/providers/amazon/aws/operators/batch.py
astronomer/providers/amazon/aws/triggers/batch.py
tests/amazon/aws/hooks/test_batch_client.py
tests/amazon/aws/operators/test_batch.py
tests/amazon/aws/triggers/test_batch.py

This PR will add a deferrable AWS Batch Operator.
Closes #358

Implement  `BatchOperatorAsync`

---

astronomer/providers/google/cloud/example_dags/example_kubernetes_engine.py

- Updated location because for GKE `us` is not a valid location

Fix location for GKE Integration Test

---

docs/conf.py
setup.cfg

Since 1.5.0 is released, we should bump this version

Bump version to 1.6.0.dev1

---

astronomer/providers/google/cloud/example_dags/example_dataproc.py
astronomer/providers/google/cloud/hooks/dataproc.py
astronomer/providers/google/cloud/hooks/dataproc_async.py
astronomer/providers/google/cloud/operators/dataproc.py
astronomer/providers/google/cloud/triggers/dataproc.py
setup.cfg
tests/google/cloud/hooks/test_dataproc_async.py
tests/google/cloud/operators/test_dataproc.py
tests/google/cloud/triggers/test_dataproc.py

Issue: https://github.com/astronomer/astronomer-providers/issues/424
Add Support for DataprocCreateClusterOperatorAsync.
- Add hook/operator/trigger
- Unit Test
- Example DAG for integration test

Add ``DataprocCreateClusterOperatorAsync``

---

astronomer/providers/google/cloud/example_dags/example_dataproc.py
astronomer/providers/google/cloud/hooks/dataproc_async.py
astronomer/providers/google/cloud/operators/dataproc.py
astronomer/providers/google/cloud/triggers/dataproc.py
tests/google/cloud/operators/test_dataproc.py
tests/google/cloud/triggers/test_dataproc.py

Issue: https://github.com/astronomer/astronomer-providers/issues/424
- Add Example DAG
- Add hook/trigger/operator
- Add Unit Test

Add DataprocDeleteClusterOperatorAsync

---

.circleci/integration-tests/Dockerfile
dev/Dockerfile
dev/Dockerfile.aws
dev/Dockerfile.emr_eks_container

Upgrade the integration tests and dev docker files to use `astro-runtime:5.0.4-base` and `quay.io/astronomer/ap-airflow:2.3.2`

Update astro cloud image

---

CHANGELOG.rst
docs/conf.py
setup.cfg

Update `setup.cfg`, `docs/conf.py` and `CHANGELOG.rst` with the changes pertaining to release 1.6.0

Release 1.6.0

---

docs/conf.py
setup.cfg

Since 1.6.0 is released, we should bump this version

Bump version to 1.7.0.dev1

---

astronomer/providers/amazon/aws/example_dags/example_batch.py
astronomer/providers/amazon/aws/hooks/batch_client.py
astronomer/providers/amazon/aws/sensors/batch.py
astronomer/providers/amazon/aws/triggers/batch.py
tests/amazon/aws/sensors/test_batch_sensors.py
tests/amazon/aws/triggers/test_batch.py

The commit adds the following:
- Implementation for  triggers and sensors for BatchSensorAsync \
- A self-sufficient example DAG to create a  compute environment, create a job queue, submit the job ,run
the sensors, delete the job queue and delete the compute environment in the
same order. The DAG needs an AWS Account and an Airflow connection to be created
for the corresponding AWS Account.
- Handle exceptions
- Add relevant docstrings for the implementation
closes #415

Implement BatchSensorAsync

---

astronomer/providers/google/cloud/example_dags/example_dataproc.py

- Fix dependency between Hadoop task and create_bucket task i.e Hadoop task will depend on create_bucket
- Add an end task that will report the correct status of DAG run

Fix Hadoop and Create Bucket Task Dependency 

---

astronomer/providers/core/example_dags/example_file_sensor.py

Since the file was already present before triggering `file_sensor_task` so it was not waiting and defering this PR make sure that the current will example defer  
- Add start and end task
- add bash task to wait for 10 sec and create a file
- add a task to delete the created file
- Deleted that hardcoded file example_file_async_sensor.txt

Update FileSensorAsync Example to Defer

---

.circleci/integration-tests/Dockerfile.astro_cloud
dev/Dockerfile
dev/Dockerfile.aws
dev/Dockerfile.emr_eks_container
dev/Dockerfile.google_cloud

Upgrade astro runtime image as 5.0.5 has been released

Upgrade astro runtime image to 5.0.5

---

astronomer/providers/google/cloud/example_dags/example_bigquery_queries.py

It is observed that the `delete_dataset` task is called even before
the dependent tasks finish processing which depend on the dataset
to be queried upon. The commit fixes this issue by adding appropriate
dependecny in the DAG chain.
Also, since the `delete_dataset` task is called with the `trigger_rule`
`all_done`, we're adding an end task to report the DAG status correctly,
i.e. fail the DAG if any of the tasks fail.
closes: #495

Fix example_async_bigquery_queries dependency

---

astronomer/providers/core/example_dags/example_file_sensor.py

Reverts astronomer/astronomer-providers#489
closes: https://github.com/astronomer/astronomer-providers/issues/499

Revert "Update FileSensorAsync Example to Defer"

---

tests/amazon/aws/operators/test_batch.py

The context object needs task instance in the base operator. Hence, create a context
with needed properties and use it to make the test pass successfully.

Create context object to fix failing test

---

CHANGELOG.rst
docs/conf.py
setup.cfg

Update `setup.cfg`, `docs/conf.py` and `CHANGELOG.rst` with the changes pertaining to release 1.7.0

Release 1.7.0

---

docs/conf.py
setup.cfg

Since 1.7.0 is released, we should bump this version

Bump to 1.8.0.dev1

---

setup.cfg

Bump markupsafe version

---

CHANGELOG.rst
docs/conf.py
setup.cfg

Update `setup.cfg`, `docs/conf.py` and `CHANGELOG.rst` with the changes pertaining to release 1.7.1

Release 1.7.1

---

docs/conf.py
setup.cfg

Since 1.7.1 is released, we should bump up this version

Bump version to 1.8.0.dev1

---

dev/docker-compose.yaml

Fix extractor import path in docker-composer.yaml

Fix Extractor Import Path

---

.pre-commit-config.yaml

This commit update all the pre-commit hooks

Update to new pre-commit hooks

---

astronomer/providers/microsoft/azure/hooks/data_factory.py
tests/microsoft/azure/hooks/test_data_factory.py

AzureDataFactoryPipelineRunStatusSensorAsync failed if 'resource_group_name' or 'factory_name' are not passed in default_args or as param in the operator/sensor. So to fix that added decorator function to get the 'resource_group_name' or 'factory_name' from the default connection args if not passed as function args or in default_args
Covered the test case and code coverage
closes: #572

Get default 'resource_group_name' and 'factory_name' for AzureDataFactoryPipelineRunStatusSensorAsync

---

CHANGELOG.rst
docs/conf.py
setup.cfg

Update `setup.cfg`, `docs/conf.py` and `CHANGELOG.rst` with the changes pertaining to release 1.8.0

Release 1.8.0

---

CHANGELOG.rst
docs/conf.py
setup.cfg

Reverts astronomer/astronomer-providers#588

Revert changes specific to "Release 1.8.0"

---

docs/conf.py
setup.cfg

Since 1.8.0 is released, we should bump up this version

Bump version to 1.9.0.dev1

---

CONTRIBUTING.rst
Makefile

This will allow jumping into a shell to run tests and other commands from that (similar to breeze)

Add a make target to run interactive shell

---

astronomer/providers/databricks/operators/databricks.py
astronomer/providers/google/cloud/operators/bigquery.py
astronomer/providers/snowflake/operators/snowflake.py

Fix Mypy issues

---

CHANGELOG.rst
docs/conf.py
setup.cfg

Update `setup.cfg`, `docs/conf.py` and `CHANGELOG.rst` with the changes pertaining to release 1.8.1

Release 1.8.1

---

dev/docker-compose.yaml

Extractor path should be `astronomer.providers.amazon.aws.extractors.redshift.RedshiftAsyncExtractor` instead of  `astronomer.providers.amazon.aws.extractors.redshift .RedshiftAsyncDataExtractor`

Fix redshift extractor path

---

README.rst
astronomer/providers/dbt/cloud/example_dags/example_dbt_cloud.py
astronomer/providers/dbt/cloud/hooks/dbt.py
astronomer/providers/dbt/cloud/operators/dbt.py
astronomer/providers/dbt/cloud/sensors/dbt.py
astronomer/providers/dbt/cloud/triggers/dbt.py
astronomer/providers/http/hooks/http.py
dev/docker-compose.yaml
docs/providers/dbt/cloud/operators/dbt.rst
docs/providers/dbt/cloud/sensors/dbt.rst
docs/providers/dbt/index.rst
docs/providers/index.rst
setup.cfg
tests/dbt/cloud/hooks/test_dbt_hooks.py
tests/dbt/cloud/operators/test_dbt.py
tests/dbt/cloud/sensors/test_dbt.py
tests/dbt/cloud/triggers/test_dbt.py

Implemented Dbt Cloud Run Job Operator Async `DbtCloudJobRunOperatorAsync` and run job Sensor `DbtCloudJobRunSensorAsync` .
Refer https://astronomer.slack.com/archives/C0387PMM2E7/p1659702674640089
closes: #575

 Implement `DbtCloudJobRunOperatorAsync` and `DbtCloudJobRunSensorAsync`

---

astronomer/providers/package.py

Add hyperlink for description

---

CHANGELOG.rst
docs/conf.py
setup.cfg

Update `setup.cfg`, `docs/conf.py` and `CHANGELOG.rst` with the changes pertaining to release 1.9.0

Release 1.9.0

---

docs/conf.py
setup.cfg

Since 1.9.0 is released, we should bump up this version

Bump version to 1.10.0.dev1

---

tests/cncf/kubernetes/hooks/test_kubernetes.py
tests/cncf/kubernetes/operators/test_kubernetes_pod.py
tests/cncf/kubernetes/triggers/test_wait_container.py
tests/utils/airflow_util.py

Clean CNCF Unit Tests

---

docs/providers/index.rst

This PR fixes some link that were broken in our documentation

Fix broken docs link

---

.circleci/integration-tests/Dockerfile.astro_cloud
Makefile

- Made changes to make file and docker file to use latest astro runtime 6.0.1 image

Use astro runtime 6.0.1 image

---

astronomer/providers/package.py
docs/conf.py
setup.cfg

Since 1.10.0 is released, we should bump up this version

Bump version to 1.11.0.dev1

---

.circleci/integration-tests/Dockerfile.astro_cloud
Makefile

The image was released a couple of days ago with some bug fixes

Bump astro-runtime to 6.0.2

---

astronomer/providers/google/cloud/hooks/dataproc.py
astronomer/providers/google/cloud/operators/bigquery.py
astronomer/providers/google/cloud/operators/dataproc.py
tests/google/cloud/hooks/test_dataproc.py

Fix mypy and Unit test failure due to new Google Provider release

---

.circleci/integration-tests/master_dag.py
astronomer/providers/amazon/aws/example_dags/example_sagemaker.py
astronomer/providers/amazon/aws/hooks/sagemaker.py
astronomer/providers/amazon/aws/operators/sagemaker.py
astronomer/providers/amazon/aws/triggers/sagemaker.py
docs/providers/amazon/aws/operators/sagemaker.rst
docs/providers/amazon/index.rst
tests/amazon/aws/hooks/test_sagemaker.py
tests/amazon/aws/operators/test_sagemaker.py
tests/amazon/aws/triggers/test_sagemaker.py

- Implemented `SageMakerProcessingOperatorAsync` 
- Added async hook, trigger 
- Added test case for  `SageMakerProcessingOperatorAsync` 
- Added Documentation for the Operators
- Added example dag for the operator
The task is associated with #669. We can close the task when this PR and https://github.com/astronomer/astronomer-providers/pull/710 is merged into the main.

Implement `SageMakerProcessingOperatorAsync`

---

astronomer/providers/amazon/aws/example_dags/example_sagemaker.py

Fixed SageMaker example DAG to create the model in transform operator itself.
While using the sync version of `SageMakerModelOperator` to create a model there was a serialize error this serialize error got fixed in [provider-amazon-6.0.0](https://pypi.org/project/apache-airflow-providers-amazon/6.0.0/) in Astro runtime base image(6.0.2) the latest version is not present, so the example end-to-end was failing in the creation model step(we are using OSS operator to create a model) which is after processing and training. 
To fix this, there is an option in the transform operator if the model config was passed the transform operator by itself creates the model and executes the transform job.

Fix sagemaker example DAG

---

CHANGELOG.rst
astronomer/providers/package.py
docs/conf.py
setup.cfg

- Create change log and changes the package version

Release 1.11.0

---

astronomer/providers/package.py
docs/conf.py
setup.cfg

Since 1.11.0 is released, we should bump up this version

Bump version to 1.12.0.dev1

---

astronomer/providers/databricks/operators/databricks.py

Addressed the review comments given in this PR https://github.com/astronomer/astronomer-providers/pull/718

Fix databricks doc

---

astronomer/providers/amazon/aws/example_dags/example_sagemaker.py
astronomer/providers/amazon/aws/operators/sagemaker.py
tests/amazon/aws/operators/test_sagemaker.py

Fixed the response key for SageMaker Training and Transform Operator
closes: #736

Fix response key's for SageMaker Training and Transform operator

---

CHANGELOG.rst
astronomer/providers/package.py
docs/conf.py
setup.cfg

Update setup.cfg, docs/conf.py and CHANGELOG.rst with the changes pertaining to release 1.11.1

Release 1.11.1

---

astronomer/providers/snowflake/operators/snowflake.py

Added missing attribute in SnowflakeAPIAsyncOperator

Add attribute to SnowflakeAPIAsyncOperator

---

CHANGELOG.rst
astronomer/providers/package.py
astronomer/providers/snowflake/operators/snowflake.py
docs/conf.py
setup.cfg

Update setup.cfg, docs/conf.py and CHANGELOG.rst with the changes pertaining to release 1.11.2

Release 1.11.2

---

CHANGELOG.rst
astronomer/providers/package.py
docs/conf.py
setup.cfg

This reverts commit 225f89289dad1048d50082354ef59e894b84895a.

Revert "Release 1.11.2 (#765)"

---

astronomer/providers/microsoft/azure/hooks/wasb.py
astronomer/providers/microsoft/azure/triggers/wasb.py
tests/microsoft/azure/hooks/test_wasb.py
tests/microsoft/azure/triggers/test_wasb.py

Remove mypy ignore specification in `WasbHookAsync`

---

CHANGELOG.rst
astronomer/providers/package.py
docs/conf.py
setup.cfg

Update setup.cfg, docs/conf.py and CHANGELOG.rst with the changes pertaining to release 1.12.0

Release 1.12.0

---

astronomer/providers/package.py
docs/conf.py
setup.cfg

Since 1.12.0 is released, so bumped up this version to 1.13.0.dev1

Bump version to 1.13.0.dev1

---

.circleci/integration-tests/Dockerfile.astro_cloud
Makefile

The new release 7.0.0 for Astro runtime was released. Upgrade to the same.

Bump astro-runtime to 7.0.0

---

CHANGELOG.rst
astronomer/providers/package.py
docs/conf.py
setup.cfg

Update setup.cfg, docs/conf.py and CHANGELOG.rst with the changes pertaining to release 1.13.0

Release 1.13.0

---

astronomer/providers/package.py
docs/conf.py
setup.cfg

Since 1.13.0 is released, so bumped up the version to 1.14.0.dev1

Bump version to 1.14.0.dev1

---

.circleci/integration-tests/Dockerfile.astro_cloud
Makefile

Bump runtime image to 7.1.0

---

CHANGELOG.rst
astronomer/providers/package.py
docs/conf.py
setup.cfg

Update setup.cfg, docs/conf.py and CHANGELOG.rst with the changes pertaining to release 1.14.0

Release 1.14.0

---

astronomer/providers/package.py
docs/conf.py
setup.cfg

Since 1.14.0 is released, so bumped up the version to 1.15.0.dev1

Bump version to 1.15.0.dev1

---

tests/apache/hive/hooks/test_hive.py
tests/apache/hive/sensors/test_hive_partition.py
tests/apache/hive/sensors/test_named_hive_partition.py
tests/apache/hive/triggers/test_hive_partition.py
tests/apache/hive/triggers/test_named_hive_partition.py
tests/apache/livy/hooks/test_livy.py
tests/apache/livy/operators/test_livy.py
tests/apache/livy/triggers/test_livy.py

closes: https://github.com/astronomer/astronomer-providers/issues/692
- Convert function-based tests to class-based
- Use pytest instead of unittest

Apache class based tests

---

astronomer/providers/snowflake/hooks/snowflake_sql_api.py

https://app.circleci.com/pipelines/github/astronomer/astronomer-providers/3781/workflows/dc520838-4c75-4b72-8a13-1d18e5cfe20d/jobs/16376

Fix mypy issue

---

.circleci/integration-tests/Dockerfile.astro_cloud
Makefile

update runtime image.
Look like yesterday while testing rc I upgraded the version
Bump runtime image to 7.2.0

Bump runtime image to 7.2.0

---

tests/http/hooks/test_http.py
tests/http/sensors/test_http.py
tests/http/triggers/test_http.py

closes: https://github.com/astronomer/astronomer-providers/issues/695
change the HTTP test from a function based to class-based.

Add http class based tests

---

.circleci/config.yml

closes: https://github.com/astronomer/astronomer-providers/issues/753

Generate constraint

---

CHANGELOG.rst
astronomer/providers/package.py
docs/conf.py
setup.cfg

Update setup.cfg, docs/conf.py and CHANGELOG.rst with the changes pertaining to release 1.15.0

Release 1.15.0

---

.circleci/integration-tests/Dockerfile.astro_cloud
Makefile

Bump astro-runtime 7.3.0 version

Bump astro-runtime 7.3.0 version

---

setup.cfg

closes: https://github.com/astronomer/astronomer-providers/issues/868

unpin mypy

---

astronomer/providers/http/sensors/http.py
tests/http/triggers/test_http.py

closes: https://github.com/astronomer/astronomer-providers/issues/895

Pass connection_id in http trigger

---

CHANGELOG.rst
astronomer/providers/package.py
docs/conf.py
setup.cfg

Update setup.cfg, docs/conf.py and CHANGELOG.rst with the changes pertaining to release 1.15.1

Release 1.15.1

---

astronomer/providers/package.py
docs/conf.py
setup.cfg

Since 1.15.1 is released, so bumped up the version to 1.16.0-dev

Bump version to 1.16.0-dev

---

.circleci/integration-tests/master_dag.py

DBT example dag was not being triggered as part of master dag.

Run dbt example dag as part of  master dag

---

.circleci/integration-tests/Dockerfile.astro_cloud
Makefile

Bump astro-runtime version 7.4.0

Bump astro-runtime version 7-4-0

---

.circleci/integration-tests/Dockerfile.astro_cloud
Makefile

Bump astro runtime to 7.4.1

---

.circleci/config.yml

We should generate constraints file for latest airflow minor version

Generate constraints for airflow-2-5-2

---

astronomer/providers/package.py
docs/conf.py
setup.cfg

Since 1.15.2 is released, so bumped up the version to 1.16.0-dev

Bump version to 1.16.0.dev1

---

astronomer/providers/core/triggers/external_task.py

Removed task_id as a parameter since it doesn't have that parameter.  Updated desc to match

Removed task_id and updated description for DagStateTrigger

---

.circleci/config.yml
.circleci/integration-tests/Dockerfile.astro_cloud
Makefile

airflow-version: 2.5.2 -> 2.5.3
runtime: 7.4.1 -> 7.4.2

Bump runtime and airflow version

---

astronomer/providers/amazon/aws/operators/redshift_cluster.py
astronomer/providers/google/cloud/sensors/bigquery.py
astronomer/providers/google/cloud/sensors/gcs.py

Fix mypy failures observed and tested in PR #940

Fix mypy failures observed and tested in PR #940

---

CODEOWNERS

Add Ankit/Utkarsh as code owner

Add Ankit/Utkarsh as code owner

---

CHANGELOG.rst
astronomer/providers/package.py
docs/conf.py
setup.cfg

Update setup.cfg, docs/conf.py, CHANGELOG.rst and astronomer/providers/package.py with the changes pertaining to release 1.15.4

Release 1.15.4

---

RELEASING.rst
astronomer/providers/package.py
pyproject.toml

We also need to update version in ``astronomer/providers/package.py`` so lets document that
add `commitizen` in pyproject.toml for bumping version

Update release docs updating version section

---

astronomer/providers/package.py
docs/conf.py
pyproject.toml
setup.cfg

Bump dev version to 1.16.0dev

---

astronomer/providers/sftp/hooks/sftp.py
tests/sftp/hooks/test_sftp.py

Since, the AsyncSSH client does not support host keys other than the ones in known_hosts file, we create and use a paramiko client to verify the provided host key. If no host key is given, we issue a warning in the log that it is susceptible to man in the middle attacks.
closes: #906

Support host key verification for SFTPSensorAsync

---

.github/workflows/deploy-integration-tests.yaml

ci(github-actions): add workflow to deploy integration tests to astro cloud

---

astronomer/providers/snowflake/hooks/snowflake.py
astronomer/providers/snowflake/operators/snowflake.py
tests/snowflake/operators/test_snowflake.py

SnowflakeOperatorAsync: check whether all queries finish before deferring the task

---

astronomer/providers/snowflake/example_dags/example_snowflake.py

test(snowflake): extend snowflake example dag to run multiple quries in one run

---

.circleci/integration-tests/master_dag.py

test(integration-tests): make master dag schedule configurable from env var

---

astronomer/providers/package.py
docs/conf.py
pyproject.toml
setup.cfg

Bump dev version to 1.16.0-dev1

Bump dev version to 1.16.0-dev1

---

tests/core/sensors/test_external_task.py
tests/http/sensors/test_http.py

Fix transient failure for tests. Mocking external call. this is happening look like after sensor optimization.

Mock external http call

---

.circleci/config.yml
.github/workflows/deploy-integration-tests.yaml
.github/workflows/deploy-to-astro-cloud-reuse-wf.yaml

* ci(circleci): remove deploy job from circle CI
* ci(github-actions): schedule integration-tests deployment on 19:00 daily
Closes: #1011

Schedule integration tests deployment through GitHub actions

---

astronomer/providers/google/cloud/operators/bigquery.py
tests/google/cloud/operators/test_bigquery.py

Check whether the job finishes before deferring the task for BigQueryValueCheckOperatorAsync

---

astronomer/providers/google/cloud/operators/bigquery.py
tests/google/cloud/operators/test_bigquery.py

Check whether the job finishes before deferring the task for BigQueryIntervalCheckOperatorAsync

---

astronomer/providers/apache/hive/example_dags/example_hive.py

Mark Hive DAG failed if any of the tasks fail

---

astronomer/providers/sftp/example_dags/example_sftp.py

Mark SFTP DAG failed if any of the tasks fail

---

astronomer/providers/amazon/aws/example_dags/example_s3.py

Mark S3 Sensor DAG failed if any of the tasks fail

---

astronomer/providers/amazon/aws/example_dags/example_sagemaker.py

Mark SageMaker DAG failed if any of the tasks fail

---

astronomer/providers/dbt/cloud/operators/dbt.py
tests/dbt/cloud/operators/test_dbt.py

Like the [SnowflakeOperatorAsync](https://github.com/astronomer/astronomer-providers/blob/b2dade827ad8425952b2f5313b6a2863cb0c3e5e/astronomer/providers/snowflake/operators/snowflake.py#L217), we need to verify if the task has already completed before deferring it to prevent unnecessary deferring. This way, we can skip deferring the task if it has already been finished.

Check whether the task finishes before deferring the task for DbtCloudRunJobOperatorAsync

---

astronomer/providers/google/cloud/example_dags/example_bigquery_impersonation_chain.py

Mark BigQuery impersonation DAG failed if any of the tasks fail

---

astronomer/providers/google/cloud/operators/dataproc.py
tests/google/cloud/operators/test_dataproc.py

Check whether the task finishes before deferring the task for DataprocCreateClusterOperatorAsync

---

astronomer/providers/google/cloud/operators/bigquery.py
tests/google/cloud/operators/test_bigquery.py

Check whether the task finishes before deferring the task for BigQueryGetDataOperatorAsync

---

astronomer/providers/google/cloud/operators/dataproc.py
tests/google/cloud/operators/test_dataproc.py

Check whether the task finishes before deferring the task for DataprocUpdateClusterOperatorAsync

---

.circleci/integration-tests/Dockerfile.astro_cloud
Makefile

Test corresponding runtime image for Airflow 2.6.1rc2

Upgrade astro runtime image to dev 8.2.0-alpha3-base

---

.circleci/integration-tests/Dockerfile.astro_cloud
Makefile

Test corresponding runtime image for Airflow 2.6.1rc3

Upgrade astro runtime image to 8.2.0-alpha4-base

---

astronomer/providers/amazon/aws/example_dags/example_batch.py

Mark AWS Batch DAG failed if any of the tasks fail

---

astronomer/providers/amazon/aws/operators/emr.py
tests/amazon/aws/operators/test_emr.py

Check whether the task finishes before deferring the task for EmrContainerOperatorAsync

---

astronomer/providers/amazon/aws/operators/sagemaker.py
tests/amazon/aws/operators/test_sagemaker.py

Check whether the task finishes before deferring the task for SageMakerProcessingOperatorAsync

---

CHANGELOG.rst
astronomer/providers/package.py
docs/conf.py
pyproject.toml
setup.cfg

Update `setup.cfg`, `docs/conf.py, CHANGELOG.rst` and `astronomer/providers/package.py` with the changes pertaining to release 1.16.0

Release 1.16.0

---

astronomer/providers/apache/hive/sensors/hive_partition.py
tests/apache/hive/sensors/test_hive_partition.py

Similar to [SnowflakeOperatorAsync](https://github.com/astronomer/astronomer-providers/blob/b2dade827ad8425952b2f5313b6a2863cb0c3e5e/astronomer/providers/snowflake/operators/snowflake.py#L217), we want to check whether the task has finished before it's deferred. For most sensors, we have a poke method in its sync counter part which can help us do such check.

feat(hive): check state before deferring HivePartitionSensorAsync

---

astronomer/providers/amazon/aws/operators/sagemaker.py
tests/amazon/aws/operators/test_sagemaker.py

Check whether the task finishes before deferring the task for SageMakerTransformOperatorAsync

---

.circleci/integration-tests/master_dag.py
.github/workflows/deploy-integration-tests.yaml

remove master dag schedule and trigger the master dag from github actions workflow

---

astronomer/providers/amazon/aws/hooks/base_aws.py
astronomer/providers/core/triggers/external_task.py
astronomer/providers/databricks/operators/databricks.py
astronomer/providers/snowflake/triggers/snowflake_trigger.py

Follow-up PR for fixing mypy failures on https://github.com/astronomer/astronomer-providers/pull/1142

Fix mypy warnings post runtime image upgrade to 8.3.0

---

astronomer/providers/amazon/aws/sensors/emr.py
tests/amazon/aws/sensors/test_emr_sensors.py

Check whether the task finishes before deferring the task for EmrJobFlowSensorAsync

---

astronomer/providers/amazon/aws/hooks/base_aws.py
astronomer/providers/snowflake/triggers/snowflake_trigger.py

https://github.com/apache/airflow/issues/31495

fix mypy warnings for  apache/airflow#31495 release

---

.circleci/integration-tests/master_dag.py

Currently, we do not include the nuke DAG in the Slack alert. This does not give us a quick view of the nuke DAG status in our daily run reports. The commit adds the status of the nuke DAG as well in our daily run reports.

Include nuke dag in the Slack report

---

.github/workflows/runtime-image-update.yaml

The PR address review comments on PR #1159 wrt 
below points:
1. Remove usage of deprecated way to write step outputs.
2. Add a condition to check tags are updated for running the 
step to create a PR.

Address @Lee-W's comments on PR #1159

---

astronomer/providers/amazon/aws/hooks/sagemaker.py
astronomer/providers/amazon/aws/operators/sagemaker.py
astronomer/providers/amazon/aws/triggers/sagemaker.py
setup.cfg
tests/amazon/aws/hooks/test_sagemaker.py
tests/amazon/aws/operators/test_sagemaker.py
tests/amazon/aws/triggers/test_sagemaker.py

This reverts commit c7fe1971013ede4ffc54af0ec7d14eff06576c42.
We will need a major release of providers as per the discussion with the team.

Revert "Extend upstream Amazon provider SageMaker operators; set deferrable to True (#1169)"

---

.circleci/integration-tests/master_dag.py

Currently, we chain the EMR DAGs, and the EMR EKS PI Job takes 
between 30 to 40 mins and the EMR Sensor DAGs takes about 
8-10 mins. As a result, due to these long-running DAGs, the 
Master DAG takes 38 to 50 mins. The EMR EKS DAG takes the 
longest duration across all the DAGs in Master DAG. With 
parallelising this chain, we're expecting the Master DAG will run 
for a duration at most the same as the EMR EKS PI job and then it 
does not have to wait for additional 8-10 mins for the EMR sensor 
DAG to finish as it would be run parallelly and would have 
completed by then.
The commit also removes additional free lines in the Slack report as it looks unnecessary.

Run EMR DAGs in parallel to reduce Master DAG run duration

---

.github/workflows/test-rc-release.yaml
astronomer/providers/amazon/aws/example_dags/example_sagemaker.py

This is the root cause of the failure https://github.com/astronomer/astronomer-providers/actions/runs/5328666545/jobs/9653537662

ci(github-actions): fix wrong variable used in test-rc workflow

---

CHANGELOG.rst
astronomer/providers/package.py
docs/conf.py
pyproject.toml
setup.cfg

Update setup.cfg, pyproject.toml, docs/conf.py, CHANGELOG.rst 
and astronomer/providers/package.py with the changes pertaining 
to release 1.17.1

Release 1.17.1

---

astronomer/providers/amazon/aws/operators/batch.py
astronomer/providers/amazon/aws/operators/redshift_cluster.py
astronomer/providers/amazon/aws/sensors/emr.py

We observed mypy failures while testing the June wave of providers
in our RC testing PR https://github.com/astronomer/astronomer-providers/pull/1194.
We try to fix those issues here and will be applied once the providers are released

Fix mypy errors observed in June Providers wave

---

pyproject.toml

Adds checks for https://beta.ruff.rs/docs/rules/#flake8-async-async

Add Ruff rules for Async

---

.github/workflows/test-rc-release.yaml

the original logic cannot correctly load bash variables

ci(github-actions): fix rc testing branch existence check

---

setup.cfg

The issue has been fixed in Airflow

Remove Pydantic restriction

---

.circleci/integration-tests/master_dag.py

Currently, in our Report, we have a lot of different version variables which can be displayed in a better way, below format has been suggested, this PR implements the same
More context: https://astronomer.slack.com/archives/C059006G6SG/p1689763710985949

Formatting Master DAG Report

---

.circleci/integration-tests/master_dag.py
astronomer/providers/amazon/aws/example_dags/example_aws_nuke.py
astronomer/providers/core/example_dags/example_external_task.py
astronomer/providers/dbt/cloud/example_dags/example_dbt_cloud.py
tests/core/triggers/test_external_task.py

Replace DummyOperator with emptyOperator since DummyOperator

Replace DummyOperator with emptyOperator

---

CHANGELOG.rst
astronomer/providers/package.py
docs/conf.py
pyproject.toml
setup.cfg

This reverts commit 3666c5d97d849fb23eef5b00b6ee1030092ce5b0.

Revert "Release 1.17.2 (#1257)"

---

.github/workflows/stale.yaml

Add workflow to mark PR/Issue stale and close them.
TODO

Add workflow to mark issue/pr stale

---

astronomer/providers/http/sensors/http.py

closes: https://github.com/astronomer/astronomer-providers/issues/1277

Fix incorrect warrning in HttpSensor

---

.circleci/config.yml
README.rst

job: https://app.circleci.com/pipelines/github/astronomer/astronomer-providers/6270/workflows/9e4ee250-9b09-4512-a7a7-bb911e3b2cf9

Fix Python3.11 constraints

---

astronomer/providers/core/sensors/external_task.py
tests/cncf/kubernetes/operators/test_kubernetes_pod.py
tests/google/cloud/operators/test_kubernetes_engine.py

* fix mypy warning
* remove redundant mocking which cause test failed
https://github.com/astronomer/astronomer-providers/pull/1293

Fix style, test changes due to https://github.com/apache/airflow/issues/33257

---

astronomer/providers/snowflake/operators/snowflake.py

blocked by https://github.com/apache/airflow/issues/35845

style(snowflake): fix mypy error

---

CHANGELOG.rst
astronomer/providers/package.py
docs/conf.py
pyproject.toml
setup.cfg

Release 1.18.3

---

astronomer/providers/amazon/aws/operators/emr.py
astronomer/providers/amazon/aws/operators/redshift_cluster.py

address https://github.com/astronomer/astronomer-providers/pull/1402/files/d6f074c32db15394696360919f47216ba026b392#r1457142029

refactor(amazon/emr): remove unnecessary return in EmrContainerOperatorAsync and Redshift Cluster operators

---

setup.cfg

update the minimum version as the latest rc has been released

build(setup.cfg): update amazon provider min version to 8.18.0

---

.circleci/config.yml
setup.cfg

Enable test for 2.9 airflow and Python 3.12

Run python3.12 tests

---

.circleci/integration-tests/Dockerfile.astro_cloud
astronomer/providers/amazon/aws/example_dags/example_s3.py
astronomer/providers/snowflake/hooks/snowflake_sql_api.py
dev/Dockerfile
tests/snowflake/hooks/test_snowflake_sql_api.py

This should be merged after provider release but is ready to be reviewed now

Fix failure due to latest wave rc provider release

---

CHANGELOG.rst
astronomer/providers/package.py
docs/conf.py
pyproject.toml
setup.cfg

Release 1.19.1

---

astronomer/providers/databricks/example_dags/example_databricks.py

"In accordance with [Issue #672](https://github.com/astronomer/issues-airflow/issues/672), we need to migrate our Databricks account to Azure. Consequently, we should update this DAG with Azure cluster configuration.

Update cluster configuration to Azure

---

CHANGELOG.rst
astronomer/providers/package.py
docs/conf.py
pyproject.toml
setup.cfg

closes: https://github.com/astronomer/issues-airflow/issues/854

Release 1.19.2

---

CHANGELOG.rst
astronomer/providers/package.py
docs/conf.py
pyproject.toml
setup.cfg

Release 1.19.3

---

CHANGELOG.rst
astronomer/providers/package.py
docs/conf.py
pyproject.toml
setup.cfg

Release 1.19.4

---

.circleci/integration-tests/Dockerfile.astro_cloud
.circleci/integration-tests/master_dag.py
.circleci/integration-tests/script.sh
.github/scripts/refactor_dag.py
.github/workflows/reuse-wf-deploy-to-astro-cloud.yaml
dev/Dockerfile

We want to add the Databricks workflow system to our integration tests so that we can be notified in case of any failure during RC testing. This PR copies the Databricks [workflow system test](https://github.com/apache/airflow/blob/main/tests/system/providers/databricks/example_databricks_workflow.py) from the Airflow repo and integrates it with our integration tests.
closes: https://github.com/astronomer/astronomer-providers/issues/1561

Add databricks workflow system to integration tests
