.codecov.yml
This PR adds some toleration for Code Coverage.
It won't always be the case that we can achieve the coverage we need. 2% is  an arbitrary number currently, we can increase or decrease in future.
=> Allow CodeCoverage toleration

astronomer/providers/amazon/aws/example_dags/example_redshift_sql.py, astronomer/providers/amazon/aws/example_dags/example_s3.py, astronomer/providers/amazon/aws/hooks/s3.py, astronomer/providers/amazon/aws/operators/redshift_sql.py, astronomer/providers/amazon/aws/sensors/redshift_cluster.py, astronomer/providers/amazon/aws/sensors/s3.py, astronomer/providers/amazon/aws/triggers/s3.py, astronomer/providers/core/sensors/external_task.py, astronomer/providers/core/sensors/filesystem.py, astronomer/providers/databricks/operators/databricks.py, astronomer/providers/google/cloud/example_dags/example_gcs.py, astronomer/providers/google/cloud/sensors/gcs.py, astronomer/providers/google/cloud/triggers/gcs.py, astronomer/providers/http/sensors/http.py, astronomer/providers/snowflake/operators/snowflake.py, pyproject.toml, tests/amazon/aws/hooks/test_s3_hooks.py, tests/google/cloud/sensors/test_gcs.py, tests/google/cloud/triggers/test_gcs.py
Issue: https://github.com/astronomer/astronomer-providers/issues/69
Implement the sensor GCSObjectsWithPrefixExistenceSensorAsync
Implement triggers for GCSObjectsWithPrefixExistenceSensorAsync
Add example DAG for GCSObjectsWithPrefixExistenceSensorAsync
Add test for GCSObjectsWithPrefixExistenceSensorAsync sensor, trigger and hooks
Implement the sensor GCSUploadSessionCompleteSensor
Implement triggers for GCSUploadSessionCompleteSensor
Add example DAG for GCSUploadSessionCompleteSensor
Add test for GCSUploadSessionCompleteSensor sensor, trigger and hooks
=> Implement GCSObjectsWithPrefixExistenceSensorAsync and GCSUploadSessionCompleteSensor

astronomer/providers/amazon/aws/example_dags/example_s3.py
- Create a `CommonPrefix` as `test` while uploading the file
```
<CommonPrefixes>
<Prefix>test/</Prefix>
</CommonPrefixes>
```
- Add `replace=True` in `LocalFilesystemToS3Operator`
-  [Reference](https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-prefixes.html)
Closes: #104
=> Fix example DAG to run standalone

.circleci/Dockerfile, .circleci/config.yml, .circleci/scripts/pre_commit_setup_cfg_all_extra.py, .pre-commit-config.yaml, astronomer/providers/cncf/kubernetes/operators/kubernetes_pod.py, astronomer/providers/google/cloud/triggers/gcs.py, dev/Dockerfile, pyproject.toml, setup.cfg
This will allow users to just install dependencies of a single provider. For example if a user wants to just use K8s async operator, they shouldn't need to install GCP, AWS, Databricks or Snowflake dependencies
closes https://github.com/astronomer/astronomer-providers/issues/101
=> Split the dependencies into multiple extras

.circleci/config.yml, astronomer/providers/google/cloud/example_dags/example_gcs.py
- Added Delay task for GCS Sensor to show the sensors is deferred and changed the upstream of the Task
- Changed the bucket name 
Issue id: https://github.com/astronomer/astronomer-providers/issues/116
=> Add Delay to GCS sensor

CHANGELOG.rst
We had old import paths : `astronomer_operators` -> `from astronomer.providers` for some of the operators
=> Fix file paths in `CHANGELOG.rst`

.circleci/scripts/pre_commit_sync_version_docs.py, .pre-commit-config.yaml, README.rst, setup.cfg
This PR:
- adds pre-commit to keep package version in setup.cfg and docs/conf.py in sync
- Adds ReadTheDocs Docs Build Badge
- Add docs link in project_urls
=> Add pre-commit to keep package version in sync

docs/conf.py
Example DAGs don't define any classes so it does not make sense to include them in the docs.
**Before**:
**After**:
=> Docs: Ignore Example DAGs from API reference

astronomer/providers/databricks/hooks/databricks.py, setup.cfg, tests/databricks/hooks/test_databricks.py
- [USER_AGENT_HEADER](https://github.com/astronomer/astronomer-providers/blob/1a27d231246e1c3c400ca7a3343d9372b6b51acf/astronomer/providers/databricks/hooks/databricks.py#L10) is imported from [airflow.providers.databricks.hooks.databricks](https://github.com/apache/airflow/blob/main/airflow/providers/databricks/hooks/databricks.py) as part of this [commit](https://github.com/apache/airflow/commit/27d19e7626ef80687997a6799762fa00162c1328). This is causing DatabricksSubmitRunOperatorAsync to throw an import error .This is for latest apache-airflow-providers-databricks==2.3.0
- Remove path import for USER_AGENT_HEADER and declare it
closes: #130
=> Remove path import for USER_AGENT_HEADER and declare it

astronomer/providers/google/cloud/example_dags/example_gcs.py
Some of the GCS operators/sensors accept only `google_cloud_conn_id` as connection param. 
because this https://github.com/astronomer/astronomer-providers/pull/102 merge example was failing.
=> Bug fix for gcs operator example

setup.cfg, tests/cncf/kubernetes/operators/test_kubernetes_pod.py
Tis PR remove the upper bound version constraints for `apache-airflow-providers-cncf-kubernetes`
=> Unpin Kubernetes Provider dependency

astronomer/providers/google/cloud/example_dags/example_bigquery_sensors.py, astronomer/providers/google/cloud/hooks/bigquery.py, astronomer/providers/google/cloud/sensors/bigquery.py, astronomer/providers/google/cloud/triggers/bigquery.py, tests/google/cloud/hooks/test_bigquery.py, tests/google/cloud/sensors/test_bigquery.py, tests/google/cloud/triggers/test_bigquery.py
story Id: https://github.com/astronomer/astronomer-providers/issues/68
- Implemented Async Big Query Table Existence Sensor (Operator, Trigger, Hook) --> @rajaths010494 
- Added Unit Test case, code coverage, Doc string For  Big Query Table Existence Sensor, code coverage --> @bharanidharan14
=> Implement Async Big Query Table Existence Sensor

astronomer/providers/databricks/hooks/databricks.py, astronomer/providers/databricks/operators/databricks.py, astronomer/providers/databricks/triggers/databricks.py, tests/databricks/hooks/test_databricks.py, tests/databricks/operators/test_databricks.py, tests/databricks/triggers/test_databricks.py
- Remove the colon in the auth header in the hooks. The issue was that the authentication header is malformed.
`Basic: <credential>`
There should not be a colon in the header.
`Basic <credential>`
- Propagate the error message from triggerer to work in case life_cycle_state: `TERMINATED`, `SKIPPED` or `INTERNAL_ERROR`.
- Update the tests
Closes: #143
=> Fix Databricks triggerer fails to check databricks job state

astronomer/providers/google/cloud/example_dags/example_bigquery_sensors.py
This PR fixes a bug on example_bigquery_sensors.py where schedule interval was set to string none rather than type None.
=> Bug fix on  example_bigquery_sensors.py dag

astronomer/providers/google/cloud/sensors/bigquery.py
This PR/commit fixes docstrings so they are rendered correctly in Sphinx.
**Before**:
**After**:
=> Fix docstrings for ``BigQueryTableExistenceSensorAsync``

CHANGELOG.rst, docs/conf.py, setup.cfg
This PR includes changes for the Astronomer Providers Release 1.1.0 and includes the below items:
- Databricks triggerer fails to check databricks job state
- Improved exception handling on the Async Databricks Operator
- Documentation changes for the release
Closes #148
=> Bump to Release 1.1.0

astronomer/providers/amazon/aws/example_dags/example_redshift_cluster_management.py, astronomer/providers/amazon/aws/example_dags/example_s3.py
- Increase execution timeout for redshift cluster mgmt from 60 sec to 15 min
- change the s3 connection name default value and env variable name since it was conflicting with the amazon web service connection
=> RedshiftClusterSensorAsync timeout fix and S3 conn name change 

astronomer/providers/cncf/kubernetes/operators/kubernetes_pod.py, astronomer/providers/http/sensors/http.py, setup.cfg
closes https://github.com/astronomer/astronomer-providers/issues/157
**With this change**:
=> Document limitations of some async operators

.circleci/integration-tests/master_dag.py, astronomer/providers/amazon/aws/example_dags/example_redshift_cluster_management.py, astronomer/providers/amazon/aws/example_dags/example_redshift_sql.py, astronomer/providers/amazon/aws/example_dags/example_s3.py, astronomer/providers/cncf/kubernetes/example_dags/example_kubernetes_pod_operator.py, astronomer/providers/core/example_dags/example_external_task.py, astronomer/providers/core/example_dags/example_external_task_wait_for_me.py, astronomer/providers/core/example_dags/example_file_sensor.py, astronomer/providers/google/cloud/example_dags/example_bigquery_queries.py, astronomer/providers/google/cloud/example_dags/example_bigquery_sensors.py, astronomer/providers/google/cloud/example_dags/example_dataproc.py, astronomer/providers/google/cloud/example_dags/example_gcs.py, astronomer/providers/http/example_dags/example_http.py, astronomer/providers/snowflake/example_dags/example_snowflake.py
Related issue: https://github.com/astronomer/astronomer-providers/issues/63
Cleanup example by adding execution_timeout in default_args in dags and removed from individual operator/sensor since now all the operator/sensor have execution_timeout
- Add execution_timeout for all examples DAG
- Included dataproc and bigquery_sensors in master DAG
=> Add timeout for all DAGs and dataproc and bigquery_sensors

astronomer/providers/databricks/example_dags/example_databricks.py, astronomer/providers/databricks/operators/databricks.py, astronomer/providers/databricks/triggers/databricks.py, tests/databricks/operators/test_databricks.py, tests/databricks/triggers/test_databricks.py
Issue: https://github.com/astronomer/astronomer-providers/issues/159
- storing databricks job_id in xcom of DatabricksSubmitRunOperatorAsync operator
- DatabricksSubmitRunOperatorAsync example will now create a new cluster so using `new_cluster` args of operator earlier it was using existing cluster
- DatabricksRunNowOperatorAsync example was earlier dependent on the environment variable for `job_id` now we are getting this from xcom.
=> Store databricks job_id in xcom for DatabricksSubmitRunOperatorAsync operator

astronomer/providers/databricks/operators/databricks.py, astronomer/providers/databricks/triggers/databricks.py, tests/databricks/operators/test_databricks.py, tests/databricks/triggers/test_databricks.py
Issue: https://github.com/astronomer/astronomer-providers/issues/167
- Pushing xcom values in in `execute_complete()` method for both DatabricksRunNowOperatorAsync and DatabricksSubmitRunOperatorAsync.
- Keeping the logic as it is in `execute` method so that value would be available also during execution
=> Persist Databricks xcom value

.circleci/integration-tests/master_dag.py, astronomer/providers/amazon/aws/example_dags/example_emr_job_flow_manual_steps.py, astronomer/providers/amazon/aws/example_dags/example_emr_step_sensor.py, astronomer/providers/amazon/aws/hooks/emr.py, astronomer/providers/amazon/aws/sensors/emr.py, astronomer/providers/amazon/aws/triggers/emr.py, tests/amazon/aws/hooks/test_emr.py, tests/amazon/aws/sensors/test_emr.py, tests/amazon/aws/triggers/test_emr.py
Issue: https://github.com/astronomer/astronomer-providers/issues/120
EmrStepSensorAsync is a async (deferring) version of [EmrStepSensor](https://airflow.apache.org/docs/apache-airflow/1.10.13/_modules/airflow/contrib/sensors/emr_step_sensor.html)
This PR has the following changes 
- Add EmrStepSensorAsync/EmrStepSensorHookAsync/EmrStepSensorTrigger implementation
- Add unit test
- Add a self-sufficient example DAG
=> Add `EmrStepSensorAsync`

dev/Dockerfile
Airflow runtime image is at 4.2.4. So bumping the version of image in Dockerfile.
=> bump up astro-runtime image version

docs/_templates/autoapi/index.rst, docs/conf.py
closes https://github.com/astronomer/astronomer-providers/issues/201
Problem:
https://astronomer-providers.readthedocs.io/en/latest/_api/amazon/aws/sensors/s3/index.html does not contain `astronomer.providers` in the module name.
**Before**:
**After**:
=> Fix Sphinx docs to have correct module paths

docs/_templates/autoapi/index.rst
=> Docs: Sort API reference by Module Name

CONTRIBUTING.rst, Makefile, astronomer/providers/apache/livy/example_dags/example_livy.py, astronomer/providers/apache/livy/hooks/livy.py, astronomer/providers/apache/livy/operators/livy.py, astronomer/providers/apache/livy/triggers/livy.py, astronomer/providers/google/cloud/example_dags/example_dataproc.py, astronomer/providers/google/cloud/hooks/dataproc.py, astronomer/providers/google/cloud/operators/dataproc.py, astronomer/providers/google/cloud/triggers/dataproc.py, docs/conf.py, setup.cfg, tests/apache/livy/hooks/test_livy.py, tests/apache/livy/operators/test_livy.py, tests/apache/livy/triggers/test_livy.py, tests/google/cloud/hooks/test_dataproc.py, tests/google/cloud/operators/test_dataproc.py, tests/google/cloud/triggers/test_dataproc.py
- Add LivyOperatorAsync, LivyTrigger and LivyHookAsync
- Add example DAG for LivyOperatorAsync
- Propagate the logs dump from livy to worker through triggerer.
- Add tests for hooks, operators and triggers.
Implements: #119
=> Implement `LivyOperatorAsync`

.circleci/config.yml, .circleci/integration-tests/script.sh
Automate cloud deployment from circleci.
I have created a new workflow called nightly and a job deploy which runs at the scheduled time, at present, it will run daily around 0:0:0 IST and deploy main branch on the cloud.  
The integration test script now depends on env variable which comes from circleci for scheduled workflow.
=> CircleCI job for automatic deployment and execution of Integration Suite

.circleci/integration-tests/master_dag.py, .pre-commit-config.yaml, astronomer/providers/amazon/aws/example_dags/example_redshift_cluster_management.py, astronomer/providers/amazon/aws/example_dags/example_redshift_sql.py, astronomer/providers/amazon/aws/hooks/emr.py, astronomer/providers/amazon/aws/hooks/redshift_data.py, astronomer/providers/amazon/aws/sensors/emr.py, astronomer/providers/amazon/aws/triggers/emr.py, astronomer/providers/apache/livy/hooks/livy.py, astronomer/providers/apache/livy/operators/livy.py, astronomer/providers/databricks/hooks/databricks.py, astronomer/providers/http/hooks/http.py, astronomer/providers/snowflake/hooks/snowflake.py, setup.cfg, tests/amazon/aws/sensors/test_emr.py
This commit adds flake8 plugin for logging - https://github.com/globality-corp/flake8-logging-format in pre-commit Hooks so that we always use Lazy loading of args in logs.
=> Add `flake8` check for logging in Pre-commit Hooks

.pre-commit-config.yaml, astronomer/providers/amazon/aws/hooks/s3.py, astronomer/providers/amazon/aws/triggers/s3.py, astronomer/providers/apache/livy/hooks/livy.py, tests/apache/livy/hooks/test_livy.py, tests/core/triggers/test_external_task.py
This commit adds yet another flake8 plugin - https://github.com/PyCQA/flake8-bugbear . This plugin for flake8 helps finding likely bugs and design problems in code. Contains warnings that don't belong in pyflakes and pycodestyle:
=> Add `flake8-bugbear` in pre-commit hooks

astronomer/providers/google/cloud/example_dags/example_bigquery_queries.py
This PR introduces an "all_done" rule on the last task of bigquery example DAG, so that the resources will be deleted even if the predecessor tasks on the DAG fail.
Closes #210
=> Add trigger rule on last task of bigquery example DAG

.circleci/scripts/pre_commit_setup_cfg_all_extra.py, setup.cfg
This PR fixes a bug in the pre commit dependency config check script. The current logic uses a one side diff between two sets (`expected_all_extra` - `found_all_extra`).However it won't work in cases when the set `found_all_extra` contains an additional element which is not in set `expected_all_extra`.
Closes #218
=> Fix the pre-commit dependency check

tests/google/cloud/hooks/test_bigquery.py
bigquery hook test `test_get_job_output_assert_once_with` were getting skipped
=> Fix bigquery hook skipping test

astronomer/providers/apache/livy/hooks/livy.py, astronomer/providers/apache/livy/operators/livy.py, docs/conf.py
This commit autogenerates the list using the list of providers in "all" extras in setup.cfg. This way we don't need to manually add providers when we add operators for new Providers. This also fixes the issue with missing Livy inventory.
This helps in the docs as shown below by allow users to click on the link for the docs of Base/inherited class.
But because Livy doesn't have an inventory, it doesn't show right now:
=> Automate inventory list for all providers

docs/conf.py
This will allow users to know which params can be passed which is difficult right now as we don't need to override `__init__` method for most of the Operator/sensors.
**Before**:
**After**:
=> Docs: Include docstrings from inherit class's `__init__`

.circleci/integration-tests/master_dag.py
Include example_emr_sensor DAG in the integration test and remove example_emr_job_flow_sensor and example_emr_step_sensor DAG since example_emr_sensor contain both
=> Add example_emr_sensor in integration test

.pre-commit-config.yaml
This is not bullet proof but will prevent us adding Secrets in some scenarios which is good enough.
=> Add pre-commit hooks for detecting private key & AWS Creds

astronomer/providers/apache/livy/example_dags/example_livy.py
The LivyOperatorAsync example DAG is failing as part of the integration
tests on staging environment. The reason for the failure is that the DAG is
referring to AWS environment variables different than what has been
configured in the staging deployment. This change renames such AWS 
environment variables to be consistent with other example DAG and the
same have been set in the staging deployment environment.
Closes: https://github.com/astronomer/astronomer-providers/issues/237
=> Fix LivyOperatorAsync example DAG

.circleci/integration-tests/Dockerfile
- Docker image build was failing due to gcc being unavailable.
- Add build-essentials and libsasl2 dependencies in `Dockerfile`.
=> Update  Integration `Dockerfile`

astronomer/providers/microsoft/azure/example_dags/example_adf_run_pipeline.py
Removed generalised exception type `Exception ` and catching  `azure.core.exceptions.HttpResponseError` which is raise by azure SDK. Changed `logger.info` to `logger. exception` get more exception info.
=> Use Exception sub class in azure datafactory example DAG

.circleci/integration-tests/Dockerfile, astronomer/providers/apache/hive/example_dags/example_hive.py, astronomer/providers/apache/hive/sensors/hive_partition.py
- Make example dag of `HivePartitionSensorAsync` self-sufficient for integration testing.
- Update sphinx docs and doc-strings to `HivePartitionSensorAsync`.
- The library version of hive and Hadoop in ``Dockerfile`` should match the remote cluster where the
Hadoop and hive are running.
Closes #265
=> Make `HivePartitionSensorAsync` example dag self-sufficient.

.circleci/integration-tests/master_dag.py
- The hive dag model was updated in master dag so that it can pick the hive example dag and run it.
=> Update hive dag name in Integration Master dag

astronomer/providers/databricks/example_dags/example_databricks.py
This PR makes changes to the Databricks example DAG to use the lower cost m4.large node type.
Closes #286
=> Optimize resource usage in Databricks example DAG

astronomer/providers/amazon/aws/example_dags/example_redshift_cluster_management.py, astronomer/providers/core/example_dags/example_external_task_wait_for_me.py, astronomer/providers/google/cloud/example_dags/example_bigquery_queries.py, astronomer/providers/google/cloud/example_dags/example_dataproc.py, astronomer/providers/http/example_dags/example_http.py
Fix example docstring tag typo.
Closes: #284
=> Fix example docs tag

.circleci/integration-tests/Dockerfile, .circleci/integration-tests/master_dag.py, .circleci/integration-tests/nuke-config.yml, astronomer/providers/amazon/aws/example_dags/example_aws_nuke.py, astronomer/providers/microsoft/azure/example_dags/example_adf_run_pipeline.py
This PR introduces aws-nuke utility into the integration workflow so that we can clean our aws resources at a specified time of each day.
Fixes part of #44
=> Enable `aws-nuke` to delete specified AWS resources

RELEASING.rst
This commit adds instructions on closing out the milestone related to the version when releasing
=> Add note on closing GitHub milestone when releasing

tests/databricks/operators/test_databricks.py
Following tests for Databricks are failing and observed in a non-related PR: #290
1. test_databricks_submit_run_operator_async
2. test_databricks_run_now_operator_async
The reason for failure is that the execute method called in these
tests is trying to push an XCOM against task instance 'ti' of
the context. Previously, context was an empty dictionary missing
the 'ti' key. We now are using the create_context utility to
generate a context object which includes the 'ti' key against which
the XCOM is getting pushed.
=> Fix failing Databricks tests

.circleci/integration-tests/Dockerfile, .circleci/integration-tests/script.sh
The commit includes the following fixes:
1. Report failure of any of the commands of the deployment script
and exit the script with status code.
2. Upgrade runtime image to 4.2.6 to be compatible with Astro
Cloud environment
Closed #274
=> Fixes for deploying integration tests on Astro Cloud

.circleci/integration-tests/Dockerfile, dev/Dockerfile
With respect to the recent Airflow release:
https://github.com/astronomer/astro-runtime/blob/main/CHANGELOG.md#500-2022-04-30
and https://airflow.apache.org/docs/apache-airflow/2.3.0/release_notes.html#airflow-2-3-0-2022-04-30,
upgrade the base image in Dockerfiles to the following versions:
ap-airflow:2.2.5 -> ap-airflow:2.3.0
astro-runtime:4.2.4-base, astro-runtime:4.2.6-base -> astro-runtime:5.0.0-base
Closed: #300
=> Upgrade base Airflow images to latest version

astronomer/providers/apache/hive/hooks/hive.py, tests/apache/hive/hooks/test_hive.py
MyPY release a new version recently 0.950 which has rightly pointed
out that we're missing an await on asyncio.sleep coroutine in our
Hive connection hook module.
The fix adds an await for the same.
Closes: #295
=> Add missing await on aysncio.sleep coroutine in Hive hook

.readthedocs.yaml
https://readthedocs.org/projects/astronomer-providers/builds/16816473/ is failing,
this will fix it.
=> Add `libsasl` to ReadTheDocs build

.circleci/integration-tests/master_dag.py, .circleci/scripts/verify_tag_and_version.py, astronomer/providers/amazon/aws/example_dags/example_aws_nuke.py, astronomer/providers/amazon/aws/example_dags/example_redshift_cluster_management.py, astronomer/providers/amazon/aws/example_dags/example_redshift_sql.py, astronomer/providers/amazon/aws/example_dags/example_s3.py, astronomer/providers/apache/hive/example_dags/example_hive.py, astronomer/providers/apache/livy/example_dags/example_livy.py, astronomer/providers/core/example_dags/example_file_sensor.py, astronomer/providers/databricks/example_dags/example_databricks.py, astronomer/providers/google/cloud/example_dags/example_bigquery_queries.py, astronomer/providers/google/cloud/example_dags/example_bigquery_sensors.py, astronomer/providers/google/cloud/example_dags/example_dataproc.py, astronomer/providers/google/cloud/example_dags/example_gcs.py, astronomer/providers/http/example_dags/example_http.py, astronomer/providers/snowflake/example_dags/example_snowflake.py
This PR will update `os.environ.get` to `os.getenv` so that fetching env will be consistent across the reop.
Closes: https://github.com/astronomer/astronomer-providers/issues/307
=> Replace `os.environ.get` to `os.getenv`

.circleci/integration-tests/Dockerfile
Image `ap-airflow:2.3.0-1 `was not coming up on staging.
Use image `ap-airflow:2.3.0-3` as per latest update on the issue.
Closes: #300
=> Update staging image to ap-airflow:2.3.0-3

.gitignore, Makefile, astronomer/providers/google/cloud/extractors/bigquery_async_extractor.py, astronomer/providers/google/cloud/extractors/bigquery_insertjoboperatorasync_extractor.py, astronomer/providers/google/cloud/operators/bigquery.py, astronomer/providers/google/cloud/triggers/bigquery.py, dev/docker-compose.yaml, dev/local_flask_lineage_server.py, setup.cfg, tests/google/cloud/extractors/job_details.json, tests/google/cloud/extractors/test_bigquery_async_extractor.py, tests/google/cloud/extractors/test_bigquery_insertjoboperatorasync_extractor.py, tests/google/cloud/operators/test_bigquery.py, tests/google/cloud/triggers/test_bigquery.py
Export job_id as XCOM for the BigQueryInsertJobOperatorAsync operator
and add an OpenLineage custom extractor for the same.
The custom extractor is an extension of OpenLineage BigQuery extractor to include
BigQueryInsertJobOperatorAsync.
The OpenLineage extractor has a common implementation to fetch statistics for
big query with the given job_id which is fetched from XCOM in the case of Airflow tasks.
So, I believe, all we need to do is push the job_id as XCOM for the task
which is pulled by OpenLineage and the metadata is fetched & extracted
by the common implementation.
Some additional OpenLineage specific environment variables need to be set
which are included as part of the docker-compose.yaml file change in the commit.
Also, adding a flask based local Lineage server where we can …
=> Add implementation for OpenLineage custom extractor for BigQueryInsertJobOperatorAsync

astronomer/providers/apache/hive/example_dags/example_hive.py, astronomer/providers/apache/hive/hooks/hive.py, astronomer/providers/apache/hive/sensors/named_hive_partition.py, astronomer/providers/apache/hive/triggers/named_hive_partition.py, tests/apache/hive/hooks/test_hive.py, tests/apache/hive/sensors/test_named_hive_partition.py, tests/apache/hive/triggers/test_named_hive_partition.py
Support for NamedHivePartitionSensorAsync. It currently only works with a plain auth mechanism.
- Add Sensor/Trigger 
- Add unit test 
- Add example
Sync Version sensor [NamedHivePartitionSensor](https://github.com/apache/airflow/blob/main/airflow/sensors/named_hive_partition_sensor.py)
Closes: #277
=> Add `NamedHivePartitionSensorAsync`

setup.cfg
Flask is a dev onoly requirement and is also a core requirement for Airflow.
=> Remove Flask from requirements

.circleci/config.yml, setup.cfg
closes https://github.com/astronomer/astronomer-providers/issues/180
Airflow 2.3 now supports Python 3.10 and so we should be able to officially support Python 3.10 too.
This PR runs all the unit tests with Python 3.10 too
=> Officially Support Python 3.10

.circleci/config.yml
This will help us to debug/check when CI starts failing because a new version of the library was released.
=> CI: Show installed deps before running tests

astronomer/providers/amazon/aws/example_dags/example_emr_sensor.py, astronomer/providers/apache/hive/example_dags/example_hive.py, astronomer/providers/apache/livy/example_dags/example_livy.py
This PR will standardize the EMR cluster names used in the integration testing, so that we can identify the example DAG which creates them, instead of using random names like "PiCalc"
Closes #299
=> Follow similar naming convention across EMR clusters

.circleci/integration-tests/master_dag.py, astronomer/providers/amazon/aws/example_dags/example_redshift_cluster_management.py, astronomer/providers/amazon/aws/example_dags/example_redshift_sql.py, astronomer/providers/apache/hive/example_dags/example_hive.py
Currently, we're catching few exceptions in our tasks as part of our example DAGs.
Such exceptions caught do log the exceptions but return None. As a result,
the task is getting marked as success/green and the downstream tasks fail
due to missing resources of this previous task outcome.
Fix such exceptions caught to rightly reflect the status of the tasks.
Closes: #321
=> Reraise exceptions caught in except block

.circleci/integration-tests/Dockerfile, dev/Dockerfile, dev/Dockerfile.emr_eks_container
Following are the latest releases for base Docker images:
`astro-runtime:5.0.1`
`ap-airflow:2.3.0-4`
Update our builds to the same.
=> Update base Astronomer images to latest release tags

README.rst, astronomer/providers/google/cloud/extractors/bigquery_async_extractor.py, dev/docker-compose.yaml, setup.cfg, tests/google/cloud/extractors/test_bigquery_async_extractor.py
This reverts commit 39102d01bc95fdb74635462ff3ee896b092699d8  to add back implementation 
for OpenLineage extractor for BigQueryInsertJobAsyncOperator. 
It was temporarily removed for release 1.3.0
Also, addressed Kaxil's comments on PR #290
=> Add back implementation for OpenLineage extractor for BigQueryInsertJobAsync Operator

.circleci/integration-tests/nuke-config.yml
This change to the nuke config will ensure that any left over EKS cluster is terminated to save costs. Note that since we should not delete databricks-workspace-stack, it is included in the filters so that `aws-nuke` would not delete it
Closes #337
Below are the logs of the run with this change.
```
us-east-2 - EC2Instance - i-0b0fff6220c1aaf69 - [Identifier: "i-0b0fff6220c1aaf69", ImageIdentifier: "ami-0410b1b829bec36f6", InstanceState: "running", InstanceType: "m5.large", LaunchTime: "2022-05-11T20:34:58Z", tag:Name: "providers-team-eks-cluster-ng-2c554d24-Node", tag:alpha.eksctl.io/nodegroup-name: "ng-2c554d24", tag:alpha.eksctl.io/nodegroup-type: "managed", tag:aws:autoscaling:groupName: "eks-ng-2c554d24-eec057c8-e1cc-86f3-d6b2-a740bb8d905c", tag:aws:ec2:fleet-id: …
```
=> Nuke `CloudFormation` resource before `EKSCluster`

dev/docker-compose.yaml
Since we already have the same ARG in the respective Dockerfiles with
updated image tags, it makes sense to remove it from the docker-compose
build target.
=> Remove IMAGE_NAME args from docker-compose build target

astronomer/providers/apache/hive/example_dags/example_hive.py, astronomer/providers/apache/livy/example_dags/example_livy.py
The previous implementation was checking only for the presence
of the machine's IP address for existence of ALLOW permission
in the security group. As a result, when both Livy and Hive example
DAGs run concurrently, one of them adds the machine's IP along with
its ports to be authorized, but the second DAG sees that the IP
is already added and then skips authorizing its port. To elaborate
with an example, let's suppose the Hive example DAG runs first. It
will authorize and open port '22' and '10000' for the machine's IP.
When the Livy operator runs, it will see that rules against the
machine's IP already exist in the security group and as a result
it will skip authorizing its required port '8998' in the security
group.
To fix this, the commit removes the check on IP in the security
group …
=> Fix ingress port authorizations for Livy & Hive example DAGs

astronomer/providers/cncf/kubernetes/example_dags/example_kubernetes_pod_operator.py
The previous command had just a plain sleep of 30 seconds.
Enhance it to write some log every one second and go back to sleep.
=> Enhance command to be run inside KubernetesPodOperator

astronomer/providers/amazon/aws/example_dags/example_redshift_cluster_management.py, astronomer/providers/amazon/aws/example_dags/example_redshift_sql.py
Cluster delete and snapshot delete tasks keep on waiting while
the status is in `deleting` state. Since, the status get is part
of a while loop, the last iteration when they get deleted raises
an exception that the corresponding resource is not found and it
marks the task as failed. We are fixing this by catching the relevant
status code and other exceptions are re-raised.
Additionally, it is observed quite often that the DAG tasks fail
without any logs. @ephraimbuddy suggested that this could be due
to DAG processing timeouts occurring due to time spent in importing
heavy libraries (although we could not find the dag processing logs in Astro cloud). 
So taking this guess & the reference of
https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html#top-level-python-code …
=> Fix Redshift DAGs to catch appropriate exceptions

astronomer/providers/amazon/aws/example_dags/example_emr_eks_containers_job.py, astronomer/providers/apache/hive/example_dags/example_hive.py, astronomer/providers/apache/livy/example_dags/example_livy.py, astronomer/providers/microsoft/azure/example_dags/example_adf_run_pipeline.py
DAGs processing might timeout due to import of heavy libraries
at top module level. Since, the DAGs are refreshed often, we want
to avoid such timeouts in processing. Hence, delay the import of
heavy libraries to task definition scope.
Reference: https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html#top-level-python-code
part of: #351
=> Delay import of libraries to task scope

astronomer/providers/google/cloud/extractors/bigquery_async_extractor.py, tests/google/cloud/extractors/test_bigquery_async_extractor.py
I observed that the hook that we attach in `execute` method
https://github.com/astronomer/astronomer-providers/blob/main/astronomer/providers/google/cloud/operators/bigquery.py#L92
is not available in `execute_complete` https://github.com/astronomer/astronomer-providers/blob/main/astronomer/providers/google/cloud/operators/bigquery.py#L129
I tried to attach this hook in `execute_complete`; it does get
attached, however, it no longer remains attached to the operator
outside its scope. Previously, the hook attached in `execute` was
available throughout (even in the extractor), but this no longer
seems to be the case. Something has changed internally which is
wiping out the hook from the operator that we manually attach to it.
To make the connection available in the extractor, I am …
=> Reconstruct hook using connection ID in the extractor

astronomer/providers/core/triggers/external_task.py, tests/core/triggers/test_external_dag.py
`DagStateTrigger` has wrong module name.
The trigger fails with:
```
File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'astronomer.providers.core.triggers.external_dag'
```
=> Correct module name for DagStateTrigger

astronomer/providers/amazon/aws/hooks/base_aws_async.py, astronomer/providers/amazon/aws/hooks/redshift_cluster.py, astronomer/providers/amazon/aws/hooks/redshift_sql.py, astronomer/providers/amazon/aws/hooks/s3.py, astronomer/providers/amazon/aws/sensors/redshift_cluster.py, astronomer/providers/amazon/aws/sensors/s3.py, astronomer/providers/amazon/aws/triggers/s3.py, astronomer/providers/core/sensors/filesystem.py, astronomer/providers/core/triggers/filesystem.py, astronomer/providers/google/cloud/triggers/dataproc.py, astronomer/providers/google/cloud/triggers/gcs.py
There are some places where we have declared a log variable has the value `logging.getLogger(__name__)`  in this PR I'm removing it because mostly it is unused and it adds an extra attribute log in documentation
=> Remove unused ``logging.getLogger`` call

astronomer/providers/core/example_dags/example_external_task.py, astronomer/providers/core/example_dags/example_external_task_wait_for_me.py
Update `ExternalTaskSensorAsync` example DAG so that it correctly defer and run for both scenarios when external_task_id is given and not given.
Closes: #369
=> Update ExternalTaskSensorAsync example dag to defer

CHANGELOG.rst
I just released 1.3.1 - https://github.com/astronomer/astronomer-providers/releases/tag/1.3.1
This commit adds changelog to the main branch
=> Add changelog for 1.3.1

.circleci/integration-tests/master_dag.py
Removed `test_external_task_async_waits_for_me_dag_from_master_dag` from `master_dag` since this dag does not test any of our async implantations but the purpose of this was to run `ExternalTaskSensorAsync` example DAG so no need to trigger this via master DAG. 
Now, [astronomer/providers/core/example_dags/example_external_task.py](https://github.com/astronomer/astronomer-providers/pull/370/files#diff-b9ba255046aec454155394e74f499084ba8ed2683b77f7316331b201da786656) trigger this instead of master DAG
related to: https://github.com/astronomer/astronomer-providers/issues/369
=> Remove test_external_task_async_waits_for_me from master DAG

.circleci/integration-tests/master_dag.py
Fix external_task DAG name mismatch in example dag in master dag
Related PR: https://github.com/astronomer/astronomer-providers/pull/370
=> Fix Example ExternalTaskSensorAsync DAG name mismatch 

astronomer/providers/cncf/kubernetes/operators/kubernetes_pod.py, astronomer/providers/cncf/kubernetes/triggers/wait_container.py, setup.cfg, tests/cncf/kubernetes/operators/test_kubernetes_pod.py, tests/cncf/kubernetes/triggers/test_wait_container.py
This PR modifies Async KPO to periodicall resume the sync portion of the task to fetch and emit the latest logs before deferring again.  
To control this behavior a new param is added: `logging_interval`.  If `None` then Async KPO operates as it did before, never resuming the sync task until the pod is done running.  If logging_interval is given a value (integer seconds) then the trigger will resume every `logging_interval` seconds to fetch latest logs and defer again (until pod is done).
Here's a task example you can test this with:
```python
test_kubernetes_pod = KubernetesPodOperatorAsync(
namespace='airflow',
image='python:3.8-slim',
cmds=[
"bash",
"-cx",
(
"i=0; "
"while [ $i -ne 30 ]; "
"do i=$(($i+1)); "
"echo $i; "
"sleep 1; "
"done; "
"mkdir -p /airflow/xcom/; "
"echo …
```
=> Enable perioding resuming to fetch logs for KPOA

.circleci/integration-tests/Dockerfile, .circleci/integration-tests/master_dag.py, dev/Dockerfile, dev/Dockerfile.emr_eks_container
Bump to the following versions
Staging image -> quay.io/astronomer/ap-airflow:2.3.1-1
Astro Cloud image -> quay.io/astronomer/astro-runtime:5.0.2
Additionally, disable run of `example_emr_eks_pi_job` DAG as part
of `master_dag` run to not make it run until the issue is fixed
for the DAG.
=> Bump image tags to latest Airflow releases

astronomer/providers/google/cloud/example_dags/example_bigquery_queries.py
The deprecated param `bigquery_conn_id` of
`BigQueryCreateEmptyDatasetOperator` has been removed as part of
PR https://github.com/apache/airflow/pull/23326 . Hence, update the
operator task to use the new param `gcp_conn_id`.
Attaching the DAG import error screenshot.
=> Replace parameter for operator post removal of deprecated param

astronomer/providers/amazon/aws/hooks/base_aws_async.py
- Add limitations of using [aiobotocore](https://aiobotocore.readthedocs.io/en/latest/tutorial.html#using-botocore) in doc-strings
=> Add limitations for the AwsBaseHookAsync in doc-strings

astronomer/providers/cncf/kubernetes/hooks/kubernetes_async.py, tests/cncf/kubernetes/hooks/test_kubernetes.py
This PR should fix `Unclosed client session error`.  
While creating the Kubernetes API client in a couple of scenarios we were calling `client.ApiClient()` twice. As fix, I'm checking if the client already initialised do not call `client.ApiClient()`
Closes: #372
=> Fix unclosed client session error for KPOA

astronomer/providers/amazon/aws/example_dags/example_aws_nuke.py, astronomer/providers/amazon/aws/example_dags/example_emr_eks_containers_job.py, astronomer/providers/amazon/aws/example_dags/example_emr_sensor.py, astronomer/providers/amazon/aws/example_dags/example_redshift_cluster_management.py, astronomer/providers/amazon/aws/example_dags/example_redshift_sql.py, astronomer/providers/amazon/aws/example_dags/example_s3.py, astronomer/providers/apache/hive/example_dags/example_hive.py, astronomer/providers/apache/livy/example_dags/example_livy.py, astronomer/providers/cncf/kubernetes/example_dags/example_kubernetes_pod_operator.py, astronomer/providers/core/example_dags/example_external_task.py, astronomer/providers/core/example_dags/example_external_task_wait_for_me.py, astronomer/providers/core/example_dags/example_file_sensor.py, astronomer/providers/databricks/example_dags/example_databricks.py, astronomer/providers/google/cloud/example_dags/example_bigquery_queries.py, astronomer/providers/google/cloud/example_dags/example_bigquery_sensors.py, astronomer/providers/google/cloud/example_dags/example_dataproc.py, astronomer/providers/google/cloud/example_dags/example_gcs.py, astronomer/providers/http/example_dags/example_http.py, astronomer/providers/microsoft/azure/example_dags/example_adf_run_pipeline.py, astronomer/providers/snowflake/example_dags/example_snowflake.py
Adds `retries` argument along with `retry_delay` to reattempt
failed tasks in example DAGs.
=> Add `retries` arg in the default params for example DAGs

astronomer/providers/google/cloud/example_dags/example_dataproc.py, astronomer/providers/google/cloud/operators/dataproc.py, astronomer/providers/google/cloud/triggers/dataproc.py, tests/google/cloud/operators/test_dataproc.py, tests/google/cloud/triggers/test_dataproc.py
This PR fix 
- Push dataproc Job Id instead of success message in xcom as sync version does 
- Fix test as per above change
- Remove kwargs param from DataProcSubmitTrigger, Since this does not require 
- Delete cluster and delete bucket task should always run in the example
- Optimize DAG. earlier it was creating 7 instances now it will create 3
Closes: #400
=> [Dataproc] Optimize Example DAG And Push Job ID in XCOM

tests/cncf/kubernetes/operators/test_kubernetes_pod.py, tests/google/cloud/operators/test_bigquery.py
Closes: #438 
- in apache-airflow-providers-google 8.0.0 in bigquery it is expecting that context should have logical_date not execution_date
- apache-airflow-providers-cncf-kubernetes 4.1.0 Kubernetes hook has changed and expect a few more params so kube client is getting affected
-------
- Updated bigquery test to set logical_date in context
- for Kubernetes mock client
=> Fix CI: Update CNCF.Kubernetes and Bigquery Test

Makefile, astronomer/providers/amazon/aws/example_dags/example_redshift_cluster_management.py, astronomer/providers/amazon/aws/hooks/redshift_cluster.py, astronomer/providers/amazon/aws/operators/redshift_cluster.py, astronomer/providers/amazon/aws/triggers/redshift_cluster.py, dev/Dockerfile.aws, tests/amazon/aws/hooks/test_redshift_cluster.py, tests/amazon/aws/operators/test_redshift_cluster.py, tests/amazon/aws/triggers/test_redshift_cluster.py
The PR addresses the following:
- Implements necessary operator, trigger, hook changes to allow  async deletion of a Redshift cluster.
- Uses this new operator `RedshiftPauseClusterOperatorAsync` in the example DAG.
- Fixes existing tests that fail due to method signature change.
- Add a make target to build images with `aws-cli` installed required for local testing of AWS example DAGs
closes: #403
=> Add async implementation for Redshift cluster deletion

astronomer/providers/google/cloud/operators/dataproc.py, astronomer/providers/google/cloud/triggers/dataproc.py, tests/google/cloud/operators/test_dataproc.py, tests/google/cloud/triggers/test_dataproc.py
closes: #424 
This PR handle below scenario for the DataprocCreateClusterOperatorAsync
- when clusters already exist and the use_if_exists param set true then use the existing cluster 
- when clusters already exist and use_if_exists param set false then raise an error
-  when the cluster is in deleting state, wait for the cluster to delete and create a new one
- when an error occurs and the delete_on_error param is set to true delete the cluster 
- in case of error exception will have diagnose_cluster API response 
The above behaviours were missing in async in my prev implemention
=> Handle dataproc create cluster error gracefully

astronomer/providers/google/cloud/operators/bigquery.py, setup.cfg, tests/google/cloud/extractors/test_bigquery_async_extractor.py, tests/google/cloud/operators/test_bigquery.py
- Sync version has changed and removed _job_id in operator which was used in our repo,
- Code has been moved to hooks with certain changes.
- Implement the code change needed for it in our repo
closes #470
=> Fix BigQueryInsertJobOperatorAsync failure after the google provider upgrade

.circleci/integration-tests/master_dag.py, Makefile, dev/Dockerfile, dev/Dockerfile.google_cloud
Look like GKEStartPodOpetror both sync and async do not work on astro-cloud tested both on astro-cloud posted log on git issue
- Disable GKEStartPod in the integration test
- Remove google cloud installation steps from the dev docker file since it was slowing down the dev build 
- Create dev/Dockerfile.google_cloud and add build-google-cloud in the makefile to install google-cloud cli in the image
Issue: https://github.com/astronomer/astronomer-providers/issues/443
=> Disable GKEStartPod Integration Test

.circleci/integration-tests/master_dag.py, astronomer/providers/microsoft/azure/example_dags/example_azure_test_file.txt, astronomer/providers/microsoft/azure/example_dags/example_wasb_sensors.py, astronomer/providers/microsoft/azure/hooks/wasb.py, astronomer/providers/microsoft/azure/sensors/wasb.py, astronomer/providers/microsoft/azure/triggers/wasb.py, tests/microsoft/azure/hooks/test_wasb.py, tests/microsoft/azure/sensors/test_wasb.py, tests/microsoft/azure/triggers/test_wasb.py
The commit adds the following:
- Implementation for hook, triggers and sensors for `WasbBlobSensorAsync` & `WasbPrefixSensorAsync`
- A self-sufficient example DAG to create a data storage container, upload a test blob, run
the sensors, delete the uploaded blob and delete the created data storage container in the
same order. The DAG needs an Azure Storage Account and an Airflow connection to be created
for the corresponding Azure Storage Account
- Handle exceptions
- Add relevant docstrings for the implementation
closes: #188
=> Implement Azure WasbBlobSensorAsync and WasbPrefixSensorAsync

astronomer/providers/amazon/aws/operators/emr.py, astronomer/providers/amazon/aws/sensors/emr.py, astronomer/providers/amazon/aws/triggers/emr.py, tests/amazon/aws/triggers/test_emr.py
closes: https://github.com/astronomer/astronomer-providers/issues/243
=> Add EMR Container Base Trigger

astronomer/providers/amazon/aws/example_dags/example_batch.py, docs/providers/amazon/aws/sensors/batch.rst, docs/providers/amazon/index.rst, docs/providers/microsoft/azure/sensors/wasb.rst, docs/providers/microsoft/index.rst
closes: #490 
Here, I'm documenting an example DAG for recently merged PR going forward we will try to include example DAG documentation in the operator/sensor implementation PR itself
=> Add missing example DAG in documentation

astronomer/providers/amazon/aws/example_dags/example_batch.py
In `example_batch.py` was failing at certain times because` disable_job_queue_func` was not waiting for the job queue to be disabled.  This PR adds a check for the job queue to be disabled before it moves to the next task.
closes #413
=> Fix `example_batch`  DAG to check for job queue status.

Makefile, dev/scripts/replace_dependencies.py, dev/scripts/trigger_master_dag.py
The commit adds a make target `test-rc-dependencies` along with a
couple of python scripts to do the following:
1. Update setup.cfg to reflect given pinned provider dependencies
2. Build an image with updated setup.cfg and deploy it to existing
Astro Cloud deployment
3. Trigger master DAG by calling the Airflow REST API
4. Checkout from git local changes made to setup.cfg
closes: #472
=> Add make target to use pinned provider depedencies for testing an RC

docs/conf.py, setup.cfg
With this change, users will be able to copy code-blocks with one click as shown in the video below.
https://user-images.githubusercontent.com/8811558/178005659-cded8d0f-a384-4648-bfbc-acd7e3ab6082.mp4
=> Add copy button to Code Blocks in docs

astronomer/providers/cncf/kubernetes/hooks/kubernetes.py
This should fix failing errors on main - https://app.circleci.com/pipelines/github/astronomer/astronomer-providers/2333/workflows/b7300908-21d3-426b-860d-7cbe1df09412/jobs/9108
```
mypy 0.961
(compiled:
yes)
astronomer/providers/cncf/kubernetes/hooks/kubernetes.py:53: error: Unused
"type: ignore" comment
async with aiofiles.tempfile.NamedTemporaryFile() as temp_...
^
astronomer/providers/cncf/kubernetes/hooks/kubernetes.py: note: In member "_load_config" of class "KubernetesHookAsync":
astronomer/providers/cncf/kubernetes/hooks/kubernetes.py:55: error: Value of
type "Coroutine[Any, Any, int]" must be used  [unused-coroutine]
temp_config.write(kubeconfig.encode())
^
astronomer/providers/cncf/kubernetes/hooks/kubernetes.py:55: note: Are you missing an await? …
```
=> Fix mypy errors

docs/_ext/traverse_operators_sensors.py, docs/_templates/traverse_operators/index.rst, docs/conf.py, docs/index.rst, docs/providers/operators_and_sensors_list.rst
The commit adds a custom Sphinx extension doing the following:
1. Walk the providers diretory and using ast.parse collect list of
operators and sensors
2. Use raw HTML to generate tables for the above collected operators
and sensors. Also, adds a link to the class definitions generated
by URL construction.
=> Add custom Sphinx extension to list available operators & sensors

.circleci/integration-tests/master_dag.py, astronomer/providers/snowflake/example_dags/example_snowflake_sql_api.py, astronomer/providers/snowflake/hooks/snowflake_sql_api.py, astronomer/providers/snowflake/hooks/sql_api_generate_jwt.py, astronomer/providers/snowflake/operators/snowflake.py, astronomer/providers/snowflake/triggers/snowflake_trigger.py, docs/providers/snowflake/index.rst, docs/providers/snowflake/operators/snowflake_sql_api.rst, tests/snowflake/hooks/test_snowflake_sql_api.py, tests/snowflake/hooks/test_sql_api_generate_jwt.py, tests/snowflake/operators/test_snowflake.py, tests/snowflake/triggers/test_snowflake.py
Implemented Async Snowflake SQL API Operator to support multiple  SQL statements sequentially, which is the behavior of the SnowflakeOperator,  the Snowflake SQL API allows for submitting multiple SQL statements in a single request. In combination with aiohttp, this may be an option for creating a SnowflakeSQLOperatorAsync that matches the query submission behavior of the SnowflakeOperator.
Documentation 
https://www.notion.so/astronomerio/Snowflake-Async-Operators-2a62522b1f534a02bde099b104216c41
closes: #477
=> Implement Async Snowflake SQL API Operator

astronomer/providers/snowflake/hooks/sql_api_generate_jwt.py
Mypy is complaining with the below error:
```
astronomer/providers/snowflake/hooks/sql_api_generate_jwt.py:132: error:
Incompatible types in assignment (expression has type "str", variable has type
"None")  [assignment]
self.token = token
^
Found 1 error in 1 file (checked 158 source files)
```
The commit is to fix the above error
closes: #520
=> Fix mypy issue for token variable of sql_api_generate_jwt.py module

.circleci/integration-tests/master_dag.py
Use a BashOperator to get the airflow version and pushes the result
to XCOM. Pass `context` to Slack report task so that it can pull
the airflow version from XCOM pushed by the BashOperator.
closes: #516
=> Add Airflow version in the Slack report for master DAG run

Makefile
It is observed on Astro Cloud that when a new image is deployed it
takes certain time to update the image on all Airflow component pods.
Currently, there is no programatic way to know whether the image
has been updated across all components. Hence, once the image is
deployed as part of the RC test make target, we are introducing
a sleep of 15 mins to allow the image to be updated across all
Airflow component pods before triggering the master DAG.
closes: #518
=> Add 15 mins sleep between deploying image & triggering master DAG

astronomer/providers/amazon/aws/hooks/redshift_data.py, astronomer/providers/amazon/aws/hooks/redshift_sql.py, tests/amazon/aws/hooks/test_redshift_data.py, tests/amazon/aws/hooks/test_redshift_sql.py
- Instead of giving both resource type and client type, it works with only client type
- Tested this change with both version
`apache-airflow-providers-amazon>=3.0.0` and latest `apache-airflow-providers-amazon==4.1.0rc1`
- Fixed for RedshiftDataOperatorAsync hook
- Added try, except for backwards and forwards-compatible without bumping the dependency
closes #523
=> Fix RedshiftSQL Operator DAG failure

.pre-commit-config.yaml
The pre-commit hook checks that there are no dead links in the
markdown files of the repo.
Reference: https://github.com/tcort/markdown-link-check
closes: #511
=> Add pre-commit hook to check for dead links in markdown files

astronomer/providers/google/cloud/example_dags/example_bigquery_queries.py
The type for schema field is not matching with the query field value.
The query field value is of type string and hence we're making the
field type to string too to fix the failing example DAG.
=> Fix example DAG for failing bigquery integration test

astronomer/providers/http/sensors/http.py
HttpSensorAsync was not taking `poll_interval` as an argument.
closes #526.
=> Add `poll_interval` in `HttpSensorAsync`

dev/docker-compose.yaml
`AIRFLOW__CORE__SQL_ALCHEMY_CONN` has been deprecated so we should consider using the new env `AIRFLOW__DATABASE__SQL_ALCHEMY_CONN`
=> Update `sql_alchemy_conn` in docker compose

astronomer/providers/amazon/aws/hooks/batch_client.py, astronomer/providers/amazon/aws/operators/batch.py, astronomer/providers/apache/livy/hooks/livy.py
- Before whatever link mention in `see also` in doc sting was not showing up in document page now  fixed it
closes: #560
=> Fix `see also` link mentioned in Document

astronomer/providers/google/cloud/example_dags/example_gcp_nuke.py, astronomer/providers/google/cloud/example_dags/example_kubernetes_engine.py
Use `gcloud sdk` within `PythonOperator` to terminate resources created
in the example DAGs including `GKE clusters`, `Dataproc clusters`,
`Compute instances` and `Storage buckets`.
For authentication, it needs a service account file which is
temporarily created by reading the stringified service account json
stored as variable in Airflow UI.
part of: #44
=> Nuke GCP resources.

astronomer/providers/snowflake/operators/snowflake.py
Added Doc string for the SnowflakeOperatorAsync to get to know the use of this operator compared with snowflake sql API operator, best practices to be followed while using this operator and where can this `SnowflakeOperatorAsync` can be used
closes: #557
=> Update Doc string for SnowflakeOperatorAsync

astronomer/providers/amazon/aws/example_dags/example_emr_sensor.py
Now `emr_conn_id` is optional in EmrCreateJobFlowOperator since the configuration we pass using param `job_flow_overrides` so the `emr_conn_id` is no longer require. We can merge this once the provider for June is released `apache-airflow-providers-amazon==4.1.0`
OSS PR: https://github.com/apache/airflow/pull/24306
=> Remove EMR Conn from example

docs/_ext/traverse_operators_sensors.py
Correct the base URL for https://astronomer-providers.readthedocs.io/
so that class def links from operators & sensors list page work
correctly.
closes: #566
=> Update base url for API docs to fix broken links

docs/_ext/traverse_operators_sensors.py
The commit adds an inline script tag to associate class def link
to the operator/sensor by extracting the prefix document version
from the url location of the current page and constructing the whole
URL by using this document version as the prefix.
=> Generate class def link dynamically based on document version

astronomer/providers/http/triggers/http.py
The `HttpTrigger.run()` docstring mentions "Databricks" while this should be http.
=> Fix error in docstring

Makefile
Currently, make run-mypy doesn't take image name as arg and fails to build.
This PR adds the image name to be taken as build args 
Closes #578
=> Update run-mypy command

astronomer/providers/google/cloud/operators/dataproc.py, astronomer/providers/google/cloud/triggers/dataproc.py
The Dataproc DAG has been failing intermittently due to timeout
error. The Timeout error is a custom error returned by the trigger
when the end_time value passed to the trigger is greater than the
default timeout value of 3600 seconds set when the cluster creation
is triggered. We want to check why is the end_time condition check
failing for the DAG by checking its set value when the DAG fails.
part of #512
=> Add temporary logs to debug intermittent failures of the Dataproc DAG

astronomer/providers/databricks/operators/databricks.py, tests/databricks/operators/test_databricks.py
A new version of Databricks `apache-airflow-providers-databricks==3.2.0rc3` while running dag it fails due to TypeError: _get_hook() missing 1 required positional argument: 'caller'. The OSS PR link which caused the issue can be found [here](https://github.com/apache/airflow/pull/25115/files#diff-30731826b25d422cb6069898701e34f8ef23b2a32b7782444793a14bc52b0cb1)
So this PR fixes the error by adding the argument caller and also supports backward compatibility for the previous version as well.
Closes #581
=> Fix async databricks job failure due to new airflow provider release

Makefile, dev/README.md
This PR upgrades the docker-compose to use V2 instead of V1. Note that in V2, the `docker-compose` command changed to `docker compose`
cc @kaxil
=> Use docker compose instead of docker-compose

CODE_OF_CONDUCT.md
The pre-Commit hook failed for dead links. Below are the dead links found.
ERROR: 5 dead links found!
[✖] https://www.contributor-covenant.org → Status: 0
[✖] https://www.contributor-covenant.org/version/2/0/code_of_conduct.html → Status: 0
[✖] https://github.com/mozilla/diversity → Status: 0
[✖] https://www.contributor-covenant.org/faq → Status: 0
[✖] https://www.contributor-covenant.org/translations → Status: 0
=> Fix dead links in repo

astronomer/providers/google/cloud/operators/dataproc.py, astronomer/providers/google/cloud/triggers/dataproc.py, tests/google/cloud/triggers/test_dataproc.py
`time.monotonic()` was having a larger time than end time at times. Attaching screenshot for reference
So replacing `time.monotonic()`  with `time.time()`
Closes #512
=> Fix GCP Dataproc DAG failed with timeout error

.circleci/integration-tests/Dockerfile.astro_cloud, .circleci/integration-tests/Dockerfile.gen_1, Makefile
New release 5.0.7 for astro runtime was out on 16th August. Upgrade to the same.
=> Upgrade astro runtime image to latest release 5.0.7

setup.cfg
Databricks was unable to install on python3.10 due to `databricks-sql-connector ` didn't have support for it till 2.0.3 release.
This PR adds the new version of `databricks-sql-connector`  to add support for python3.10.
=> Add support for Python3.10 for Databricks

astronomer/providers/microsoft/azure/operators/data_factory.py, astronomer/providers/microsoft/azure/triggers/data_factory.py, tests/microsoft/azure/triggers/test_data_factory.py
Azure data factory pipeline got succeeded in Azure data factory, it didn't passed inside the while loop in trigger where the condition to get the status of the pipeline is not executed because the condition fails due to the monotonic time is greater in while loop check so we are raising timeout error. so replaced `time.monotonic()`  with `time.time()` and this works as expected. Attached screenshot for success run
=> Fix ADF pipeline timeout issue

dev/docker-compose.yaml
look like `>-` in YAML put a space at the end for multiline string because of that import was failing in dev container for the snowflake extractor 
closes: https://github.com/astronomer/astronomer-providers/issues/606
=> Fix import error for snowflake extractor

astronomer/providers/databricks/hooks/databricks.py, astronomer/providers/databricks/triggers/databricks.py, tests/databricks/hooks/test_databricks.py, tests/databricks/triggers/test_databricks.py
currently, `_do_api_call_async` of databricks does not raise an exception in case of user error instead it returns a Dict because of this the caller of this method might not be aware that the API call was successful or not and the code execution will break in an unexpected way. in this PR I'm modifying this to raise an exception instead of returning Dict. 
https://github.com/astronomer/astronomer-providers/blob/main/astronomer/providers/databricks/hooks/databricks.py#L53
=> Async Databricks Operator: raise exception instead of return in case of user error

astronomer/providers/amazon/aws/extractors/redshift.py, astronomer/providers/amazon/aws/extractors/redshift_data.py, astronomer/providers/amazon/aws/operators/redshift_data.py, astronomer/providers/amazon/aws/operators/redshift_sql.py, dev/docker-compose.yaml, setup.cfg, tests/amazon/aws/extractors/test_redshift.py, tests/amazon/aws/operators/test_redshift_data.py, tests/amazon/aws/operators/test_redshift_sql.py
Export query_ids as XCOM for the Redshift async operators
and add an OpenLineage custom extractor for the same.
Some additional OpenLineage specific environment variables
need to be set which are included as part of the
docker-compose.yaml file change in the commit.
Also adds unit tests for the custom extractor.
Closes #462
=> Implement Open lineage extractor for RedshiftAsync Operators

astronomer/providers/google/cloud/extractors/bigquery.py, astronomer/providers/google/cloud/hooks/bigquery.py, astronomer/providers/google/cloud/operators/bigquery.py, tests/google/cloud/extractors/test_bigquery.py, tests/google/cloud/hooks/test_bigquery.py, tests/google/cloud/operators/test_bigquery.py
This PR addresses the code changes needed to use the OSS BigQueryHook within the repo instead of using a vendored hook
- Remove _BigQueryHook usage
- Change the tests accordingly for the google async hooks and operators
Closes: #52
=> Remove redundant code in BigQueryHookAsync

astronomer/providers/package.py, setup.cfg
This PR is an attempt to add an entry point in the provider so that Airflow can display the astronomer-provider metadata in UI
closes: https://github.com/astronomer/astronomer-providers/issues/610
=> Add provider entry_points for airflow UI

astronomer/providers/package.py
Recently we encounter that the new astro-cloud instances were failing with an error. Here, I'm adding a fallback for the metadata so that server will not crash.
```
File "/usr/local/lib/python3.9/site-packages/astronomer/providers/package.py", line 16, in get_provider_info
"description": config["metadata"]["description"],
File "/usr/local/lib/python3.9/configparser.py", line 963, in __getitem__
raise KeyError(key)
KeyError: 'metadata'
```
=> Add fallback value for config metadata

astronomer/providers/package.py
Look like `description` param in response of `get_provider_info` should be tuple
=> Fix metadata description

astronomer/providers/amazon/aws/triggers/emr.py, astronomer/providers/google/cloud/hooks/dataproc.py, astronomer/providers/google/cloud/triggers/dataproc.py, astronomer/providers/snowflake/hooks/snowflake_sql_api.py, tests/google/cloud/hooks/test_bigquery.py, tests/microsoft/azure/triggers/test_wasb.py
This PR is to resolve flake8 issues where an abstract decorator has to be used if a class is inherited from ABC.
In python, caplog logging has to be set before using it. So the test cases were failing. So now I have set the log level before doing assertion.
=> Fix flake8 failure and failure test cases.

astronomer/providers/apache/hive/example_dags/example_hive.py, astronomer/providers/apache/livy/example_dags/example_livy.py
While running hive or livy dag where we use ssh to login into the machine pem file was missing in /tmp folder.
Now PEM is downloaded into /tmp in SSH task so PEM is available at the same worker node. 
This PR checks whether the file exists or not while copying the pem into /tmp and downloading before SSH into the machine.
If it doesn't exist then it will raise an exception.
closes: #620
=> Add check for PEM exists for Hive and Livy DAG.

astronomer/providers/amazon/aws/xcom_backends/s3.py, docs/conf.py, setup.cfg, tests/amazon/aws/xcom_backends/test_s3.py
Custom XCOM to upload xcom values to the S3 bucket for the given name.
Adding ENV AIRFLOW__CORE__XCOM_BACKEND: astronomer.providers.amazon.aws.xcom_backends.s3.S3XComBackend in the docker-compose.yaml or where the airflow is running will enable the custom XCOM forS3.
closes #559
=> Custom S3 Backend

.circleci/scripts/pre_commit_sync_version_desc_package.py, .pre-commit-config.yaml, astronomer/providers/package.py
There was an attempt to fix it in https://github.com/astronomer/astronomer-providers/pull/635 from @pankajastro  but that file (setup.cfg) won't exist once the package is packaged, hence it will always fallback to an empty value.
This PR/commit fixes it by making `astronomer/providers/package.py` file static and uses  pre-commit hook to sync version and description from setup.cfg to it
**Before**:
=> Fix Provider entrypoint for Airflow

astronomer/providers/amazon/aws/operators/emr.py
- `max_retries` is been deprecated in the latest RC 6.0.0rc1, so fixed for deprecated  value and add backward compatible 
Closes: #676
=> Fix emr_eks_pi_job DAG failing in new RC 6.0.0rc1

CHANGELOG.rst, astronomer/providers/package.py, docs/conf.py, setup.cfg
Update setup.cfg, docs/conf.py and CHANGELOG.rst with the changes pertaining to release 1.10.0
=> Release 1.10.0

astronomer/providers/amazon/aws/operators/emr.py
In the latest  `apache-airflow-providers-amazon-6.0.0`  the `max_tries` attribute is deprecated and that got fixed in the RC image test PR #682, as we discussed fixing mypy issue after the release.
=> Fix mypy issue

astronomer/providers/databricks/hooks/databricks.py, astronomer/providers/databricks/triggers/databricks.py, tests/databricks/hooks/test_databricks.py, tests/databricks/triggers/test_databricks.py
Handled the failure case properly with proper failure message as per in sync version
- In the Jobs API 2.1, we can't call `get_run_output` on the top-level Run ID because it's
not supported by API - we need to call this function on a specific sub-run of the job, even
if it consists of the single task
closes: #643
=> Handle the Databricks Operator failures

Makefile
Currently, we only modify the setup.cfg with the RC providers, build the image, deploy it to Astro Cloud and then trigger the master DAG run. However, we do not check if the RC causes any static check failures like `mypy` or if the tests run fine as we do not run the checks which are only triggered once we create a PR. We come to know of such failures only upon new subsequent PRs. So to detect such failures early, change the `test-rc-deps `make target to create a PR by pushing the setup.cfg to a new branch.
Also, we observed in the past that it takes sometimes ~20 mins for the new image changes to be applied on Astro Cloud and hence we are increasing the wait time to 30 mins before triggering the master DAG run to test the RCs against our DAGs.
closes: #677
=> Modify test RC dependency automation to create a PR

.circleci/integration-tests/script.sh
since now we are building the integration test image  from `quay.io/astronomer/astro-runtime:6.0.2-base` instead of `quay.io/astronomer/astro-runtime:6.0.2` so  `packages.txt` and `requirements.txt` no longer require
=> Remove unused files from integration tests image

astronomer/providers/databricks/operators/databricks.py
Add Doc string for the Databricks async operators
=> Add doc string for `DatabricksSubmitRunOperatorAsync` and `DatabricksRunNowOperatorAsync`

.circleci/integration-tests/master_dag.py
=> Enable `GKEStartPodOperatorAsync` in integration tests

.circleci/integration-tests/Dockerfile.astro_cloud, Makefile
The new release 6.0.3 for Astro runtime was out on 24th October. Upgrade to the same.
=> Bump astro-runtime to 6.0.3

astronomer/providers/amazon/aws/hooks/base_aws.py, tests/amazon/aws/hooks/test_s3_hooks.py
when AWS secrete and access key is passed via the connection UI field the session token is not considered, when it is passed via extra config it is considered
closes: #725
=> Fix session token from extra config

astronomer/providers/package.py, docs/conf.py, setup.cfg
Since 1.11.1 is released with a bug fix, so bumped up this version to `1.12.0.dev1`
=> Bump version to 1.12.0.dev1

astronomer/providers/google/cloud/hooks/bigquery.py, tests/google/cloud/hooks/test_bigquery.py, tests/google/cloud/triggers/test_bigquery.py
closes: https://github.com/astronomer/astronomer-providers/issues/743
The Bigquery hook get_records always return a list of string irrespective of the Bigquery table column type. So if even my table column has value 0 the task succeeds since bool("0") returns True.
This PR fixes it by typecasting the column value using `_bq_cast`
=> Typecast bigquery job response col value

astronomer/providers/amazon/aws/hooks/redshift_data.py, tests/amazon/aws/hooks/test_redshift_data.py
- Consider access and secret key if it is passed in connection login and password field
- Consider AWS session token if it is passed in `extra_config`
closes: #741
=> Fix `redshift_data` hook to consider access and secret key from the connections object not from extra

astronomer/providers/sftp/hooks/sftp.py, astronomer/providers/sftp/sensors/sftp.py, astronomer/providers/sftp/triggers/sftp.py, tests/sftp/hooks/test_sftp.py, tests/sftp/triggers/test_sftp.py
- Handled SFTP async operator when file pattern is not passed
- Added `newer_than` attribute corresponding to Sync operators and code changes for the same.
- Added test case for the code changes
closes: #707
=> Handle `SFTPSensorAsync` when file pattern is not passed

.circleci/integration-tests/Dockerfile.astro_cloud, Makefile
The new release 6.0.4 for Astro runtime was out on 14th November. Upgrade to the same.
=> Bump astro-runtime to 6.0.4

astronomer/providers/google/cloud/hooks/bigquery.py
Use bigquery hook bq_cast since _bq_cast was a private to the repo and would be removed in the upcoming google provider release i.e (apache-airflow-providers-google > 8.4.0) https://github.com/apache/airflow/pull/27543
=> Use bigquery hook bq_cast 

astronomer/providers/amazon/aws/operators/redshift_sql.py, astronomer/providers/snowflake/operators/snowflake.py
SnowflakeOperatorAsync, SnowflakeSqlApiOperatorAsync and RedshiftSQLOperatorAsync Operator failed due to new RC version changes `apache-airflow-providers-amazon==6.1.0rc1` and `apache-airflow-providers-snowflake==4.0.0rc1` the sync version of those operators started inherited from SQLExecuteQueryOperator  which doesn't have `snowflake_conn_id`  and `redshift_conn_id`. This issue is fixed by with backward compatibility
=> Fix Bug in SnowflakeOperatorAsync and RedshiftSQLOperatorAsync 

astronomer/providers/snowflake/operators/snowflake.py
There was an issue `SnowflakeOperatorAsync` with the auto-commit option which was set to false by default in `SQLExecuteQueryOperator` the latest `apache-airflow-providers-snowflake==4.0.0rc1` was inherited from the `SQLExecuteQueryOperator` so now it is set to True by default in `SnowflakeOperatorAsync`
=> Set auto commit to true by default in SnowflakeOperatorAsync

astronomer/providers/snowflake/hooks/snowflake.py, astronomer/providers/snowflake/operators/snowflake.py
Adding auto-commit to true in the hook where we are connecting to the snowflake and running the queries.
=> Add autocommit = True in `SnowflakeHookAsync`

astronomer/providers/amazon/aws/hooks/base_aws.py
Used `AwsConnectionWrapper` for getting the connection params which we don't need to cover the details from our end, it will cover all the missing params passed in the AWS connections. This will also cover removing the redundant. 
Closes: #732
=> Remove redundant connection params from `AwsBaseHookAsync`

docs/providers/microsoft/index.rst
Fix the broken readthedoc https://astronomer-providers.readthedocs.io/en/stable/providers/microsoft/azure/Sensors/data_factory.html
Before
After
closes: https://github.com/astronomer/astronomer-providers/issues/778
=> Fix ADF broken docs

Makefile
Add `'DO NOT MERGE'` prefix to PRs created from RC test make target so that
we do not merge the PR mistakenly.
=> Add 'DO NOT MERGE' prefix for RC test PRs

astronomer/providers/amazon/aws/sensors/s3.py, astronomer/providers/amazon/aws/triggers/s3.py, tests/amazon/aws/triggers/test_s3_triggers.py
Added `poke_interval` for the S3KeyTrigger. Adding poke_interval makes the trigger sleep for seconds to avoid the trigger process becoming overwhelmed when sensing a large number of files in s3.
closes: #750
=> Added poke interval for the S3KeyTrigger

astronomer/providers/google/cloud/xcom_backends/gcs.py, tests/google/cloud/xcom_backends/test_gcs.py
Custom XCOM to upload xcom values to the GCS bucket for the given name.
Adding ENV ` AIRFLOW__CORE__XCOM_BACKEND: astronomer.providers.google.cloud.xcom_backends.gcs.GCSXComBackend` in the `docker-compose.yaml` or where the airflow is running will enable the custom XCOM for GCS.
closes #596
=> Custom XCom GCS

astronomer/providers/snowflake/hooks/snowflake.py, astronomer/providers/snowflake/operators/snowflake.py, tests/snowflake/hooks/test_snowflake.py, tests/snowflake/operators/test_snowflake.py
Return an XCom of results in SnowflakeOperatorAsync as same as the sync version SnowflakeOperator
closes: https://github.com/astronomer/astronomer-providers/issues/714
=> Fix `SnowflakeOperatorAsync` XCom value to return

astronomer/providers/http/sensors/http.py
Update the docstrings for HttpSensorAsync as discussed in https://astronomer.slack.com/archives/C0387PMM2E7/p1665393838125069..
closes #706
=> Correct docstrings for `HttpSensorAsync`

astronomer/providers/snowflake/example_dags/example_snowflake.py, astronomer/providers/snowflake/operators/snowflake.py
Passed the `return_last` parameter to hook `check_query_output` which is now the operator params, this param helps the user to return the result of only the last statement output or all statement output. By default, it is set to `True`, which will return the last value in case of multiple query execution.
=> Fix return value of snowflakeOperatorAsync

.circleci/integration-tests/master_dag.py, astronomer/providers/google/cloud/example_dags/example_bigquery_impersonation_chain.py, astronomer/providers/google/cloud/example_dags/example_bigquery_impersonation_key.py, astronomer/providers/google/cloud/example_dags/example_dataproc_impersonation.py, astronomer/providers/google/cloud/hooks/bigquery.py, astronomer/providers/google/cloud/operators/bigquery.py, astronomer/providers/google/cloud/operators/dataproc.py, astronomer/providers/google/cloud/triggers/bigquery.py, astronomer/providers/google/cloud/triggers/dataproc.py, tests/google/cloud/triggers/test_bigquery.py, tests/google/cloud/triggers/test_dataproc.py
Google operators ignore authentication parameters `impersonation_chain` which supports connecting with google cloud API without any authentication key by using impersonation chain authentication. These parameters are supported by their sync version operators, So now made a fix to the async Operators to support `impersonation_chain` and `delegate_to` other type authentication params.
Closes: #651
=> Allow Async Google Operators to accept `impersonation_chain` and `delegate_to` parameters for authentication

README.rst
currently, the license docs link is broken in the readtheodcs https://astronomer-providers.readthedocs.io/en/stable/ https://astronomer-providers.readthedocs.io/en/stable/LICENSE . Here, I'm updating the relative path with the full GitHub path
=> Fix license broken link in readthedocs

.circleci/integration-tests/master_dag.py, astronomer/providers/sftp/example_dags/example_sftp.py, astronomer/providers/sftp/hooks/sftp.py, tests/sftp/hooks/test_sftp.py
Added the `SFTPSensorAsync`  example DAG into the master DAG, created the connection details via code and other details needed for the DAG to run as a self-sufficient
closes: #662  #760
=> Run `SFTPSensorAsync` in integrations tests and add support for private key connection

astronomer/providers/amazon/aws/hooks/base_aws.py, tests/amazon/aws/hooks/test_s3_hooks.py
Previously `aiobotocore` doesn't support assume role with `role_arn`. Now added support for assuming role option in `AwsBaseHookAsync`
closes: #786
=> Support assume role for AWS base async hook

astronomer/providers/cncf/kubernetes/operators/kubernetes_pod.py
`kube_config_path` or `kube_config` (JSON) from Kubernetes connection was not consider in `KubernetesPodOperatorAsync`. Because the connection id is set to None in the trigger, So now it is fixed to consider the Kubernetes connection id and details in trigger.
closes: #745
=> Fix ``KubernetesPodOperatorAsync`` to consider kubernetes connection id and details in trigger

astronomer/providers/core/sensors/external_task.py
I've recently started onboarding as the astronomer provider async sensors, I'm really appreciative you've made these available publicly!
One thing I noticed is that the FileSensorAsync supports poke_interval but the ExternalTaskSensorAsync does not and runs as a fixed 5 seconds. While this isn't an issue at the moment as we only run a few external task sensors as we scale up I wouldn't want 100s running every 5 seconds.
I notice that both DagStateTrigger and TaskStateTrigger support poll_interval.
closes #817
=> ExternalTaskSensorAsync to support poke_interval

astronomer/providers/amazon/aws/xcom_backends/s3.py, tests/amazon/aws/xcom_backends/test_s3.py
Custom XCOM to upload xcom values to the S3 bucket for the given name.
Adding ENV  `AIRFLOW__CORE__XCOM_BACKEND: astronomer.providers.amazon.aws.xcom_backends.s3.S3XComBackend` in the docker-compose.yaml or where the airflow is running will enable the custom XCOM for S3.
closes #795
=> Custom backend XCom S3

astronomer/providers/cncf/kubernetes/triggers/wait_container.py, astronomer/providers/google/cloud/operators/kubernetes_engine.py, astronomer/providers/google/cloud/triggers/kubernetes_engine.py, tests/cncf/kubernetes/triggers/test_wait_container.py, tests/google/cloud/operators/test_kubernetes_engine.py, tests/google/cloud/triggers/test_kubernetes_engine.py
- Fix  Issue: #811 not showing pod's logs on completion if `get_logs` is True
Currently in `GKEStartPodOperatorAsync`, even though the `get_logs` attribute is set to True it was not showing the pod's log as in sync operator as expected, now it is fixed extended support to conclude the `get_logs` attribute once the trigger callback function is executed fetching the container logs from the pod manager if `get_logs` attribute is set to True.
- Fix  Issue #451  pod cleanup and XCom push
Once the trigger callback function is executed after the successful event. Pushed `pod name` and `namespace` and result in XCom when `do_xcom_push`  is set to True and cleaning of the pod was also handled.
- Handle the `GKEStartPodOperatorAsync` status based on the terminal status. #814
Currently, …
=> Fix `get_logs`, `pod cleanup` and `XCom push` in ``GKEStartPodOperatorAsync``

astronomer/providers/google/cloud/operators/dataproc.py, tests/google/cloud/operators/test_dataproc.py
This PR enables the user to see Dataproc resource button when we run a job using ``DataprocSubmitJobOperatorAsync``.
closes #825
=> Add `DataprocLink` to see Dataproc jobs  in `DataprocSubmitJobOperatorAsync`

astronomer/providers/amazon/aws/operators/emr.py
currently, in operator, we have `tags` param but we do not pass it in boto api
closes: https://github.com/astronomer/astronomer-providers/issues/430
=> Use tags param in `EmrContainerOperatorAsync`

tests/databricks/hooks/test_databricks.py, tests/databricks/operators/test_databricks.py, tests/databricks/triggers/test_databricks.py
closes: https://github.com/astronomer/astronomer-providers/issues/693
- convert the function-based test to a class-based
- remove context fixture definition from operator/sensor/extractor and reuse from conftest
- remove function create_context from a couple of test files and reuse it from the util
- remove duplicate code for initializing op/senor/trigger/hook at possible places
=> Databricks class based tests

.circleci/integration-tests/Dockerfile.astro_cloud, dev/Dockerfile.google_cloud
With kubectl v1.26, the auth mechanism has been altered and now it needs the gke-gcloud-auth-plugin for authentication to succeed. Install the same in the docker image getting built to be run in CI.
closes: #842
=> Install gke-gcloud-auth-plugin to fix auth failures

tests/snowflake/extractors/test_snowflake.py, tests/snowflake/hooks/test_snowflake_sql_api.py, tests/snowflake/hooks/test_sql_api_generate_jwt.py, tests/snowflake/operators/test_snowflake.py, tests/snowflake/triggers/test_snowflake.py
closes: https://github.com/astronomer/astronomer-providers/issues/697
convert the function-based test to a class-based
remove context fixture definition from operator/sensor/extractor and reuse from conftest
remove function create_context from a couple of test files and reuse it from the util
remove duplicate code for initializing op/senor/trigger/hook at possible places
=> Snowflake class based tests

astronomer/providers/snowflake/hooks/snowflake.py, tests/snowflake/hooks/test_snowflake.py
closes: https://github.com/astronomer/astronomer-providers/issues/433
=> Snowflake handle empty sql list

tests/microsoft/azure/hooks/test_data_factory.py, tests/microsoft/azure/hooks/test_wasb.py, tests/microsoft/azure/operators/test_data_factory.py, tests/microsoft/azure/sensors/test_data_factory.py, tests/microsoft/azure/sensors/test_wasb.py, tests/microsoft/azure/triggers/test_data_factory.py, tests/microsoft/azure/triggers/test_wasb.py
google class-based tests
closes: https://github.com/astronomer/astronomer-providers/issues/696
convert the function-based test to a class-based
remove context fixture definition from operator/sensor/extractor and reuse from conftest
remove function create_context from a couple of test files and reuse it from the util
remove duplicate code for initializing op/senor/trigger/hook at possible places
=> Add microsoft class based tests

tests/google/cloud/extractors/test_bigquery.py, tests/google/cloud/hooks/test_bigquery.py, tests/google/cloud/hooks/test_dataproc.py, tests/google/cloud/hooks/test_gcs.py, tests/google/cloud/operators/test_bigquery.py, tests/google/cloud/operators/test_dataproc.py, tests/google/cloud/operators/test_kubernetes_engine.py, tests/google/cloud/sensors/test_bigquery.py, tests/google/cloud/sensors/test_gcs.py, tests/google/cloud/triggers/test_bigquery.py, tests/google/cloud/triggers/test_dataproc.py, tests/google/cloud/triggers/test_gcs.py, tests/google/cloud/triggers/test_kubernetes_engine.py, tests/google/cloud/xcom_backends/test_gcs.py, tests/utils/airflow_util.py
google class-based tests
closes: https://github.com/astronomer/astronomer-providers/issues/694
- convert the function-based test to a class-based
- remove context fixture definition from operator/sensor/extractor and reuse from conftest
- remove function create_context from a couple of test files and reuse it from the util
- remove duplicate code for initializing op/senor/trigger/hook at possible places
=> google class based tests

astronomer/providers/dbt/cloud/hooks/dbt.py, tests/dbt/cloud/hooks/test_dbt_hooks.py
Related: https://github.com/apache/airflow/issues/27146 https://github.com/apache/airflow/pull/28890
In OSS Airflow, the dbt Cloud connection has replaced `schema` for `host` to provide the "tenant" name. This fix was included in the latest version of the dbt Cloud provider (2.3.1) and should also be reflected in this provider.
=> Use entire tenant domain name in dbt Cloud connection

astronomer/providers/core/sensors/external_task.py
When an external task id is given `ExternalTaskSensor` is using `execution_timeout`  instead of `timeout` from `BaseSensorOperator`.
closes #857
=> Use  `timeout` instead of `execution_timeout` with `ExternalTaskSensor` when sensing task_id

setup.cfg
pin mypy version <1.0.0. 
Mypy-1.0.0 is crashing look similar to https://github.com/python/mypy/issues/14631
```
mypy 1.0.0
(compiled:
yes)
Traceback (most recent call last):
File "/home/circleci/.pyenv/versions/3.9.16/bin/mypy", line 8, in <module>
sys.exit(console_entry())
File "/home/circleci/.pyenv/versions/3.9.16/lib/python3.9/site-packages/mypy/__main__.py", line 15, in console_entry
main()
File "mypy/main.py", line 95, in main
File "mypy/main.py", line 174, in run_build
File "mypy/build.py", line 194, in build
File "mypy/build.py", line 277, in _build
File "mypy/build.py", line 2923, in dispatch
File "mypy/build.py", line 3320, in process_graph
File "mypy/build.py", line 3443, in process_stale_scc
File "mypy/build.py", line 2504, in write_cache
File "mypy/build.py", line 1574, in …
```
=> pin mypy version <1.0.0

astronomer/providers/google/cloud/example_dags/example_bigquery_impersonation_chain.py
Delegate_to param id is deprecated. Since it would need project-level domain-wide delegation enabled, we can remove its usage and let alone use the impersonation chain param.
closes: #886
=> Remove usage of deprecated param delegate_to

astronomer/providers/microsoft/azure/hooks/data_factory.py, astronomer/providers/microsoft/azure/hooks/wasb.py, tests/microsoft/azure/hooks/test_data_factory.py
With the 5.0.0 release of the Microsoft Azure PR, the PR https://github.com/apache/airflow/pull/27047 introduced a breaking change where while creating new connections, the ``extra__`` prefix is no longer set for extra fields in the conneciton. This issue was not identified with testing the 5.0.0 RC because, it only happens for new connections that are created. The existing connections still contain the extra fiels with the ``extra__`` prefix. Hence, the existing code which looks for the connection field with the prefix ``extra__azure_data_factory__subscriptionId`` works on the older deployment with the new provider release as the connection was created before the release, but it fails on new deployments when a fresh connection is created.
To fix this, we're removing the prefix while …
=> Support retriveing extra fields which do not have extra prefix set - Azure ADF DAG failure

astronomer/providers/microsoft/azure/hooks/data_factory.py, tests/microsoft/azure/hooks/test_data_factory.py
PR #899 introduced an import for method ``get_field`` and started its usage. However, as reviewed and suggested by @ashb this will fail on providers with version < 5.0.0 as it was only the release 5.0.0 which included the ``get_field`` method. To solve this, we remove the dependency on the imported method and introduce the same method in local module.
=> Fix get_field import availability - PR #899 followup

astronomer/providers/sftp/hooks/sftp.py, astronomer/providers/sftp/triggers/sftp.py, tests/sftp/hooks/test_sftp.py, tests/sftp/triggers/test_sftp.py
When we use file_pattern and newer_than in SFTPSensorAsync to find only the files that landed in SFTP after the data interval of the prior successful DAG run ({{ prev_data_interval_end_success  }}).
I have four text files (file.txt, file1.txt, file2.txt and file3.txt) but only file3.txt has the last modification date after the data interval of the prior successful DAG run. I use the following file pattern: "*.txt".
The moment the first file (file.txt) was matched and the modification date did not meet the requirement.
The other files matching the pattern should be checked as well.
closes #903 
closes #904
=> SFTPSensorAsync using newer_than doesn't work well with file_pattern

.circleci/integration-tests/master_dag.py, astronomer/providers/snowflake/hooks/snowflake.py
Fix mypy issues on main and  currently, the `example_snowflake_sensor` dag was not included as part of the master dag and this dag was not running on astro cloud. 
This PR adds the `example_snowflake_sensor` into master_dag.
=> Fix mypy and add snowflake sensor dag to master dag

astronomer/providers/amazon/aws/operators/sagemaker.py, tests/amazon/aws/operators/test_sagemaker.py
With the new RC release, the test cases were failing and dag was failing due to https://app.circleci.com/pipelines/github/astronomer/astronomer-providers/4127/workflows/1c8507c3-d802-46fc-9c1f-49c7fd9cc37e/jobs/19074,
This PR makes sagemaker operator compatible with an older and newer versions also.
=> Make amazon sagemaker async operators compatible with new amazon provider

astronomer/providers/core/sensors/external_task.py, astronomer/providers/snowflake/sensors/snowflake.py, tests/snowflake/sensors/test_snowflake.py
Based on internal discussion to mitigate race condition on deferrable sensor immediately getting successful, made the changes to the sensors to check on the worker first, then defer if the condition is not met.
- SnowflakeSensorAsync refactored to inherit from `SqlSensor` and rewrote the test
- ExternalTaskSensorAsync
- ExternalDeploymentTaskSensorAsync
=> Update ExternalTaskSensorAsync and SnowflakeSensorAsync to check on worker first

astronomer/providers/amazon/aws/triggers/s3.py
When check_fn = None, i see in logs two TriggerEvent - one with success status and another with error status:
```
[2023-03-07 13:32:30,215] {triggerer_job.py:362} INFO - Trigger <astronomer.providers.amazon.aws.triggers.s3.S3KeyTrigger bucket_name=None, bucket_key=['s3://my_path/_SUCCESS'], wildcard_match=False, check_fn=None, aws_conn_id=aws_default, hook_params={'hook_params': {'verify': None}}, poke_interval=60> (ID 1086) fired: TriggerEvent<{'status': 'success'}>
[2023-03-07 13:32:30,222] {triggerer_job.py:362} INFO - Trigger <astronomer.providers.amazon.aws.triggers.s3.S3KeyTrigger bucket_name=None, bucket_key=['s3://my_path/_SUCCESS'], wildcard_match=False, check_fn=None, aws_conn_id=aws_default, hook_params={'hook_params': {'verify': None}}, poke_interval=60> (ID 1086) fired: …
```
=> S3KeyTrigger yields two trigger events when check_fn is none.

.circleci/integration-tests/Dockerfile.astro_cloud
In integration test docker file we use `RUN pip install /tmp/astronomer-providers[all] ` to install astronomer-provider which uses cache and because of that it does not install latest version of dependent apache airflow provider. In this PR I'm making changes to install latest version and not use cache. 
cons: increase deployment time
pros: run against latest provider so we can use improvement
=> Install new version of dependencies in Integration tests

astronomer/providers/amazon/aws/example_dags/example_redshift_cluster_management.py
Currently, when the dag was running by default max attempt was 5 and the interval period is 60 default. it will check for 5 mins and error out if the cluster is not brought up by then with the below error.
but in the subsequent retry when it tries to bring up the cluster and throws an error saying ClusterAlreadyExists error.
So this PR adds a max attempt of 30 which waits for a maximum of 30 mins to cluster to bring up.
=> Add max attempts to Redshift Cluster dag to wait

astronomer/providers/amazon/aws/hooks/redshift_cluster.py, tests/amazon/aws/hooks/test_redshift_cluster.py
currently, if cluster not exist and we try to use redshift delete cluster then https://github.com/astronomer/astronomer-providers/blob/46864035c106999446816e3b86316a85d642dd43/astronomer/providers/amazon/aws/hooks/redshift_cluster.py#L57-L61 throw exception and task fail but I think should pass
=> Fix redshift delete cluster when cluster not exist

astronomer/providers/cncf/kubernetes/hooks/kubernetes.py, tests/cncf/kubernetes/hooks/test_kubernetes.py
the extra__ prefix is no longer set for extra fields in the connection.
it only happens for new connections that are created. The existing connections still contain the extra fields with the extra__ prefix. Hence, the existing code looks for the connection field with the prefix.
To fix this, we're removing the prefix while retrieving the connection field and at the same time we're supporting previously created connections by using the same get_field method from Airflow OSS introduced in the same PR above to allow backward compatibility.
closes #938
=> Support retrieving extra fields which do not have extra prefix set

.circleci/integration-tests/master_dag.py, .pre-commit-config.yaml
The `master_dag` has implemented chaining of DAGs by grouping them based on providers. However, if one of the DAG fails in the chain, subsequent DAGs are not run and hence we do not test them. As such, the DAGs do not need to depend on each other and hence we can set the `trigger_rule` in the `TriggerDagRunOperator` to `all_done` so that we test all the DAGs irrespective of whether the previous DAG in the chain succeeded.
closes: #949
=> Set TriggerDagRunOperator's trigger_rule to all_done in master_dag

astronomer/providers/google/cloud/__init__.py, astronomer/providers/google/cloud/operators/kubernetes_engine.py, astronomer/providers/google/cloud/triggers/kubernetes_engine.py, tests/google/cloud/operators/test_kubernetes_engine.py, tests/google/cloud/triggers/test_kubernetes_engine.py
Contradicted to the previous discussion with @pankajkoti . I dig into the code on both sides a bit. It seems to me that adding the removed function back makes more sense.
1. GKEStartPodOperatorAsync is not inherited from GKEStartPodOperator. They’re different operators from the beginning. If we’re to copy the logic from GKEStartPodOperator, it might make more sense for us to remove  GKEStartPodOperatorAsync  as GKEStartPodOperator now supports deferrable as well.
2. get_gke_config_file can be used alone and doesn’t necessary need to tide to a class which might make sense to make it a utility function
closes #947
=> fix(google): add back removed utility function get_gke_config_file

astronomer/providers/amazon/aws/example_dags/example_redshift_cluster_management.py
Currently, the RedshiftCreateClusterSnapshotOperator takes on avg of 4 mins to create the snapshot but sometimes it crosses 5 mins.  the default values in operator is for 15secs poll interval and 20 max_attempts and it fails with 
`botocore.exceptions.WaiterError: Waiter SnapshotAvailable failed: Max attempts exceeded`.
This PR increases the max attempt for the waiting of this operator to create the snapshot
=> Increase `RedshiftCreateClusterSnapshotOperator` max attempt to wait for snapshot creation.

astronomer/providers/amazon/aws/xcom_backends/s3.py, astronomer/providers/google/cloud/xcom_backends/gcs.py, dev/docker-compose.yaml, tests/amazon/aws/xcom_backends/test_s3.py, tests/google/cloud/xcom_backends/test_gcs.py
The downloaded file content from AWS and Google hook return bytes instance which the pandas read_json cannot read; hence, we fix this by converting it to BytesIO instance which the pandas read_json method reads well.
closes: #955
=> Fix read of Pandas json for S3 and GCS custom XCOM backend

setup.cfg
As discussed in #958, we might need to pin snowflake-sqlalchemy >= 1.4.4 to resolved the issue. For the next step, I'm thinking of sending a PR to pin it to >= 1.4.4 on `apache-airflow-providers-snowflake` and then pin the `apache-airflow-providers-snowflake` in this repo after it's released
=> build(setup.cfg): pinning snowflake-sqlalchemy to greater than or eqaul to 1.4.4

astronomer/providers/google/cloud/operators/bigquery.py
Bigquery operator backward compatibility
currently, the task fails if we have astronomer provider 1.15.3 and apache-airflow-providers-google < 8.11.0
Add init in affected operators and if `poll_interval` is pass by user then use it otherwise use default trigger poll_interval
with new google provider
with a old google provider
closes: https://github.com/astronomer/astronomer-providers/issues/966
=> Bigquery operator backward compatibility

astronomer/providers/amazon/aws/operators/sagemaker.py, tests/amazon/aws/operators/test_sagemaker.py
The `find_processing_job_by_name` method on the Sagemaker hook has been replaced with `count_processing_jobs_by_name` and hence make the necessary changes for the release ensuring backward compatibility for the older versions of the provider.
related to: #977
=> Fix sagemaker operator for Amazon provider release 8.0.0

astronomer/providers/google/cloud/operators/bigquery.py, astronomer/providers/google/cloud/sensors/bigquery.py, astronomer/providers/google/cloud/sensors/gcs.py
The delegate_to parameter has been removed in the release 10.0.0; the commit makes sure to integrate that change while ensuring that the backward compatibility is maintained for older versions of the provider.
related to: #977
=> Fix bigquery & gcs operators & sensors for Google provider 10.0.0

.circleci/integration-tests/master_dag.py
This PR adds the executor info in the integration test report so that we can use it to identify the test report when we start running tests on Kubernetes Executor in Astro
=> add executor info in the integration test report

.circleci/integration-tests/Dockerfile.astro_cloud
We recently deployed 8.0.0-alpha1 to our provider-integartion-tests deployment. The current nightly job tries to deploy 7.4.2 image, but it fails as Astro does not allow to downgrade the runtime image for a deployment. So, until the stable runtime image is out, let's deploy the alpha-1 image so that we ensure there are no failures as there are multiple provider releases in short span of time.
=> Use runtime image 8.0.0-alpha1 so that nightly job succeeds

.circleci/integration-tests/Dockerfile.astro_cloud, Makefile
Apache Airflow 2.6.0 has been released and a corresponding astro runtime image 8.0.0 is available now, so upgrade to it.
=> Upgrade astro runtime image to 8.0.0

Makefile, RELEASING.rst
Add a make target to bump the version locally.
example
```
make ASTRO_PROVIDER_VERSION=dev bump-version  // this will set the version to next minor-version-dev1 example 1.1.0-dev1
make ASTRO_PROVIDER_VERSION=1.1.1 bump-version
make ASTRO_PROVIDER_VERSION=1.1.0 bump-version 
make ASTRO_PROVIDER_VERSION=1.0.0 bump-version
```
=> Add a make target to bump version

astronomer/providers/dbt/cloud/sensors/dbt.py, tests/dbt/cloud/sensors/test_dbt.py
Similar to SnowflakeOperatorAsync, we want to check whether the task has finished before it's deferred. For most sensors, we have a poke method in its sync counter part which can help us do such check.
=> feat(dbt): check state before deferring DbtCloudJobRunSensorAsync

astronomer/providers/apache/livy/operators/livy.py, tests/apache/livy/operators/test_livy.py, tests/snowflake/operators/test_snowflake.py
Similar to [SnowflakeOperatorAsync](https://github.com/astronomer/astronomer-providers/blob/b2dade827ad8425952b2f5313b6a2863cb0c3e5e/astronomer/providers/snowflake/operators/snowflake.py#L217), we want to check whether the task has finished before it's deferred which can avoid unnecessarily deferring the task to the trigger. For most sensors, we have a poke method in its sync counterpart which can help us do such check
Closes: #995
=> feat(livy): check state before deferring LivyOperatorAsync

astronomer/providers/microsoft/azure/sensors/data_factory.py, tests/microsoft/azure/sensors/test_data_factory.py
=> Check whether the pipeline finishes before deferring the task for AzureDataFactoryPipelineRunStatusSensorAsync

astronomer/providers/google/cloud/sensors/gcs.py, tests/google/cloud/sensors/test_gcs.py
=> Check whether the task finishes before deferring the task for GCSObjectUpdateSensorAsync

astronomer/providers/google/cloud/sensors/gcs.py, tests/google/cloud/sensors/test_gcs.py
=> Check whether the upload completes before deferring the task for GCSUploadSessionCompleteSensorAsync

astronomer/providers/google/cloud/sensors/gcs.py, tests/google/cloud/sensors/test_gcs.py
=> Check whether the object exists before deferring the task for GCSObjectsWithPrefixExistenceSensorAsync

astronomer/providers/google/cloud/sensors/gcs.py, tests/google/cloud/sensors/test_gcs.py
Just like the [SnowflakeOperatorAsync](https://github.com/astronomer/astronomer-providers/blob/b2dade827ad8425952b2f5313b6a2863cb0c3e5e/astronomer/providers/snowflake/operators/snowflake.py#L217), we need to verify if the task has already completed before deferring it to prevent unnecessary deferring. This way, we can skip deferring the task if it has already been finished. To accomplish this, we can make use of the poke method found in the sync counterpart of most sensors.
=> Check whether the object already exists before deferring the task for GCSObjectExistenceSensorAsync

astronomer/providers/google/cloud/sensors/bigquery.py, tests/google/cloud/sensors/test_bigquery.py
Similar to [SnowflakeOperatorAsync](https://github.com/astronomer/astronomer-providers/blob/b2dade827ad8425952b2f5313b6a2863cb0c3e5e/astronomer/providers/snowflake/operators/snowflake.py#L217), we want to check whether the task has finished before it's deferred. For most sensors, we have a poke method in its sync counter part which can help us do such check.
=> Check whether table exists before deferring the task for BigQueryTableExistenceSensorAsync

astronomer/providers/amazon/aws/example_dags/example_redshift_cluster_management.py
Previously, the max_attempts was set to 40 and the poll interval is 15 seconds.
However, it looks like this duration of 40 * 15=600 seconds(10 mins) is not enough
at times as it takes longer for snapshot creation and the task fails. Hence, we're
increasing the max_attempts to 100, meaning we will wait for
100 * 15=1500seconds(25 mins) now.
=> Increase snapshot creation max_attempts to 100

astronomer/providers/amazon/aws/sensors/batch.py, tests/amazon/aws/sensors/test_batch_sensors.py
=> Check whether the job reaches a failure or a success state before deferring the task for BatchSensorAsync

astronomer/providers/amazon/aws/example_dags/example_aws_nuke.py
With the change in PR #1019, we set the schedule of nuke DAG to none as it runs from the master DAG now. However, there are some abnomalities in the KubernetesExecutor deployment and also the nuke DAG does not run there. As a result resources are not cleaned up post the master DAG run in KubernetesExecutor (which runs after the master DAG in CeleryExecutor). As a result, on next day, DAGs in CeleryExecutor deployment also fail due to resouce already exists error. Hence, for the time being until KubernetesExecutor deployment is all well, we would like to renable the Nuke DAG to run daily at 20:30 Hrs.
=> Schedule daily run of AWS nuke DAG temporarily

astronomer/providers/amazon/aws/sensors/redshift_cluster.py, tests/amazon/aws/sensors/test_redshift_sensor.py
=> Check whether the task finishes before deferring the task for RedshiftClusterSensorAsync

astronomer/providers/amazon/aws/sensors/emr.py, tests/amazon/aws/sensors/test_emr_sensors.py
=> Check whether the task finishes before deferring the task for EmrStepSensorAsync

astronomer/providers/amazon/aws/example_dags/example_aws_nuke.py
It is observed on KubernetesExecutor deployment that the AWS Nuke DAG fails
with permission issues that it cannot assume an AWS role to perform operations
in our AWS account. The preliminary guess is that since we run authentication
and nuke commands in separate operators, they get launched in separate pods
and hence the authentication/authorization is missing the second pod which triggers
the nuke. This PR combines the two operators in a single operator so that the Nuke
DAG runs fine on our KubernetesExecutor deployment
=> Combine aws configure with aws nuke in single operator

astronomer/providers/apache/livy/example_dags/example_livy.py
the correct top-level view of statuses of the DAGs triggered from the master DAG.
fail.
closes: #1001
=> Mark Livy DAG failed if any of the tasks fail

.circleci/integration-tests/nuke-config.yml
Nukes SageMaker models left undeleted.
closes: #1055
=> Nuke SageMaker model as part of AWS nuke DAG

astronomer/providers/amazon/aws/example_dags/example_emr_sensor.py
=> Mark EMR Sensor DAG failed if any of the tasks fail

astronomer/providers/amazon/aws/example_dags/example_aws_nuke.py
This reverts commit 0f8635742f9171427ea482945fddcbdc1372a604.
Since, we have AWS nuke DAG working on KE deployment now, we can disable scheduled runs of the AWS nuke DAG now.
=> Revert "Schedule daily run of AWS nuke DAG temporarily (#1040)"

astronomer/providers/amazon/aws/hooks/s3.py, astronomer/providers/amazon/aws/sensors/s3.py, tests/amazon/aws/hooks/test_s3_hooks.py, tests/amazon/aws/sensors/test_s3_sensors.py
=> Check whether the task finishes before deferring the task for S3KeysUnchangedSensorAsync

astronomer/providers/google/cloud/operators/bigquery.py, tests/google/cloud/operators/test_bigquery.py
=> Check whether the task finishes before deferring the task for BigQueryCheckOperatorAsync

astronomer/providers/google/cloud/operators/bigquery.py, tests/google/cloud/operators/test_bigquery.py
Like the [SnowflakeOperatorAsync](https://github.com/astronomer/astronomer-providers/blob/b2dade827ad8425952b2f5313b6a2863cb0c3e5e/astronomer/providers/snowflake/operators/snowflake.py#L217), we try to verify if the submitted job has already completed before deferring it to prevent unnecessary deferring. This way, we can skip deferring the task if it has already been finished. 
Same as #1041 (I accidentally delete the branch)
=>  Check whether the job finishes before deferring the task for BigQueryInsertJobOperatorAsync

astronomer/providers/microsoft/azure/operators/data_factory.py, tests/microsoft/azure/operators/test_data_factory.py
=> Check whether the job finishes before deferring the task for AzureDataFactoryRunPipelineOperatorAsync

dev/docker-compose.yaml
We do not have extractors for all the operators that we have in this repo.
As a result, when building the setup locally using docker-compose.yml and
running the DAGs we keep on getting Extractor logs not found in the task 
logs which deviates us from finding the right logs.
With this change, we are disabling setting the openlineage specific envrionment
variables, so that we have clean task logs.
=> Disable openlineage for local build of providers

.circleci/integration-tests/Dockerfile.astro_cloud
Test Airflow 2.6.0RC1 by using the corresponding runtime image
=> Upgrade runtime image 8.2.0 alpha1

astronomer/providers/google/cloud/operators/dataproc.py, tests/google/cloud/operators/test_dataproc.py
Like the [SnowflakeOperatorAsync](https://github.com/astronomer/astronomer-providers/blob/b2dade827ad8425952b2f5313b6a2863cb0c3e5e/astronomer/providers/snowflake/operators/snowflake.py#L217), we need to verify if the task has already completed before deferring it to prevent unnecessary deferring. This way, we can skip deferring the task if it has already been finished.
=> Check whether the task finishes before deferring the task for DataprocSubmitJobOperatorAsync

astronomer/providers/amazon/aws/operators/batch.py, tests/amazon/aws/operators/test_batch.py
With the change in PR https://github.com/astronomer/astronomer-providers/pull/1087, we called `submit_job` and assigned its output to a local variable `job_id` and then used this local variable `job_id` to describe on the job subsequently by passing it as parameter to the describe method. But, the `submit_job` method implicitly assigns the `job_id` as an instance attribute and it returns `None`. Hence, `self.job_id` actually contains the `job_id` and the local variable `job_id` which was capturing the output of `submit_job` was assigned `None` value and hence the subsequent method to describe job was failing as it was calling the describe on a `None` (job_id) type value.
The commit fixes this issue by referencing `self.job_id` instead of using the `None` valued local variable `job_id` …
=> Use `self.job_id` to describe Batch job

astronomer/providers/dbt/cloud/operators/dbt.py, tests/dbt/cloud/operators/test_dbt.py
Currently, if DBT Cloud job run is cancelled our async operator just logs 
a message in the task logs that the job is cancelled and marks the task
status as success.
The PR now raises an AirflowFailException to mark the task as failed 
and that it is not retried by Airflow as the user may not pay attention to 
re-cancel the job or may not have set retries to 0 for the task in their DAG.
closes: #1081
=> Mark DBT cloud job run failed if cancelled by raising AirflowFailException

astronomer/providers/amazon/aws/operators/redshift_sql.py, tests/amazon/aws/operators/test_redshift_sql.py
=> Check whether the task finishes before deferring the task for RedshiftSQLOperatorAsync

.circleci/integration-tests/Dockerfile.astro_cloud, Makefile
The runtime image corresponds to Airflow 2.6.1 and 
has upgraded below packages in it: 
astronomer-providers to 1.15.5
openlineage-airflow to 0.25.0
=> Upgrade runtime image to 8.2.0

astronomer/providers/databricks/operators/databricks.py, tests/databricks/operators/test_databricks.py
=> Check whether the task finishes before deferring the task for DatabricksSubmitRunOperatorAsync

astronomer/providers/databricks/operators/databricks.py, tests/databricks/operators/test_databricks.py
=> Check whether the task finishes before deferring the task for DatabricksRunNowOperatorAsync

Makefile, dev/scripts/replace_dependencies.py
According to the discussion with @pankajkoti yesterday, when testing [apache-airflow-providers-cncf-kubernetes](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/), we cannot use the pinned version but need to use the [source distribution](https://files.pythonhosted.org/packages/a9/59/fcd15c3d3b9b26bab4df980f59b1e86769bf7b18edbd18afca5db973b746/apache-airflow-providers-cncf-kubernetes-6.1.0.tar.gz) instead. However, our current script does not support parsing this kind of string. This PR replace the original string manipulation and uses pip internal to parse the package string instead
=> ci(dev/scripts): use pip internal to parse RC_PROVIDER_PACKAGES

astronomer/providers/amazon/aws/hooks/redshift_data.py, astronomer/providers/amazon/aws/operators/redshift_data.py, astronomer/providers/amazon/aws/operators/redshift_sql.py, tests/amazon/aws/operators/test_redshift_data.py
=> Check whether the task finishes before deferring the task for RedshiftDataOperatorAsync

astronomer/providers/amazon/aws/operators/sagemaker.py, tests/amazon/aws/operators/test_sagemaker.py
=> Check whether the task finishes before deferring the task for SageMakerTrainingOperatorAsync

astronomer/providers/sftp/hooks/sftp.py, astronomer/providers/sftp/sensors/sftp.py, astronomer/providers/sftp/triggers/sftp.py, tests/sftp/hooks/test_sftp.py, tests/sftp/sensors/test_sftp.py, tests/sftp/triggers/test_sftp.py
The PR address the following feature requests mentioned in the issue as per user feedback:
- If the ssh host key and the SSH command line tool outputs are in the format of `ecdsa-sha2-nistp256`, then ideally the SFTP hook should recognise this format without the need for it to be edited (by prepending `ssh-`) just to get it working with Astronomer’s SFTP library
- If no_host_key_check: False on the connection, but doesn’t include a host key, it lets the connection through just fine and effectively doesn’t validate the server. This seems wrong. In fact, the whole need to enable host key checking by default seems wrong. Host key check should be enabled by default (so by default users are then forced to use secure/validated connections), and if it is needed to test locally without ssh host …
=> Enhance SFTP Async sensor addressing user feedback

astronomer/providers/amazon/aws/operators/redshift_sql.py, astronomer/providers/apache/hive/sensors/named_hive_partition.py, tests/apache/hive/sensors/test_named_hive_partition.py
Similar to [SnowflakeOperatorAsync](https://github.com/astronomer/astronomer-providers/blob/b2dade827ad8425952b2f5313b6a2863cb0c3e5e/astronomer/providers/snowflake/operators/snowflake.py#L217), we want to check whether the task has finished before it's deferred. For most sensors, we have a poke method in its sync counter part which can help us do such check.
=> feat(hive): check state before deferring NamedHivePartitionSensorAsync

astronomer/providers/amazon/aws/sensors/s3.py, astronomer/providers/amazon/aws/triggers/s3.py, tests/amazon/aws/sensors/test_s3_sensors.py
=> Check whether the task finishes before deferring the task for S3KeySensorAsync

setup.cfg
dependency conflict between `protobuf<=3.20.0` and `google-ads>=20.0.0` after we upgrade google provider to [10.1.0rc2](https://pypi.org/project/apache-airflow-providers-google/10.1.0rc2)
Close: #1119
=> build(setup.cfg): remove protobuf constraint

astronomer/providers/amazon/aws/operators/sagemaker.py, astronomer/providers/databricks/operators/databricks.py, astronomer/providers/google/cloud/operators/bigquery.py, astronomer/providers/google/cloud/sensors/gcs.py
On https://github.com/astronomer/astronomer-providers/pull/1109, we're testing RC releases announced on airflow [issue 31322](https://github.com/apache/airflow/issues/31322). This PR fixes the mypy warnings on that branch
=> style(mypy): fix mypy warnings

.circleci/config.yml, RELEASING.rst
Currently, we run the `generate-constraints` job in CircleCI for a matrix of 
Python and Airflow versions (total 9 jobs at the moment) for every PR that
we create and any additional commits we push to the PR also trigger that
job. This is unnecessary.
The PR modifies the `generate-constraints` job to be run only on the `main` 
and `release` (branches starting with the `release` prefix) branches. It also 
updates the `RELEASING.rst` to suggest that release branches need to have 
that practice although it's unconventional not to do so.
=> Modify constraints job to run only on release and main branches

.github/workflows/test-rc-release.yaml
Automate the RC testing process through the GitHub Actions workflow.
It can accept one of the following two arguments.
* rc_testing_branch: existing rc testing branch (e.g., `rc-test-2023-05-20T05-10-46UTC`)
* issue_url: the URL to the airflow issue that announces rc testing
=> Add test rc GitHub workflow

.github/workflows/test-rc-release.yaml
Address comments on https://github.com/astronomer/astronomer-providers/pull/1107
* reword test-rc-branch workflow descriptions
* use export-rc-testing-branch-name output to checkout in trigger-master-dag
=> Test rc branch workflow quick fix

.github/workflows/deploy-integration-tests.yaml, .github/workflows/test-rc-release.yaml
* reduce the wait time to 30 minutes for providers-integration-tests-on-KE if providers-integration-tests is not deployed
* merge wait for deployment and trigger master dag job into the same job but different step
Closes: #1136
=> Optimize deployment workflow

astronomer/providers/amazon/aws/example_dags/example_emr_sensor.py, astronomer/providers/apache/hive/example_dags/example_hive.py, astronomer/providers/apache/livy/example_dags/example_livy.py
Note that this loguri is a fake s3 bucket which doesn't not exist and used only for bypassing this issue
Closes: #1120, #1121, #1123
=> add loguri to EmrCreateJobFlowOperator for bypassing https://github.com/apache/airflow/issues/31480

astronomer/providers/databricks/operators/databricks.py, astronomer/providers/google/cloud/operators/bigquery.py
PR #1143 showed in its checks that all mypy checks are successful,
but after merging to main, main reported additional couple of failures. 
The commit tried to resolve those mypy failures too by ignoring them 
as we do mean to override the methods as they are being implemented 
in the respective providers.
=> Fix additional mypy failures newly reported in main

dev/Dockerfile
Currently, the master DAG does not load locally as it complains about importing the slack provider which is not installed in the image; this provider is needed by the report generation task in the master DAG. The commit installs the apache-airflow-providers-slack in the local dev image so that we could also run the master_dag locally.
=> Include apache-airflow-providers-slack in dev image

.circleci/integration-tests/Dockerfile.astro_cloud, astronomer/providers/amazon/aws/example_dags/example_aws_nuke.py, dev/Dockerfile
It has been observed that sometimes the virtual clusters launched 
by EMR containers are not cleaned up. It is not possible to nuke 
them using AWS nuke as this resource type is not exposed, 
additionally, it has not been exposed to delete them in the 
AWS console too. The only way to delete them is using AWS CLI 
and hence we're adding a task in the nuke DAG to delete those 
using AWS CLI.
=> Terminate running virtual clusters launched for EMR containers

dev/Dockerfile.aws
We use the dev/Dockerfile.aws to build images locally for testing 
AWS example DAGs. Images built using this file currently does not 
support running example DAGs like the nuke dag, emr_eks_pi_job_dag 
due to missing dependencies. The commit adds the missing dependencies. 
Additionally, since most of the developers are on ARM64 architectures, 
it makes sense to update the AWS CLI installation to refer to the aarch64 binary 
instead of the amd64; so we're also changing that in the commit.
=> Update the dev AWS Dockerfile to support all AWS example DAGs

.circleci/integration-tests/Dockerfile.astro_cloud
We introduce an error https://github.com/astronomer/astronomer-providers/pull/1151/files#diff-ffdd07a66f69f4d478483b9856c4b5442796955f3d624738b5b9c981905f204dR33 due to some typos
=> ci(integration-tests): fix installation breakline typo

astronomer/providers/amazon/aws/example_dags/delete_stale_emr_vpcs.sh, astronomer/providers/amazon/aws/example_dags/example_aws_nuke.py
Delete leftover/stale VPCs launched by EMR-EKS
The PR adds a script to do the following steps for deleting the VPCs:
1. List the VPCs with the prefix `eksctl-providers-team-eks`
2. Firstly delete all the association of the VPCs, viz. subnets,
Internet gateways, route tables, security groups, and network
interfaces
3. By default, AWS takes care of the main route table and the default
security groups are not deleted as they have further dependencies
associated with them, which we do not touch in our script.
Hence we're safe here.
4. Finally, delete the VPCs and report the exit status of these final
deletion commands as the task status. We do not want to `set -e`
in the beginning of the script as the association failures can be
ignored if we're able to delete the VPCs.
The PR then adds this …
=> Delete leftover/stale VPCs launched by EMR-EKS

astronomer/providers/amazon/aws/example_dags/example_delete_eks_cluster_and_role_policies.sh, astronomer/providers/amazon/aws/example_dags/example_emr_eks_containers_job.py
This commit refactors the cleanup script that automates 
the deletion of resources launched by the EMR_EKS_PI_JOB DAG. 
The script deletes an IAM role, detaches policies from the role, 
removes the role from associated instance profiles, deletes a 
virtual cluster (EMR Containers), and deletes an EKS cluster and 
its associated node group. The major change with the refactoring 
is to include checks to avoid failures if resources don't exist because 
the creation script for creating the resources might have created 
partial resources and could have failed without fully completing the 
creation.
=> Refactor EMR EKS cleanup script to handle failures gracefully

astronomer/providers/databricks/operators/databricks.py, astronomer/providers/google/cloud/operators/kubernetes_engine.py, tests/google/cloud/operators/test_kubernetes_engine.py
=> Check whether the task finishes before deferring the task for GKEStartPodOperatorAsync

.circleci/integration-tests/master_dag.py, astronomer/providers/amazon/aws/example_dags/example_aws_nuke.py, dev/Dockerfile.aws, dev/docker-compose.yaml
It is observed that when 2 deployments are run in parallel, 
their master DAGs trigger the nuke task which cleanup the 
resources and if one master DAG finished running before 
the other one across the deployments, the other deployment's
master DAG tasks will fail as the resources will no longer be 
available. To mitigate this, we remove the nuke DAG trigger 
from the master DAG and instead plan to schedule the master 
DAG only from one of the provider integration tests 
deployment (e.g. CeleryExecutor) by using the env var 
"AWS_NUKE_DAG_SCHEDULE". We also want to be alerted in
our Slack channel if one of the nuke tasks fail and hence also 
add a report task for the DAG.
=> Remove AWS nuke DAG from master DAG & accept DAG schedule param 

astronomer/providers/amazon/aws/sensors/s3.py, astronomer/providers/amazon/aws/triggers/s3.py, tests/amazon/aws/sensors/test_s3_sensors.py, tests/amazon/aws/triggers/test_s3_triggers.py
if soft_fail is set to true then raise AirflowSkipException. We may need to replicate this to other sensor too
closes: https://github.com/astronomer/astronomer-providers/issues/1149
=> Handle soft fail for s3keysensor

.circleci/integration-tests/master_dag.py, astronomer/providers/microsoft/azure/example_dags/example_adf_run_pipeline.py
1. Remove hardcoded resource_group_name value from default arg in example_async_adf_run_pipeline DAG
2. Updated unique env info master_dag docs
=> Remove hardcoded resource_group_name value from default arg in example_async_adf_run_pipeline DAG

astronomer/providers/cncf/kubernetes/operators/kubernetes_pod.py, astronomer/providers/cncf/kubernetes/triggers/wait_container.py, tests/cncf/kubernetes/operators/test_kubernetes_pod.py
=> Check whether the task finishes before deferring the task for KubernetesPodOperatorAsync

.github/workflows/test-rc-release.yaml
Check whether the RC testing announcement (e.g., https://github.com/apache/airflow/issues/31322) has been made on [apache-airflow](https://github.com/apache/airflow/). If there's an announcement and we do not have an existing open issue with the title `[DO NOT MERGE] Test RC provider packages for $rc_issue_url`, then trigger the rest of the RC provider testing workflow
=> ci(github-action): periodically parse oss airflow issue to check provider release

astronomer/providers/google/cloud/example_dags/example_gcp_nuke.py
The current GCP Nuke DAG schedule is colluding with our
night runs and hence we're observing GCP DAG failures
at times. This allows us to set the nuke dag schedule with
an environment variable and we plan to run it at the same
time as AWS nuke DAG which runs twice; once before and once
after our nightly run.
=> Use env variable to control GCP nuke DAG schedule

astronomer/providers/amazon/aws/sensors/s3.py, astronomer/providers/amazon/aws/triggers/s3.py, tests/amazon/aws/sensors/test_s3_sensors.py, tests/amazon/aws/triggers/test_s3_triggers.py
closes: https://github.com/astronomer/astronomer-providers/issues/1166
=> Handle check_fn in S3KeySensor

astronomer/providers/amazon/aws/hooks/s3.py, astronomer/providers/amazon/aws/sensors/s3.py, astronomer/providers/amazon/aws/triggers/s3.py, tests/amazon/aws/hooks/test_s3_hooks.py, tests/amazon/aws/triggers/test_s3_triggers.py
closes: https://github.com/astronomer/astronomer-providers/issues/1154
=> Add use_regex param in S3KeySensor

astronomer/providers/amazon/aws/example_dags/example_redshift_cluster_management.py
=> Mark Async Redshift Cluster DAG failed if any of the tasks fail

.circleci/integration-tests/master_dag.py, astronomer/providers/microsoft/azure/example_dags/example_adf_run_pipeline.py
We have recently observed that the current usage of the "factory_name" as a static value. Taking it from an environment variable will help us run the DAG in parallel.
=> Setting Factory name as ENV Var

astronomer/providers/amazon/aws/example_dags/example_emr_eks_containers_job.py
fail.
Tested DAG locally after update
=> Mark EMR EKS Container DAG failed if any of the tasks fail

astronomer/providers/amazon/aws/example_dags/example_redshift_data.py
=> Mark Async Redshift Data DAG failed if any of the tasks fail

astronomer/providers/amazon/aws/example_dags/example_redshift_sql.py
=> Mark Async Redshift sql DAG failed if any of the tasks fail

astronomer/providers/core/example_dags/example_external_task.py
=> Mark External Task DAG failed if any of the tasks fail

astronomer/providers/dbt/cloud/example_dags/example_dbt_cloud.py
=> Mark DBT Cloud DAG failed if any of the tasks fail

astronomer/providers/google/cloud/example_dags/example_bigquery_queries.py
=> Mark Async bigquery DAG failed if any of the tasks fail

astronomer/providers/amazon/aws/example_dags/example_aws_nuke.py, astronomer/providers/amazon/aws/example_dags/example_delete_stale_emr_iam_roles.sh
Ideally, the "emr_eks_pi_job" DAG should delete the IAM roles it creates. 
However, there were observed occurrences where the IAM roles were not 
deleted, most probably because we did not allow to run the delete cluster 
task to completion or did not allow the task to run altogether due to killing 
of the deployment before it finished running. With this commit, we add a 
script that automates the deletion of such stale IAM roles by first detaching 
its associated policies. We call this script as a task from the AWS nuke DAG 
which is scheduled to run after the end of the master DAG run.
=> Delete stale IAM roles left by EMR EKS PI job DAG

.github/workflows/delete-branch-on-pr-close.yaml
Our current GitHub configuration automatically deletes the branches
when PRs are merged. But for closed PRs, the branches are not deleted
and they remain stale. We have cases like testing the RCs, where we do
not want to merge the PR but only close it after verifying that our RCs
do not cause static check or tests failure. For such RC testing branches, 
this action will delete the branches upon closing the PR. 
In case, we want to reopen the PR, we need to click the button to 
restore the branch first and only then the reopen PR option will be
enabled by GitHub. I made an attempt to restore the branch if the event
is of type PR reopen, but that event cannot happen when the branch
no longer exists. Hence, we will have to manually click on the restore
button first if we want to reopen the …
=> Automate deletion of RC testing branch once PR is closed

RELEASING.rst
Some text is in Markdown format but not in RST, resulting in poor formatting.
=> docs(RELEASING): fix format

RELEASING.rst, pyproject.toml
Since version 3.4.0, commitizen introduce [version_schemes](https://github.com/commitizen-tools/commitizen/blob/master/CHANGELOG.md#v340-2023-06-20). By default, python project uses `pep440` instead of `semver` (check [here](https://commitizen-tools.github.io/commitizen/bump/#-version-scheme) for more information). As we use "semver" in this project, I set the version_scheme to "semver" to fix a version bumping error
=> Set version scheme to semver

CHANGELOG.rst
The old text uses the markdown format. this pr fixing it as the rst format
=> docs(CHANGELOG): fix format

.circleci/integration-tests/master_dag.py
Recently we have noticed that we do not publish astronomer-provider version in our test report, this PR will display the provider version in every report.
Tested the Report
=> Display astronomer-provider version in slack report

astronomer/providers/cncf/kubernetes/operators/kubernetes_pod.py, astronomer/providers/cncf/kubernetes/triggers/wait_container.py, tests/cncf/kubernetes/operators/test_kubernetes_pod.py
This reverts commit 89ccc7ec1ad5c38a1665b50f649e9153d3ca2f37.
PR #1104 adds logic to poke for Pod status before putting the status 
check on deferral. However, it is observed that our DAG fails always 
when we go on checking the status.phase on pods as Pod.status is None 
before the pod gets scheduled on a node. So, in most scenarios it does 
not make sense to check for the pod status immediately to verify that the 
pod has completed its desired execution and hence, we revert this poke 
in case of Kubernetes Pod operator.
closes: #1208
=> Revert "feat(kubernetes): check state before deferring KubernetesPodOperatorAsync (#1104)"

astronomer/providers/cncf/kubernetes/example_dags/example_kubernetes_pod_operator.py
Remove retries from the example DAG to uncover potential issues.
=> Remove retries from KPO Async DAG

.github/workflows/test-rc-release.yaml
we should set the main branch as base instead of the changed branch
=> ci(github-actions): fix wrong base branch used when creating pull request

.github/workflows/test-rc-release.yaml
In step `wait-for-deployment-to-be-ready-and-trigger-master-dag`, we use the output of `export-rc-testing-branch` but we did not specify it as needs of `wait-for-deployment-to-be-ready-and-trigger-master-dag`
=> ci(github-actions): fix missing needed in test rc release

.github/workflows/deploy-integration-tests.yaml, .github/workflows/test-rc-release.yaml, .github/workflows/trigger-dag-reuse-wf.yaml, Makefile, dev/integration_test_scripts/trigger_dag.py
* ci(github-actions):
* **fix** fix triggering failure due to astro_cloud subdomain change 
* **refactor**: extract common wait and trigger logic as a reusable workflow
For this workflow to work, we must set the latest subdomain to github secret as `ASTRO_SUBDOMAIN`. we used to hardcode it in the script, but I think it might be better for use to keep it secret
=> fix triggering failure due to astro_cloud subdomain change

setup.cfg
We need to pin this version as most of our users might not use the airflow on the main branch
related issue: https://github.com/apache/airflow/issues/32311
related PR: https://github.com/apache/airflow/pull/32312
=> build(setup.cfg): pin pydanctic to lower than 2.0.0

.github/workflows/deploy-integration-tests.yaml
With PR #1222, we made few change but also started passing
the same CE deployment secrets to KE deployment master DAG
trigger. As a result the KE DAG was not getting triggered. This
PR corrects the usage of needed creds to trigger KE DAG.
=> Correct KE creds passed while triggering master DAG

astronomer/providers/google/cloud/triggers/dataproc.py, tests/google/cloud/triggers/test_dataproc.py
- Remove param location and wait_timeout from the DataProcSubmitTrigger docs string since these do not belong to DataProcSubmitTrigger class. 
- Add Dataproc job object in DataProcSubmitTrigger yield event this will have some info about the job 
https://cloud.google.com/python/docs/reference/dataproc/latest/google.cloud.dataproc_v1.types.Job 
https://cloud.google.com/python/docs/reference/dataproc/latest/google.cloud.dataproc_v1.types.JobStatus
=> Add Dataproc job object in DataProcSubmitTrigger yield message

.github/workflows/test-rc-release.yaml
Today's announcement happen to be a bit later than our regular check. thus, @phanikumv suggests we can increase the check frequency
=> ci(github-actions): increate the frequency of airflow rc testing issue check

astronomer/providers/amazon/aws/example_dags/example_create_eks_kube_namespace_with_role.sh, astronomer/providers/amazon/aws/example_dags/example_delete_eks_cluster_and_role_policies.sh
It appears that the default region support in the latest release of eksctl (v0.148.0) is broken. A defect has already been raised for this issue, which you can find [here](https://github.com/weaveworks/eksctl/issues/6774). As a result of this problem, all of our eksctl commands were failing because we didn't have the "--region" command line option included. To work around this issue, I have temporarily added the "--region" option explicitly
=> Adding region option in eksctl commands

.github/workflows/deploy-integration-tests.yaml, .github/workflows/trigger-dag-reuse-wf.yaml
Currently, we have a static sleep time of [1800](https://github.com/astronomer/astronomer-providers/blob/d50a8b6150b541ca8cdc9c826a3e7c3bda7a00d3/.github/workflows/trigger-dag-reuse-wf.yaml#L45) seconds for the deployment to reach a healthy state. However, instead of relying on this fixed duration, we can implement a polling mechanism to check the health of the deployment. If the deployment is found to be unhealthy, we can Exit 1. This improvement will address the following issues:
1. We observed today that even when the deployment was unhealthy, our workflow still succeeded. This PR will prevent such occurrences in the future.
2. By implementing polling, we can reduce the overall execution time of the workflow. In most cases, deployments become healthy within 5-10 minutes, and with …
=> Adding logic to poll deployment health instead of static wait

.github/workflows/test-rc-release.yaml
https://github.com/astronomer/astronomer-providers/actions/runs/5538290617
=> ci(github-actions): fix missing organization_id and bearer_token

.circleci/config.yml, .github/workflows/delete-branch-on-pr-close.yaml, .pre-commit-config.yaml
Failures due to https://github.com/astronomer/astronomer-providers/pull/1240 changes (fixed in https://github.com/astronomer/astronomer-providers/pull/1242) can be detected through actionlint. Thus, adding this lint for preventing this kind of error in the future
=> Add actionlint

.circleci/integration-tests/master_dag.py, astronomer/providers/core/example_dags/example_external_task.py
Recently, we have noticed that our Master DAG and example_external_task DAG are throwing parsing errors due to a new [change](https://github.com/apache/airflow/commit/fd2687d0d51fa444f63aac705d843f30e5922319#diff-800088a475d2b93df93b7b497aba69eeb0485005be1d4dd5b414c46ab1c68023). We can only pass valid DAG [states](https://github.com/apache/airflow/blob/145b16caaa43f0c42bffd97344df916c602cddde/airflow/utils/state.py#L67C7-L67C18) in TriggerDagRunOperator. This PR will address this issue
=> Adding only valid DAG state for TriggerDagRunOperator

astronomer/providers/microsoft/azure/hooks/wasb.py
https://github.com/astronomer/astronomer-providers/pull/1241
We'll need to wait for the release of https://github.com/apache/airflow/issues/32568
=> style: fix mypy failure

.github/workflows/test-rc-release.yaml
If a new set of providers rc releases only providers that do not exist in this repo (e.g., https://github.com/apache/airflow/issues/32640), it still triggers the "Test providers RC releases" but will fail during commit as there's no change. This PR tries to skip this case
=> ci(github-actions): skip rc testing is no providers in this repo is changed

astronomer/providers/cncf/kubernetes/example_dags/example_kubernetes_pod_operator.py
In our KPO example test, we write some dummy data at path `/airflow/xcom/return.json` 
The intention of doing this would be probably to push this data in xcom 
but it does not push since `do_xcom_push` is false. 
so either we should set `do_xcom_push`  to true or remove `'echo \'{"message": "good afternoon!"}\' > /airflow/xcom/return.json' `
=> Enable `do_xcom_push` param in KPO example

tests/amazon/aws/xcom_backends/test_s3.py, tests/google/cloud/xcom_backends/test_gcs.py
Tests have been failing as observed in PR https://github.com/astronomer/astronomer-providers/pull/1252
for the missing import path pandas.util.testing. It is observed
the module was moved one level up in the Pandas 2.0.0 release 
and hence import the module from that path.
=> Correct testing module import path as per Pandas 2.0.0 release

astronomer/providers/databricks/operators/databricks.py, tests/databricks/operators/test_databricks.py
This fixes the issue that `job_name` is passed without `job_id` and gets `{"error_code":"INVALID_PARAMETER_VALUE","message":"Job 0 does not exist."}` error
=> fix(databricks): get jod_id from job_name for DatabricksRunNowOperatorAsync

.github/scripts/validate_release_commit.py, .github/workflows/deploy-integration-tests.yaml, .github/workflows/deploy-to-astro-cloud-reuse-wf.yaml, .github/workflows/release.yaml, RELEASING.rst
* add `release` workflow for automating tagging process
* fix missing `needs` in the test rc release workflow
* rename workflows
closes: #1201 
We'll need to allow `action@github.com` to push tag and commit to main
=> Automate part of the release process

astronomer/providers/amazon/aws/hooks/redshift_data.py
Currently, the redshift_data hook in the Amazon provider has 
a dependency on snowflake for it's utility to split sql strings. 
The PR removes this need by instead using the DbApiHook's 
`split_sql_string` which reliably parses the sql strings for us.
closes: #1259
=> Use DbApiHook's split_sql_string instead of snowflake utility in amazon provider

.github/workflows/release.yaml
* ci(github-actions):
* postpone the commit message check to python script as `github.event.pull_request` does not have commit message
* skip if the head message is not "Release \d+\.\d+\.\d+"
=> fix release github workflow failure

astronomer/providers/amazon/aws/example_dags/example_sagemaker.py
the current token life is 30min but dag take sometime more than 30min recently we got error that token expire so increasing the token lifetime
https://org-airflow-team-org.astronomer.run/dfi0rona/dags/example_async_sagemaker/grid?dag_run_id=sagemaker_dag_example_async_sagemaker_2023-07-26&task_id=test_model&tab=logs
=> Increase sts token life for segmaker

.circleci/config.yml, .circleci/scripts/pre_commit_readme_extra.py, .circleci/scripts/pre_commit_setup_cfg_python_3_11_all_extra.py, .pre-commit-config.yaml, setup.cfg, tests/core/triggers/test_external_task.py
Run unit tests for Python3.11
exclude hive extra from it because of issue https://github.com/cloudera/python-sasl/issues/30
=> Run test for Python-3.11

astronomer/providers/amazon/aws/triggers/s3.py, tests/amazon/aws/triggers/test_s3_triggers.py
closes: https://github.com/astronomer/astronomer-providers/issues/1213
Airflow S3Sensor and astronomer-provider S3SensorAsync call check_fn param with different param. This PR restrict S3SensorAsync to call check_fn with the same param as in the Airflow sensor
=> Call S3 sensor check_fn only with file size attribute

astronomer/providers/amazon/aws/sensors/batch.py, astronomer/providers/amazon/aws/sensors/emr.py, astronomer/providers/amazon/aws/sensors/redshift_cluster.py, astronomer/providers/amazon/aws/sensors/s3.py, astronomer/providers/apache/hive/sensors/hive_partition.py, astronomer/providers/core/sensors/external_task.py, astronomer/providers/dbt/cloud/sensors/dbt.py, astronomer/providers/google/cloud/sensors/bigquery.py, astronomer/providers/google/cloud/sensors/gcs.py, astronomer/providers/http/sensors/http.py, astronomer/providers/microsoft/azure/sensors/data_factory.py, astronomer/providers/microsoft/azure/sensors/wasb.py, astronomer/providers/sftp/sensors/sftp.py, astronomer/providers/snowflake/sensors/snowflake.py, astronomer/providers/utils/sensor_util.py, tests/amazon/aws/sensors/test_redshift_sensor.py, tests/amazon/aws/sensors/test_s3_sensors.py, tests/apache/hive/sensors/test_hive_partition.py, tests/google/cloud/sensors/test_bigquery.py, tests/microsoft/azure/sensors/test_wasb.py, tests/sftp/sensors/test_sftp.py, tests/snowflake/sensors/test_snowflake.py
closes: https://github.com/astronomer/astronomer-providers/issues/1170
Handle soft_fail param for sensor
TODO
=> Handle soft fail

.github/scripts/validate_release_commit.py, .github/workflows/release.yaml
* fix release commit validation step failure
* we'll need to quote the commit message when running the bash script
* change the regex to check the release commit to include the PR number
* Our release message format is something like "Release 1.0.0 (#123)" instead of "Release 1.0.0" 
* use BOT_ACCESS_TOKEN to push the git tag
* remove bump dev version step for now as it will fail due to commitizen behavior
=> Fix automate process

dev/integration_test_scripts/replace_dependencies.py
=> Fix typo in rc testing script docstring param cncf_url -> url for PyPI url

.circleci/integration-tests/master_dag.py
Recently we started testing example dags with runtime Python version images and we observed a need to get Python version info in report
=> Adding Python version in Master DAG slack report

.circleci/config.yml
Currently, main branch is using an old cache for CircleCI jobs. 
We already have a hash for setup.cfg in the key, but this does 
not allow us to use newer upstream dependencies when they 
are released as there is no change in setup.cfg due to no version 
pins. To allow bursting cache, leveraging the use of environment 
variables. Have added a CACHE_VERSION env variable in our 
project settings and set the value for it to today's date. We can 
update it as and when needed by changing the value to new date 
the next time we feel the need to burst the cache.
=> Use env var for cache version in cache key for CircleCI jobs

astronomer/providers/amazon/aws/example_dags/example_delete_eks_cluster_and_role_policies.sh
It is observed that the EKS cluster DAGs sometimes hangs 
on the CloudFormation Stack to be deleted. It just prolongs 
the task from its completion. Removing the sync wait as we 
could rely on it finishing async and if it fails, the Nuke DAG 
can take care of the deletion.
=> Remove sync wait for deletion of EKS cluster in EMR EKS DAG

Makefile, RELEASING.rst, dev/prepare_release_scripts/changelog_drafter.py
`make prepare-release` automates the following steps.
1. Create a new release branch from main
2. Update the version number
3. Write the changelog
This change pushes release automation one step forward. We still need to decide on the bump version and what should be included in the changelog manually, we might not be able to fully automate the process as of now
=> Simplify release steps through "make prepare-release" make target

.github/workflows/delete-branch-on-pr-close.yaml, .github/workflows/deploy-integration-tests.yaml, .github/workflows/reuse-wf-check-rc-release.yaml, .github/workflows/reuse-wf-deploy-to-astro-cloud.yaml, .github/workflows/reuse-wf-trigger-dag.yaml, .github/workflows/runtime-image-update.yaml, .github/workflows/test-rc-release.yaml
* extract check rc announcement as a reusable workflow
* use BOT_ACCESS_TOKEN for test-rc-release
* replace the fake account action@github.com with airflow-oss-bot@astronomer.io
* rename Reusable workflows to separate them from other workflows
* fix typo
=> Use personal access token in rc workflow and extract it as a separate reusable workflow

.circleci/integration-tests/master_dag.py
update command to get astronomer provider version
=> update command to get astronomer provider version

astronomer/providers/http/hooks/http.py, astronomer/providers/snowflake/hooks/snowflake_sql_api.py, tests/http/hooks/test_http.py
add keep_response parameter to HttpHookAsync to allow user to use the response after running HttpHookAsync.run
closes: #1321
=> add keep_response parameter to HttpHookAsync 

.circleci/config.yml, astronomer/providers/microsoft/azure/example_dags/example_adf_run_pipeline.py, astronomer/providers/microsoft/azure/hooks/data_factory.py, astronomer/providers/microsoft/azure/operators/data_factory.py, astronomer/providers/microsoft/azure/triggers/data_factory.py, setup.cfg, tests/microsoft/azure/operators/test_data_factory.py, tests/microsoft/azure/sensors/test_data_factory.py
This PR fixes the failure due to https://pypi.org/project/apache-airflow-providers-microsoft-azure/8.0.0rc1/
=> Fix azure provider breaking change

astronomer/providers/databricks/hooks/databricks.py, tests/databricks/hooks/test_databricks.py
Currently, if the API call results in a `ClientConnectorError`, it won't be properly handled, and it won't be eligible for retries. This adds the `ClientConnectorError` to the exceptions that trigger the databricks retry block.
=> Handle ClientConnectorError to allow for retries

.circleci/integration-tests/Dockerfile.astro_cloud, .pre-commit-config.yaml
Pinning connexion==2.14.2 due to issue with latest release version3.0.0
more context:https://astronomer.slack.com/archives/C01UJJEN0P3/p1699003495317799
=> Pinning connexion==2.14.2 due to issue with latest release version3.0.0

setup.cfg
The release of CNCF Kubernetes Airflow provider 7.9.0 includes PR https://github.com/apache/airflow/pull/35422 whih removes the PodLoggingStatus object that was getting returned that we are relying in our Async KPO operator. Since, it is a breaking change for our operator restrict the max version of the provider to 7.8.0 until which the operator works well for us. Additionally, since the Google KE engine operator also relies on the PodLoggingStatus, also restrict the max version for the Google provider to the previous stable version and restrict the dependent Kubernetes provider version to the one containing the PodLoggingStatus object
=> Pin max versions for CNCF Kubernetes and Google Airflow providers

.circleci/integration-tests/script.sh, .github/workflows/deploy-integration-tests.yaml, .github/workflows/reuse-wf-deploy-to-astro-cloud.yaml, .github/workflows/reuse-wf-trigger-dag.yaml, .github/workflows/test-rc-release.yaml, dev/integration_test_scripts/trigger_dag.py
As part of moving the deployments to the stage, we had to make some fixes in the script. sh and GitHub Actions files.
=> Fixes to move deployment to stage env

setup.cfg
This reverts commit 76d082c502a391bdb704e548cc56c1a421e2ffa3. 
Since even if we pin the max version, there could be a possibility that 
the cncf kubernetes provider version is upgraded in the deployment 
and hence the pin won't be effective. It was decided to revert the 
removal of required PodLoggingStatus object in Airflow OSS and 
corresponding PR has been merged which can be tracked in the linked 
issue.
closes: #1366
=> Revert "Pin max versions for CNCF Kubernetes and Google Airflow providers (#1359)"

astronomer/providers/databricks/hooks/databricks.py, tests/databricks/hooks/test_databricks.py
according to user feedbacks, 403 sometimes works after retry
=> feat(databricks): include 403 as retryable error

.circleci/integration-tests/master_dag.py, astronomer/providers/amazon/aws/example_dags/example_aws_nuke.py
Resolve the Slack notification failure in the Nuke DAG and include the deployment link for Cloud UI in the Master DAG
=> Resolve the Slack notification failure in the Nuke DAG and include the Cloud UI deployment link in the Master DAG

astronomer/providers/snowflake/example_dags/example_snowflake.py
As per RCA in #1383, to demonstrate multiple queries in a 
single statement, the queries need to be independent of 
each other as they get run in an async & indepedently of 
one another  after submission. Hence, correcting the example 
DAG to have queries independent of each other.
closes: #1383 
closes: #1385
=> Correct Snowflake example DAG to demonstrate multiple queries run

astronomer/providers/amazon/aws/sensors/batch.py, astronomer/providers/amazon/aws/triggers/batch.py, tests/amazon/aws/sensors/test_batch_sensors.py, tests/amazon/aws/triggers/test_batch.py
Deprecate `BatchSensorAsync` and fallback to `BatchSensor` with `deferrable=True`
The logic of `BatchSensorAsync` bas been contributed back to OSS airflow as part of `BatchSensor`
https://github.com/astronomer/astronomer-providers/blob/b5a9417919d8a13b8e519d2582ce705c4689b7c6/astronomer/providers/amazon/aws/sensors/batch.py#L46-L68
https://github.com/apache/airflow/blob/999b70178a1f5d891fd2c88af4831a4ba4c2cbc9/airflow/providers/amazon/aws/sensors/batch.py#L98-L133
=> Deprecate BatchSensorAsync

astronomer/providers/amazon/aws/operators/redshift_sql.py, astronomer/providers/snowflake/operators/snowflake.py
fix mypy failure in https://app.circleci.com/jobs/github/astronomer/astronomer-providers/45984
=> style(mypy): fix mypy error

astronomer/providers/amazon/aws/sensors/s3.py, astronomer/providers/amazon/aws/triggers/s3.py, tests/amazon/aws/sensors/test_s3_sensors.py, tests/amazon/aws/triggers/test_s3_triggers.py
This reverts commit d6cbd8ea5fa0b660e6f734c32914df4950ac02e6.
=> Revert "Deprecate S3KeysUnchangedSensorAsync (#1392)"

astronomer/providers/amazon/aws/operators/emr.py, astronomer/providers/amazon/aws/triggers/emr.py, tests/amazon/aws/operators/test_emr.py, tests/amazon/aws/triggers/test_emr.py
This reverts commit 60546e4cc22d25d81b6b75a449ba21e4cc30db25.
=> Revert "Deprecate EmrContainerOperatorAsync (#1393)"

.circleci/integration-tests/master_dag.py
This PR is to test the astronomer logging provider for non-ASCII character, as we have providers tests running on all cloud providers daily, This will help us test daily without creating additional deployments.
=> Add non-ASCII logs check task in master dag

.circleci/integration-tests/master_dag.py
[PR](https://github.com/astronomer/astronomer-providers/pull/1427) introduced a bug due to which the airflow version was getting displayed incorrectly
=> Fix master DAG with airflow version

astronomer/providers/amazon/aws/hooks/redshift_cluster.py, astronomer/providers/amazon/aws/operators/redshift_cluster.py, astronomer/providers/amazon/aws/triggers/redshift_cluster.py, setup.cfg, tests/amazon/aws/operators/test_redshift_cluster.py
Deprecate redshift_cluster operators and fallback to their OSS counter part` with `deferrable=True`
This is blocked by [the release of https://github.com/apache/airflow/pull/36416](https://github.com/apache/airflow/issues/36644) as the logic of checking cluster_state before deferring has not yet been contributed back.
Most of the logic of these operators has been contributed back to OSS airflow
=> Deprecate RedshiftDeleteClusterOperatorAsync, RedshiftPauseClusterOperatorAsync and RedshiftResumeClusterOperatorAsync operators

astronomer/providers/amazon/aws/hooks/emr.py, astronomer/providers/amazon/aws/sensors/emr.py, astronomer/providers/amazon/aws/triggers/emr.py, tests/amazon/aws/sensors/test_emr_sensors.py
Deprecate EmrJobFlowSensorAsync and fallback to their OSS counterpart `EmrJobFlowSensor` with `deferrable=True`
Most of the logic of these operators has been contributed back to OSS airflow
=> Deprecate EmrJobFlowSensorAsync

astronomer/providers/amazon/aws/example_dags/example_redshift_cluster_management.py
closes: #1432
The default max_attempts is 10. If the status is still in the state of "resuming," it raises a failure. Extend this max_attempts for a longer waiting time and fix the master_dag failure.
=> ci(providers/amazon): extend max_attempts for resume_redshift_cluster to 20

astronomer/providers/core/sensors/external_task.py, astronomer/providers/core/sensors/filesystem.py, astronomer/providers/core/triggers/external_task.py, astronomer/providers/core/triggers/filesystem.py
This PR just added a deprecation warning in the core provider to warn users about removal and encourage them to use the upcoming OSS sensor
closes: https://github.com/astronomer/astronomer-providers/issues/1413
=> Add deprecation warning in core provider

setup.cfg
Since, we bumped the minimum version for the Amazon provider to 8.16.0,
our constraints generation is failing in main as the provider version now needs
Airflow >= 2.6. Hence, bump the same.
=> Increase min airflow version to 2.6

astronomer/providers/microsoft/azure/hooks/data_factory.py, astronomer/providers/microsoft/azure/sensors/data_factory.py, astronomer/providers/microsoft/azure/triggers/data_factory.py, tests/microsoft/azure/sensors/test_data_factory.py
Deprecate AzureDataFactoryPipelineRunStatusSensorAsync and proxy it 
to its Airflow OSS provider's counterpart
related: #1412
=> Deprecate AzureDataFactoryPipelineRunStatusSensorAsync

.circleci/config.yml, setup.cfg
Although we attempted to increase Airflow version in #1438,
constraints generation is still failing in main as we try to generate
them on Airflow 2.4.3. We no longer would need to generate constraints
for Airflow 2.4.3, as we have the min Airflow version to 2.6.0 now.
With that we also remove the duplicate job in CI for Python 3.11
constraints generation
Additionally, this PR also bumps the min Python version to 3.8,
we also do not already run tests on Python 3.7 in our CI.
=> Bump python >= 3.8 and fix constraints generation

astronomer/providers/microsoft/azure/operators/data_factory.py, astronomer/providers/microsoft/azure/triggers/data_factory.py, tests/microsoft/azure/operators/test_data_factory.py
Deprecate AzureDataFactoryRunPipelineOperatorAsync and 
proxy it to its Airflow OSS provider's counterpart
related: #1412
=> Deprecate AzureDataFactoryRunPipelineOperatorAsync

astronomer/providers/amazon/aws/example_dags/example_aws_nuke.py, astronomer/providers/amazon/aws/example_dags/example_sagemaker.py, astronomer/providers/core/sensors/external_task.py, astronomer/providers/core/sensors/filesystem.py
Fix mypy failures (& ignore some) as observed in CI
=> Fix mypy failures

.circleci/integration-tests/Dockerfile.astro_cloud
Airflow operator readiness probes make use of Pendulum 2.x. With the release of Pendulum 3.x, the deployment is breaking. A [PR](https://github.com/astronomer/airflow-operator/pull/1775/files) has already been raised in the operator to address this issue. However, the fix has not been released yet. Therefore, downgrading the Pendulum version until the release is available.
=> Downgrade pendulum version 

astronomer/providers/dbt/cloud/hooks/dbt.py, astronomer/providers/dbt/cloud/operators/dbt.py, astronomer/providers/dbt/cloud/sensors/dbt.py, astronomer/providers/dbt/cloud/triggers/dbt.py, setup.cfg, tests/dbt/cloud/operators/test_dbt.py, tests/dbt/cloud/sensors/test_dbt.py
This PR deprecates the operator DbtCloudRunJobOperatorAsync 
and the sensor DbtCloudJobRunSensorAsync from the dbt provider 
by proxying them to their Airflow OSS provider's counterpart.
closes: #1414
=> Deprecate DbtCloudRunJobOperatorAsync and DbtCloudJobRunSensorAsync

dev/Dockerfile
Sets `AIRFLOW__CORE__TEST_CONNECTION=Enabled` in the 
Docker image to allow testing connections in a quick go.
=> Enable test connection for increasing local dev productivity

astronomer/providers/google/cloud/operators/dataproc.py, astronomer/providers/google/cloud/triggers/dataproc.py, tests/google/cloud/operators/test_dataproc.py
Deprecate `DataprocSubmitJobOperatorAsync` and proxy it
to its Airflow OSS provider's counterpart
=> deprecate DataprocSubmitJobOperatorAsync

astronomer/providers/apache/livy/hooks/livy.py, astronomer/providers/apache/livy/operators/livy.py, astronomer/providers/apache/livy/triggers/livy.py, setup.cfg, tests/apache/livy/operators/test_livy.py
Deprecate LivyOperatorAsync and proxy it to its 
Airflow OSS provider's counterpart
closes: #1421
=> Deprecate LivyOperatorAsync

astronomer/providers/google/cloud/sensors/bigquery.py, astronomer/providers/google/cloud/triggers/bigquery.py, tests/google/cloud/sensors/test_bigquery.py
Deprecate BigQueryTableExistenceSensorAsync and proxy them to their Airflow OSS provider's counterpart
=> deprecate BigQueryTableExistenceSensorAsync

astronomer/providers/google/cloud/gke_utils.py
Recent pre-commit formatting breaking the GKE DAG. This PR fixes it.
=> Change format as per PEP 8 conventions

astronomer/providers/microsoft/azure/sensors/wasb.py, astronomer/providers/microsoft/azure/triggers/wasb.py, setup.cfg, tests/microsoft/azure/sensors/test_wasb.py
Deprecate WasbPrefixSensorAsync and proxy it to its Airflow 
OSS provider's counterpart
closes: #1412
=> Deprecate WasbPrefixSensorAsync

tests/microsoft/azure/hooks/test_wasb.py
As suggested in https://github.com/matplotlib/matplotlib/issues/24148/#issuecomment-1279425975
=> Fix TestWasbHookAsyncConnection tests

README.rst
Add public documentation alerting the deprecation of providers and sensors 
closes: #1434
=> Add draft for deprecation notice

astronomer/providers/sftp/hooks/sftp.py, astronomer/providers/sftp/sensors/sftp.py, astronomer/providers/sftp/triggers/sftp.py, setup.cfg, tests/sftp/sensors/test_sftp.py
Deprecate SFTPSensorAsync and proxy it to its Airflow
OSS provider's counterpart
closes: #1419
=> Deprecate async SFTP sensor

.circleci/integration-tests/Dockerfile.astro_cloud
This reverts commit 6db2a4976575c7ddd67f7b7576a3c092ba5b3431.
closes: #1477
=> Revert "Downgrade pendulum version  (#1446)"

astronomer/providers/amazon/aws/operators/sagemaker.py, astronomer/providers/amazon/aws/triggers/sagemaker.py, setup.cfg, tests/amazon/aws/operators/test_sagemaker.py
Deprecate SageMakerTrainingOperatorAsync and proxy them to their Airflow OSS provider's counterpart.
this needs to wait for the release of https://github.com/apache/airflow/pull/36685
=> Deprecate SageMakerTrainingOperatorAsync

astronomer/providers/core/example_dags/example_astro.py, astronomer/providers/core/hooks/astro.py, astronomer/providers/core/sensors/astro.py, astronomer/providers/core/triggers/astro.py, astronomer/providers/package.py, tests/core/hooks/test_astro.py, tests/core/sensors/test_astro.py, tests/core/triggers/test_astro.py
- Introduce Astro Cloud connection type
- Add ExternalDeploymentSensor, which uses Astro API to monitor Astro DAG status or task status. 
Sensor expects external_dag_id as a required param and external_task_id as an optional param if external_task_id is provided then it monitors a task instance of task external_task_id otherwise monitors the overall status of  external_dag_id.  
Once the sensor execution starts it fetches the dag run for external_dag_id with status running or queued if found then waits for it to succeed or fail in the trigger component. if not found then return immediately and mark it a success.
~TODO;~
- ~Test case~
- ~Docs/example~
- ~probably monitor task group too~: This can't be done at moment because task group is just UI feature and not exposed externally …
=> Add ExternalDeploymentSensor

setup.cfg
In PRs
1. #1463 
2. #1464 
3. #1465 
I had pinned RC2 versions of the upstream providers and merged 
to main so that we can test regressions together on main.
This PR updates the RC2 versions to their corresponding release
versions. 
closes: #1418 
closes: #1411  
closes: #1410
=> Update upstream providers versions from RC versions

astronomer/providers/core/example_dags/example_external_deployment_task_sensor.py, astronomer/providers/core/sensors/external_task.py
closes: https://github.com/astronomer/astronomer-providers/issues/1461
=> Remove legacy API call to generate token

.circleci/integration-tests/Dockerfile.astro_cloud
Recently, we have been observing failures to build our 
integration tests docker images precisely at the step 
where we download the google cloud-sdk library. It has 
been observed that the previously working http URL is 
no longer available and we need to use a https URL. 
This PR corrects the same for successful build of the image.
closes: #1488
=> Correct google cloud-sdk download URL protocol to https from http

.github/workflows/deploy-integration-tests.yaml
Since we have deprecated astronomer-providers in 1.19.0, 
it would make sense to disable the scheduled workflow for 
running the integration tests on the providers deployment. 
We can re-enable it if we need to run the integration tests 
on the providers deployment again. This will help us save some
cloud costs on the resources used for running the integration 
tests.
Note that we still have a workflow that triggers build and deploy
whenever new upstream OSS providers RCs are out.
=> Disable scheduled run of providers integration tests

astronomer/providers/apache/hive/example_dags/example_hive.py, astronomer/providers/apache/livy/example_dags/example_livy.py, astronomer/providers/sftp/example_dags/example_sftp.py
Add task to remove ingress rule
=> Add task to revoke ingress rule

astronomer/providers/core/sensors/filesystem.py, astronomer/providers/google/cloud/extractors/bigquery.py, tests/google/cloud/extractors/test_bigquery.py
=> Fix bq extract arg change in upstream

.github/workflows/test-rc-release.yaml
This is with an intent to save some costs and running once at midnight should be sufficient.
=> Update test-rc job schedule to run only once at midnight

astronomer/providers/sftp/example_dags/example_sftp.py
We were not using correct task for cluster IP retrieval. Updated task name correctly.
=> Fix task name to get cluster IP using xcom

.circleci/integration-tests/master_dag.py
As we no longer have a DBT account, removing the DBT trigger task.
=> Remove DBT trigger task from master DAG

astronomer/providers/snowflake/sensors/snowflake.py, tests/snowflake/sensors/test_snowflake.py
Currently the SnowflakeSensorAsync does not propagate `parameters` to its parent class, SqlSensor. Because of this, `parameters` are not passed for execution and can cause task failures when attempting doing so.
=> Pass `parameters` to parent class in SnowflakeSensorAsync

astronomer/providers/snowflake/example_dags/example_snowflake_sensor.py, astronomer/providers/snowflake/sensors/snowflake.py
This PR fixes mypy error in https://github.com/astronomer/astronomer-providers/pull/1540 due to the latest provider release
=> style: fix mypy warning

astronomer/providers/microsoft/azure/hooks/wasb.py, docs/_ext/traverse_operators_sensors.py
Address feedback from @lzdanski on the deprecation status text 
Ref: https://astronomer.slack.com/archives/CGQSYG25V/p1724261555954379?thread_ts=1724153077.643379&cid=CGQSYG25V
=> Change deprecation status to Yes/No instead of icons

.circleci/integration-tests/Dockerfile.astro_cloud
We have migrated to Bookworm from Bullseye in runtime12. Astronomer providers' tests are now also moved to runtime12. Since Bookworm does not have JDK8, we are upgrading to the latest version to resolve this issue.
=> Update JDK17 in Dockerfile as per Bookworm requirement

.github/workflows/reuse-wf-deploy-to-astro-cloud.yaml
Recent https://github.com/apache/airflow/pull/42505 in airflow updated path of providers and system test. This PR addresses that.
=> FIxing provider system test path

.circleci/integration-tests/Dockerfile.astro_cloud
Noticed [CI](https://github.com/astronomer/astronomer-providers/actions/runs/11307013444/job/31448269612) job is failing due to hive version. Bumping the version
=> Fixing failures due to hive version

astronomer/providers/amazon/aws/example_dags/example_batch.py
With [PR](https://github.com/apache/airflow/issues/42882) deprecated all deprecated stuff is being removed as there would be a new major release of AWS provider. Is PR update example DAG with same
=> Replacing deprecating provider with overrides with container_overrides

.github/workflows/reuse-wf-check-rc-release.yaml, .github/workflows/reuse-wf-deploy-to-astro-cloud.yaml, .github/workflows/reuse-wf-trigger-dag.yaml, .github/workflows/runtime-image-update.yaml
The Ubuntu 20.04 Actions runner image will begin deprecation on 2025-02-01 and will be fully unsupported by 2025-04-01:
https://github.com/actions/runner-images/issues/11101
Used the following command to replace all the ocurrences:
```
find . -type f -exec sed -i -e 's/ubuntu-20.04/ubuntu-latest/g' {} +
```
=> Upgrade GitHub Actions Ubuntu version
